"use strict";
const admin=require('firebase-admin'),{google}=require('googleapis'),PDFDocument=require('pdfkit'),{Readable}=require('node:stream'),{createHash,randomUUID}=require('node:crypto');
const C=require('./colocacionesCoreV129');
if(!admin.apps.length)admin.initializeApp();
// Same accounts that can read and annotate this sector in app.js.
const OPERATORS=new Set(['info@tizpublicidad.com','giancarlo.pareja@gmail.com','carolina.flores@tizpublicidad.com','arielbenitezpublicidad@gmail.com']);
const ORIGINS=new Set(['https://tiz-publicidad.github.io','https://tiz---app.web.app','https://tiz---app.firebaseapp.com']);
const fail=(message,status=409)=>Object.assign(new Error(message),{status});
const ident=v=>{const s=C.text(v);if(!/^[\w-]{1,150}$/.test(s))throw fail('Identificador inválido.',400);return s};
async function operator(req){const h=req.get('authorization')||'';if(!h.startsWith('Bearer '))throw fail('Falta iniciar sesión.',401);const d=await admin.auth().verifyIdToken(h.slice(7));if(!OPERATORS.has(C.text(d.email).toLowerCase()))throw fail('Sin permiso para Colocaciones.',403);return C.text(d.email).toLowerCase()}
async function saveDraft(db,body,email){const a=C.cleanAction(body.action||{}),id=ident(a.id),ref=db.collection('colocacionesPendientes').doc(id),obraId=body.obraId?ident(body.obraId):'',obraRef=obraId?db.collection('obras').doc(obraId):null;await db.runTransaction(async tx=>{const snap=await tx.get(ref),os=obraRef?await tx.get(obraRef):null,old=snap.exists?snap.data():{};if(old.obraId)throw fail('El pendiente ya fue vinculado a una OT.');if(snap.exists&&!C.open(old))throw fail('La acción ya fue gestionada.');if(snap.exists&&C.text(old.actualizadoEn)!==C.text(body.version))throw fail('Otra persona modificó este pendiente. Actualizá la base.');if(obraRef&&(!os.exists||os.data().colocacionesGestion?.cierre?.cerrada))throw fail('La OT no está disponible o su colocación está cerrada.');const at=new Date().toISOString();if(!snap.exists&&body.action?.origen==='Planilla'&&body.action.estado==='Cerrada'&&a.datosPlanilla?.length){a.estado='Cerrada';a.fechaReal=C.iso(body.action.fechaReal);a.resultado=C.text(body.action.resultado)||'Terminada en la planilla original';a.gestionadaEn=at;a.gestionadaPor=email}const record={...a,id,registroId:'sinOT/'+id,creadoEn:old.creadoEn||at,creadoPor:old.creadoPor||email,actualizadoEn:at,actualizadoPor:email};if(obraRef){if(os.data().colocacionesGestion?.acciones?.[id])throw fail('La OT ya tiene una acción con esa identidad.');tx.update(obraRef,{[`colocacionesGestion.acciones.${id}`]:record,'colocacionesGestion.actualizadoEn':at});record.obraId=obraId}tx.set(ref,record)});return {ok:true,id,obraId}}
async function resolveDraft(db,body,email){
 const id=ident(body.id),ref=db.collection('colocacionesPendientes').doc(id),nextId=body.next?ident(body.next.id):'',nextRef=nextId?db.collection('colocacionesPendientes').doc(nextId):null;
 if(nextId===id)throw fail('La próxima acción necesita otra identidad.',400);
 await db.runTransaction(async tx=>{const snap=await tx.get(ref),ns=nextRef?await tx.get(nextRef):null;
 if(!snap.exists)throw fail('El pendiente ya no está disponible.');const old=snap.data();
 if(old.obraId||C.text(old.actualizadoEn)!==C.text(body.version))throw fail('El pendiente cambió. Actualizá la base.');
 if(ns?.exists)throw fail('La próxima acción ya existe.');
 const day=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Argentina/Buenos_Aires',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),at=new Date().toISOString();
 const r=C.resolveDraftAction(old,body.result||{},body.next,day,at,email);tx.set(ref,r.closed);
 if(nextRef)tx.set(nextRef,{...r.next,registroId:'sinOT/'+nextId});});return {ok:true,id,nextId};
}
async function linkDraft(db,body,email){const id=ident(body.id),obraId=ident(body.obraId),draftRef=db.collection('colocacionesPendientes').doc(id),ref=db.collection('obras').doc(obraId);return db.runTransaction(async tx=>{const [ds,os]=await Promise.all([tx.get(draftRef),tx.get(ref)]);if(!ds.exists||!os.exists)throw fail('El pendiente o la obra ya no están disponibles.');const a=ds.data(),o=os.data();if(a.obraId===obraId)return {ok:true,obraId,alreadyLinked:true};if(a.obraId)throw fail('El pendiente ya está asociado a otra OT.');if(C.text(a.actualizadoEn)!==C.text(body.version))throw fail('El pendiente cambió. Actualizá la base.');if(o.colocacionesGestion?.cierre?.cerrada)throw fail('Reabrí la colocación antes de asociar pendientes.');if(o.colocacionesGestion?.acciones?.[id])throw fail('La OT ya tiene una acción con esa identidad.');const at=new Date().toISOString();tx.update(ref,{[`colocacionesGestion.acciones.${id}`]:{...a,id,registroId:a.registroId||'sinOT/'+id,origen:'Base general',asociadoEn:at,asociadoPor:email},'colocacionesGestion.actualizadoEn':at});tx.update(draftRef,{obraId,asociadoEn:at,asociadoPor:email});return {ok:true,obraId}})}
async function planVisits(db,body,email){const selections=Array.isArray(body.selections)?body.selections:[];if(!selections.length||selections.length>20)throw fail('Elegí entre 1 y 20 acciones vinculadas a una OT.',400);const keys=new Set();for(const s of selections){const k=ident(s.obraId)+'/'+ident(s.actionId);if(keys.has(k))throw fail('Una acción está seleccionada dos veces.',400);keys.add(k)}const ids=[...new Set(selections.map(s=>s.obraId))],refs=ids.map(id=>db.collection('obras').doc(id)),id=randomUUID().replace(/-/g,''),at=new Date().toISOString();await db.runTransaction(async tx=>{const snaps=await Promise.all(refs.map(ref=>tx.get(ref)));const patches=snaps.map((s,i)=>{if(!s.exists)throw fail('La obra ya no existe.');return C.planPatch(s.data(),selections.filter(x=>x.obraId===ids[i]),body.day,id,email,at)});patches.forEach((p,i)=>tx.update(refs[i],p))});return {ok:true,id,count:selections.length}}
function makePdf(report){return new Promise((resolve,reject)=>{const doc=new PDFDocument({size:'A4',margin:38,bufferPages:true}),chunks=[];doc.on('data',b=>chunks.push(b));doc.on('error',reject);doc.on('end',()=>resolve(Buffer.concat(chunks)));function line(s,size=10,bold=false){if(doc.y>735)doc.addPage();doc.font(bold?'Helvetica-Bold':'Helvetica').fontSize(size).fillColor('#171717').text(C.text(s),{width:519}).moveDown(.35)}function title(s){doc.moveDown(.6);line(s,13,true)}
 doc.rect(38,35,519,5).fill('#e8b84b');doc.y=51;line('TIZ PUBLICIDAD · COLOCACIONES',16,true);line(`OT ${report.ot} · ${report.cliente}`,13,true);line(report.descripcion);line(`Domicilio: ${report.direccion||'A completar'} · Zona: ${report.zona||'A completar'}`);line(`Modalidad: ${report.modalidad||'A definir'} · Trabajo: ${report.tipoTrabajo||'A definir'}`);line('Actualizado: '+new Intl.DateTimeFormat('es-AR',{timeZone:'America/Argentina/Buenos_Aires',dateStyle:'short',timeStyle:'short'}).format(new Date()),9);
 title('CONTACTOS');report.contactos.forEach(c=>line(`${c.nombre} · ${c.cargo||'Sin cargo'} · ${c.telefono} · ${c.email}`));
 title('PENDIENTES Y RESULTADOS');report.acciones.forEach(a=>{line(`${C.week(a.fecha).label} · ${a.fecha||'Sin fecha'} · ${a.estado} · ${a.prioridad}`,10,true);line(a.titulo,11,true);line(`${a.tipo} · Responsable: ${a.responsable||'Sin asignar'} · ${a.direccion||report.direccion}`);if(a.contacto||a.hora)line(`Contacto: ${a.contacto||'Sin asignar'} · Horario: ${a.hora||'Todo el día'}${a.hora?' · '+a.duracion+' min':''}`);if(a.observaciones)line('Detalle: '+a.observaciones);if(a.resultado)line(`Resultado (${a.fechaReal||'sin fecha'}): ${a.resultado}`);if(a.cantidadReal||a.control||a.retrabajo)line(`Cantidad real: ${a.cantidadReal||'—'} · Control: ${a.control||'—'} · Retrabajo: ${a.retrabajo||'—'}`);doc.moveDown(.4)});
 title('PREPARACIÓN');report.preparacion.forEach(c=>{line(`${c.paso} · ${c.estado} · ${c.detalle}`);if(c.fecha||c.destinatario)line(`${c.fecha} · ${c.destinatario}`);if(c.url)line(c.url,9)});title('AYUDAMEMORIAS Y EXPERIENCIAS');report.notas.forEach(n=>line(`${n.tipo} · ${n.texto}`));const range=doc.bufferedPageRange();for(let i=0;i<range.count;i++){doc.switchToPage(i);doc.fontSize(8).fillColor('#666').text(`TIZ · OT ${report.ot} · ${i+1}/${range.count}`,38,790,{lineBreak:false})}doc.end()})}
async function folder(drive,parent){const meta=(await drive.files.get({fileId:parent,fields:'id,mimeType,trashed',supportsAllDrives:true})).data;if(meta.trashed||meta.mimeType!=='application/vnd.google-apps.folder')throw fail('La carpeta OT vinculada no está disponible.');const files=(await drive.files.list({q:`'${parent}' in parents and trashed = false and mimeType = 'application/vnd.google-apps.folder'`,fields:'files(id,name)',supportsAllDrives:true,includeItemsFromAllDrives:true,pageSize:1000})).data.files||[];const matches=files.filter(f=>C.norm(f.name)==='colocaciones');if(matches.length>1)throw fail('Hay varias carpetas Colocaciones. Revisá cuál corresponde.');if(matches.length)return matches[0].id;return (await drive.files.create({requestBody:{name:'Colocaciones',mimeType:'application/vnd.google-apps.folder',parents:[parent]},fields:'id',supportsAllDrives:true})).data.id}
async function archive(db,body,email){const obraId=ident(body.obraId),ref=db.collection('obras').doc(obraId),lease=randomUUID(),now=Date.now();let o;await db.runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw fail('No se encontró la OT.',404);o={...s.data(),id:obraId};if(Number(o.colocacionesGestion?.documento?.lockUntil)>now)throw fail('Esta ficha se está actualizando. Reintentá en unos segundos.');tx.update(ref,{'colocacionesGestion.documento.lockUntil':now+150000,'colocacionesGestion.documento.lease':lease})});
 try{const parent=C.text(o.driveFolderId)||C.text(o.driveFolderUrl).match(/\/folders\/([\w-]+)/)?.[1];if(!parent)throw fail('La OT todavía no tiene una carpeta de Drive vinculada.');let inherited=[];const qid=o.presupuestoId||o.cotizacionId;let source=o.entregaLogistica||{};if(qid){const q=await db.collection('presupuestos').doc(ident(qid)).get();if(q.exists)source={...source,...q.data().entregaLogistica}}if(source.contacto)inherited=[{id:'cotizacion',nombre:source.contacto,telefono:source.contactoTelefono,email:source.contactoEmail}];const saved=o.colocacionesGestion?.contactos||{},merged=new Map(inherited.map(c=>[c.id,c]));Object.entries(saved).forEach(([id,c])=>merged.set(id,{...(merged.get(id)||{}),...c}));const report=C.report({...o,entregaLogistica:source},[...merged.values()].filter(c=>!c.oculto));const signature=createHash('sha256').update(JSON.stringify(report)).digest('hex');const old=o.colocacionesGestion?.documento||{};if(old.signature===signature&&old.url&&!body.force)return {ok:true,...old,unchanged:true};
 const token=C.text(body.driveAccessToken);let auth;if(token){auth=new google.auth.OAuth2();auth.setCredentials({access_token:token})}else auth=new google.auth.GoogleAuth({scopes:['https://www.googleapis.com/auth/drive']});const drive=google.drive({version:'v3',auth}),folderId=await folder(drive,parent),name=`OT ${C.text(o.ot).replace(/[^\w-]/g,'')} - Colocaciones.pdf`,files=(await drive.files.list({q:`'${folderId}' in parents and trashed = false and name = '${name}'`,fields:'files(id,mimeType)',supportsAllDrives:true,includeItemsFromAllDrives:true,pageSize:1000})).data.files||[];if(files.length>1)throw fail('Hay varias fichas con el mismo nombre. Revisá los duplicados en Drive.');if(files[0]&&files[0].mimeType!=='application/pdf')throw fail('El archivo existente no es un PDF de Colocaciones.');const pdf=await makePdf(report),args={requestBody:{name},media:{mimeType:'application/pdf',body:Readable.from(pdf)},fields:'id,webViewLink',supportsAllDrives:true};const file=files[0]?(await drive.files.update({...args,fileId:files[0].id})).data:(await drive.files.create({...args,requestBody:{name,parents:[folderId]}})).data;const doc={fileId:file.id,url:file.webViewLink||`https://drive.google.com/file/d/${file.id}/view`,folderId,signature,fecha:new Date().toISOString(),usuario:email,error:'',lockUntil:0,lease:''};await ref.update({'colocacionesGestion.documento':doc});return {ok:true,...doc};
 }catch(e){await ref.update({'colocacionesGestion.documento.error':e.message||'No se pudo archivar la ficha.','colocacionesGestion.documento.lockUntil':0,'colocacionesGestion.documento.lease':''}).catch(()=>{});throw e}finally{await db.runTransaction(async tx=>{const s=await tx.get(ref);if(s.data()?.colocacionesGestion?.documento?.lease===lease)tx.update(ref,{'colocacionesGestion.documento.lockUntil':0,'colocacionesGestion.documento.lease':''})}).catch(()=>{})}}
exports.handleColocaciones=async(req,res)=>{const origin=req.get('origin');if(ORIGINS.has(origin)){res.set('Access-Control-Allow-Origin',origin);res.set('Vary','Origin')}res.set('Access-Control-Allow-Headers','Authorization, Content-Type');res.set('Access-Control-Allow-Methods','POST, OPTIONS');if(req.method==='OPTIONS')return res.status(204).send('');if(req.method!=='POST')return res.status(405).json({ok:false,error:'Método no permitido.'});try{const email=await operator(req),db=admin.firestore(),body=req.body||{};let result;if(body.mode==='list'){const snap=await db.collection('colocacionesPendientes').limit(2001).get();if(snap.size>2000)throw fail('La base superó 2000 pendientes. Revisá los registros.',422);const settings=await db.collection('configuracion').doc('colocacionesSheetV130').get(),cfg=settings.data();result={ok:true,sheet:cfg?.spreadsheetId?{url:cfg.url,fecha:cfg.sincronizadaEn||''}:null,rows:snap.docs.map(d=>({...d.data(),id:d.id})).filter(a=>!a.obraId)}}else if(body.mode==='save')result=await saveDraft(db,body,email);else if(body.mode==='resolve-draft')result=await resolveDraft(db,body,email);else if(body.mode==='link')result=await linkDraft(db,body,email);else if(body.mode==='plan')result=await planVisits(db,body,email);else if(body.mode==='archive')result=await archive(db,body,email);else if(body.mode==='read-source')result=await require('./colocacionesSheetV130').readSource(db,body);else if(body.mode==='configure-sheet')result=await require('./colocacionesSheetV130').configureSheet(db,body,email);else if(body.mode==='sync-sheet')result=await require('./colocacionesSheetV130').syncSheet(db,body,email);else throw fail('Operación inválida.',400);return res.json(result)}catch(e){return res.status(e.status||502).json({ok:false,error:e.message||'No se pudo actualizar Colocaciones.'})}};

