/* Shared operations only: no commercial or fiscal data. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.TIZColocacionesGeneralCore=api})(typeof window==='object'?window:globalThis,function(){
  'use strict';
  const text=v=>String(v??'').trim(), norm=v=>text(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
  function iso(v){const s=text(v);if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return '';const d=new Date(s+'T12:00:00Z');return !Number.isNaN(+d)&&d.toISOString().slice(0,10)===s?s:''}
  function shift(v,n){const d=new Date(iso(v)+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
  function week(v){if(!iso(v))return {label:'Sin fecha',start:'',end:''};const d=new Date(v+'T12:00:00Z'),start=shift(v,1-(d.getUTCDay()||7)),thursday=new Date(shift(start,3)+'T12:00:00Z'),year=thursday.getUTCFullYear(),jan4=`${year}-01-04`,janD=new Date(jan4+'T12:00:00Z'),first=shift(jan4,1-(janD.getUTCDay()||7)),number=1+Math.round((new Date(start+'T12:00:00Z')-new Date(first+'T12:00:00Z'))/604800000);return {start,end:shift(start,6),number,year,label:`${year}-W${String(number).padStart(2,'0')}`}}
  const open=a=>['Pendiente','Bloqueada'].includes(a.estado);
  const overdue=(a,day)=>open(a)&&!!iso(a.fecha)&&a.fecha<=shift(day,-2);
  function resolveDraftAction(old,result,next,day,at,email){
    if(!open(old))throw new Error('Esta acción ya fue gestionada.');
    if(!text(result.detalle)||!iso(result.fechaReal))throw new Error('Completá el resultado y la fecha real.');
    if(next){next=cleanAction(next);validate(next);if(next.fecha<day)throw new Error('La próxima acción debe tener fecha de hoy o posterior.');}
    if(!next&&old.tipo==='Colocación'&&!['conforme','aprobado'].includes(norm(result.control||old.control)))throw new Error('Registrá control conforme para terminar una colocación.');
    return {closed:{...old,control:result.control===undefined?old.control||'':text(result.control),retrabajo:result.retrabajo===undefined?old.retrabajo||'':text(result.retrabajo),cantidadReal:result.cantidadReal===undefined?old.cantidadReal||'':text(result.cantidadReal),estado:next?'Reprogramada':'Cerrada',resultado:text(result.detalle),fechaReal:result.fechaReal,gestionadaEn:at,gestionadaPor:email,actualizadoEn:at,actualizadoPor:email,siguienteId:next?.id||''},next:next?{...next,anteriorId:old.id,creadoEn:at,creadoPor:email,actualizadoEn:at,actualizadoPor:email}:null};
  }
  const visit=a=>['Relevamiento','Colocación','Entrega','Control final'].includes(a.tipo);
  function zone(address,explicit=''){if(text(explicit))return ['caba','capital federal','ciudad autonoma de buenos aires'].includes(norm(explicit))?'CABA':text(explicit);const n=' '+norm(address)+' ';if(/\b(caba|capital federal|ciudad autonoma de buenos aires)\b/.test(n))return 'CABA';return ''}
  function validate(a,{draft=false}={}){if(!text(a.titulo))throw new Error('Escribí la acción.');if(text(a.titulo).length>500)throw new Error('La acción supera 500 caracteres.');if(a.fecha&&!iso(a.fecha))throw new Error('Fecha inválida.');if(!draft&&(!iso(a.fecha)||!text(a.responsable)))throw new Error('Completá responsable y fecha de compromiso.');if(a.todoDia===false&&(!/^([01]\d|2[0-3]):[0-5]\d$/.test(a.hora||'')||!Number.isFinite(+a.duracion)||+a.duracion<15||+a.duracion>1440))throw new Error('Hora o duración inválida.');return a}
  function cleanAction(a){const out={};for(const k of ['id','titulo','tipo','responsable','fecha','prioridad','contactoId','estado','observaciones','direccion','zona','tipoTrabajo','cliente','referencia','hora','cantidadReal','control','retrabajo'])out[k]=text(a[k]);if(Array.isArray(a.datosPlanilla))out.datosPlanilla=a.datosPlanilla.slice(0,22).filter(p=>Array.isArray(p)&&p.length===2).map(p=>p.map(v=>text(v).slice(0,3000)));out.estado=['Pendiente','Bloqueada'].includes(out.estado)?out.estado:'Pendiente';out.todoDia=a.todoDia!==false;out.duracion=Number(a.duracion)||60;out.aviso=Number(a.aviso)||0;return validate(out,{draft:true})}
  function nearby(rows,anchor,day){if(!anchor||!visit(anchor.accion))return [];const z=zone(anchor.accion.direccion,anchor.accion.zona);if(!z)return [];const end=week(day).end;return rows.filter(r=>r.key!==anchor.key&&open(r.accion)&&r.accion.estado!=='Bloqueada'&&visit(r.accion)&&norm(zone(r.accion.direccion,r.accion.zona))===norm(z)&&(!r.accion.fecha||r.accion.fecha<=end)).map(r=>{const sameWork=!!anchor.tipoTrabajo&&norm(anchor.tipoTrabajo)===norm(r.tipoTrabajo),sameType=r.accion.tipo===anchor.accion.tipo;return {...r,score:2+(sameWork?2:0)+(sameType?1:0),motivo:`Misma zona: ${z}${sameWork?' · mismo tipo de obra':''}${sameType?' · misma tarea':''}${r.accion.fecha&&r.accion.fecha<day?' · pendiente vencido':''}`}}).sort((a,b)=>b.score-a.score||(a.accion.fecha||'9999').localeCompare(b.accion.fecha||'9999'))}
  function planPatch(o,selected,day,id,email,at){if(!iso(day))throw new Error('Indicá el día de salida.');if(o.colocacionesGestion?.cierre?.cerrada)throw new Error('La colocación está cerrada.');const p={};for(const item of selected){const a=o.colocacionesGestion?.acciones?.[item.actionId];if(!a||!open(a)||a.estado==='Bloqueada'||!visit(a))throw new Error('Una acción cambió o no admite visita. Volvé a revisar.');if(text(a.actualizadoEn||a.creadoEn)!==text(item.version)||text(a.fecha)!==text(item.fecha))throw new Error('Una acción fue modificada. Volvé a revisar.');p[`colocacionesGestion.acciones.${a.id}`]={...a,fecha:day,salidaId:id,fechaAnterior:a.fecha||'',actualizadoEn:at,actualizadoPor:email};p[`colocacionesGestion.eventos.salida${id}${a.id}`]={accion:`Salida agrupada: ${a.titulo}. Compromiso anterior ${a.fecha||'sin fecha'}; nueva fecha ${day}`,fecha:at,usuario:email}}p['colocacionesGestion.actualizadoEn']=at;p['colocacionesGestion.actualizadoPor']=email;return p}
  function report(o,contacts=[],legacy=[]){const g=o.colocacionesGestion||{};return {ot:text(o.ot),cliente:text(o.cliente),descripcion:text(o.desc),direccion:text(g.direccion||o.entregaLogistica?.domicilio||o.direccion),zona:text(g.zona),modalidad:text(g.modalidad),tipoTrabajo:text(g.tipoTrabajo),contactos:contacts.map(c=>({nombre:text(c.nombre),cargo:text(c.cargo),telefono:text(c.telefono),email:text(c.email)})),acciones:[...Object.values(g.acciones||{}),...legacy].map(a=>({titulo:text(a.titulo),tipo:text(a.tipo),fecha:text(a.fecha),responsable:text(a.responsable),prioridad:text(a.prioridad),estado:text(a.estado),observaciones:text(a.observaciones),contacto:contacts.find(c=>c.id===a.contactoId)?.nombre||'',hora:text(a.hora),duracion:Number(a.duracion)||0,direccion:text(a.direccion),zona:text(a.zona),fechaReal:text(a.fechaReal),resultado:text(a.resultado),cantidadReal:text(a.cantidadReal),control:text(a.control),retrabajo:text(a.retrabajo)})),preparacion:Object.entries(g.preparacion||{}).map(([k,v])=>({paso:k,estado:text(v.estado),detalle:text(v.detalle),url:text(v.url),fecha:text(v.fecha),destinatario:contacts.find(c=>c.id===v.contactoId)?.nombre||''})),notas:Object.values(g.notas||{}).map(n=>({tipo:text(n.tipo),texto:text(n.texto),fecha:text(n.fecha)}))}}
  return {text,norm,iso,shift,week,open,overdue,resolveDraftAction,visit,zone,validate,cleanAction,nearby,planPatch,report};
});

