"use strict";
const admin=require("firebase-admin");
const forge=require("node-forge");
const {onRequest}=require("firebase-functions/v2/https");
const {defineSecret}=require("firebase-functions/params");
const {archivarFacturaPdfEnDrive}=require("./facturaDrive2026");
if(!admin.apps.length)admin.initializeApp();
const cert=defineSecret("ARCA_PROD_CERTIFICATE_PEM"),key=defineSecret("ARCA_PROD_PRIVATE_KEY_PEM"),issuer=defineSecret("ARCA_ISSUER_CUIT"),allowed=defineSecret("ARCA_ALLOWED_EMAILS");
const WSAA="https://wsaa.afip.gov.ar/ws/services/LoginCms",WSFE="https://servicios1.afip.gov.ar/wsfev1/service.asmx",PTO=9;
const ORIGINS=new Set(["https://tiz-publicidad.github.io","https://tiz---app.web.app","https://tiz---app.firebaseapp.com","https://tiz---app--facturacion-v83-pruebas-h6sjmm0g.web.app","http://localhost:5000","http://127.0.0.1:5000"]);
const esc=v=>String(v??"").replace(/[<>&'\"]/g,c=>({"<":"&lt;",">":"&gt;","&":"&amp;","'":"&apos;",'"':"&quot;"})[c]);
const dec=v=>String(v||"").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,"&");
const tag=(xml,n)=>{const m=String(xml||"").match(new RegExp(`<(?:\\w+:)?${n}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/(?:\\w+:)?${n}>`,"i"));return m?dec(m[1].trim()):""};
const num=v=>Number(v)||0,round2=v=>Math.round(num(v)*100)/100;
function cors(req,res){const o=req.get("origin");if(o&&ORIGINS.has(o)){res.set("Access-Control-Allow-Origin",o);res.set("Vary","Origin")}res.set("Access-Control-Allow-Headers","Authorization, Content-Type");res.set("Access-Control-Allow-Methods","POST, OPTIONS")}
async function operator(req){const h=req.get("authorization")||"";if(!h.startsWith("Bearer "))throw Object.assign(new Error("Falta iniciar sesión"),{status:401});const d=await admin.auth().verifyIdToken(h.slice(7)),email=String(d.email||"").toLowerCase(),set=new Set(allowed.value().split(",").map(x=>x.trim().toLowerCase()).filter(Boolean));if(!set.has(email))throw Object.assign(new Error("Usuario sin permiso"),{status:403});return email}
function tra(){const n=new Date(),g=new Date(n-600000).toISOString().replace(/\.\d{3}Z$/,"Z"),e=new Date(n.getTime()+600000).toISOString().replace(/\.\d{3}Z$/,"Z");return `<?xml version="1.0"?><loginTicketRequest version="1.0"><header><uniqueId>${Math.floor(n.getTime()/1000)}</uniqueId><generationTime>${g}</generationTime><expirationTime>${e}</expirationTime></header><service>wsfe</service></loginTicketRequest>`}
function cms(x){const p=forge.pkcs7.createSignedData();p.content=forge.util.createBuffer(x,"utf8");const c=forge.pki.certificateFromPem(cert.value()),k=forge.pki.privateKeyFromPem(key.value());p.addCertificate(c);p.addSigner({key:k,certificate:c,digestAlgorithm:forge.pki.oids.sha256,authenticatedAttributes:[{type:forge.pki.oids.contentType,value:forge.pki.oids.data},{type:forge.pki.oids.messageDigest},{type:forge.pki.oids.signingTime,value:new Date()}]});p.sign();return forge.util.encode64(forge.asn1.toDer(p.toAsn1()).getBytes())}
async function soap(url,action,body){const r=await fetch(url,{method:"POST",headers:{"Content-Type":"text/xml; charset=utf-8",SOAPAction:action},body}),t=await r.text(),f=tag(t,"faultstring");if(f)throw new Error(`ARCA: ${f}`);if(!r.ok)throw new Error(`ARCA respondió HTTP ${r.status}`);return t}
async function credentials(){const e=`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><loginCms xmlns="http://wsaa.view.sua.dvadac.desein.afip.gov"><in0>${cms(tra())}</in0></loginCms></soapenv:Body></soapenv:Envelope>`,x=await soap(WSAA,"",e),r=tag(x,"loginCmsReturn"),token=tag(r,"token"),sign=tag(r,"sign");if(!token||!sign)throw new Error("WSAA no devolvió credenciales válidas");return{token,sign}}
async function call(method,inner,cr){const a=`<Auth><Token>${esc(cr.token)}</Token><Sign>${esc(cr.sign)}</Sign><Cuit>${esc(issuer.value())}</Cuit></Auth>`,e=`<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><${method} xmlns="http://ar.gov.afip.dif.FEV1/">${a}${inner||""}</${method}></soap:Body></soap:Envelope>`;return soap(WSFE,`http://ar.gov.afip.dif.FEV1/${method}`,e)}
function isoDate(v){const s=String(v||"").replace(/\D/g,"");return s.length===8?`${s.slice(0,4)}-${s.slice(4,6)}-${s.slice(6,8)}`:String(v||"")}
function typeName(t){return ({1:"Factura A",6:"Factura B",2:"Nota de Débito A",3:"Nota de Crédito A",7:"Nota de Débito B",8:"Nota de Crédito B",201:"Factura de Crédito Electrónica A",206:"Factura de Crédito Electrónica B",202:"Nota de Débito FCE A",203:"Nota de Crédito FCE A",207:"Nota de Débito FCE B",208:"Nota de Crédito FCE B"})[Number(t)]||`Comprobante ${t}`}
function family(t){t=Number(t);if([3,8,203,208].includes(t))return"credito";if([2,7,202,207].includes(t))return"debito";return"factura"}
function list(o){const a=Array.isArray(o?.comprobantesArca)?[...o.comprobantesArca]:Array.isArray(o?.facturasArca)?[...o.facturasArca]:[];if(o?.facturaArca?.cae&&!a.some(x=>x?.cae===o.facturaArca.cae))a.push(o.facturaArca);return a.filter(Boolean)}
function sameComp(c,t,n){return Number(c?.ptoVta)===PTO&&Number(c?.cbteTipo)===Number(t)&&Number(c?.cbteNro)===Number(n)}
function cuitOf(x){return String(x?.clienteCuit||x?.cuit||x?.facturaArca?.cuit||"").replace(/\D/g,"")}
function scaledItems(o,net){const src=(Array.isArray(o?.itemsCotizados)?o.itemsCotizados:[]).map(x=>({descripcion:String(x.descripcion||x.desc||"").trim(),cantidad:num(x.cantidad||x.cant||x.unidades||1)||1,unitario:num(x.unitario??x.precio??x.precioUnitario)})).filter(x=>x.descripcion&&x.unitario>=0),base=src.reduce((s,x)=>s+x.cantidad*x.unitario,0),ratio=base?net/base:1;return src.length?src.map(x=>({...x,unitario:round2(x.unitario*ratio)})):[{descripcion:"Comprobante recuperado de ARCA",cantidad:1,unitario:net}]}
async function findContext(db,t,n,cuit,net){const os=await db.collection("obras").limit(1500).get(),obras=os.docs.map(d=>({id:d.id,...d.data()}));let obra=obras.find(o=>list(o).some(c=>sameComp(c,t,n))||sameComp(o.facturaArca,t,n));if(!obra){const candidates=obras.filter(o=>cuitOf(o)===cuit);obra=candidates.find(o=>{const total=num(o?.finanzas?.total||o?.neto||o?.importe||o?.infoPresupuesto?.importe);return Math.abs(total-net)<0.02})||candidates[0]||null}
 let cliente="";if(obra)cliente=String(obra.cliente||"").trim();if(!cliente){const cs=await db.collection("clientes").limit(2000).get();const c=cs.docs.map(d=>d.data()).find(x=>String(x?.cuit||x?.CUIT||"").replace(/\D/g,"")===cuit);cliente=String(c?.razonSocial||c?.razon_social||c?.nombreFiscal||c?.nombre||"").trim()}
 return {obra,cliente:cliente||`CUIT ${cuit}`}}
async function consultar(t,n,cr){const x=await call("FECompConsultar",`<FeCompConsReq><CbteTipo>${Number(t)}</CbteTipo><PtoVta>${PTO}</PtoVta><CbteNro>${Number(n)}</CbteNro></FeCompConsReq>`,cr),errors=[...x.matchAll(/<(?:Msg|Obs)>([\s\S]*?)<\/(?:Msg|Obs)>/gi)].map(m=>dec(m[1].trim())).filter(Boolean),result=tag(x,"Resultado");if(errors.length&&result!=="A")throw Object.assign(new Error(errors.join(" · ")),{status:404});const cae=tag(x,"CodAutorizacion")||tag(x,"CAE");if(!cae)throw Object.assign(new Error(`ARCA no devolvió autorización para ${String(PTO).padStart(5,"0")}-${String(n).padStart(8,"0")}`),{status:404});return{cbteTipo:Number(t),cbteNro:Number(n),ptoVta:PTO,cuit:String(tag(x,"DocNro")||"").replace(/\D/g,""),fecha:isoDate(tag(x,"CbteFch")),neto:round2(tag(x,"ImpNeto")||tag(x,"ImpOpEx")),iva:round2(tag(x,"ImpIVA")),total:round2(tag(x,"ImpTotal")),cae:String(cae),caeVto:isoDate(tag(x,"FchVto")||tag(x,"CAEFchVto")),resultado:result||"A"}}
const facturacionRecuperarHistoricosV86=onRequest({region:"us-central1",invoker:"public",secrets:[cert,key,issuer,allowed],timeoutSeconds:120},async(req,res)=>{cors(req,res);if(req.method==="OPTIONS")return res.status(204).send("");if(req.method!=="POST")return res.status(405).json({ok:false,error:"Método no permitido"});try{const email=await operator(req),tipo=Number(req.body?.cbteTipo||1),nums=(Array.isArray(req.body?.numeros)?req.body.numeros:[req.body?.cbteNro]).map(Number).filter(n=>Number.isInteger(n)&&n>0).slice(0,10);if(!nums.length)throw Object.assign(new Error("Indicá al menos un número de comprobante"),{status:400});const db=admin.firestore(),cr=await credentials(),out=[];for(const n of nums){try{const raw=await consultar(tipo,n,cr),ctx=await findContext(db,tipo,n,raw.cuit,raw.neto),obra=ctx.obra||{ot:"",cliente:ctx.cliente,desc:"Recuperado de ARCA"},factura={ambiente:"produccion",tipo:typeName(tipo),familia:family(tipo),letra:[1,2,3,201,202,203].includes(tipo)?"A":"B",ptoVta:PTO,cbteTipo:tipo,cbteNro:n,numeroCompleto:`${String(PTO).padStart(5,"0")}-${String(n).padStart(8,"0")}`,fecha:raw.fecha,cae:raw.cae,caeVto:raw.caeVto,cliente:ctx.cliente,cuit:raw.cuit,neto:raw.neto,iva:raw.iva,total:raw.total,items:scaledItems(obra,raw.neto),recuperadaDeArca:true};const drive=await archivarFacturaPdfEnDrive({factura,obra,issuerCuit:issuer.value()});const rec={...factura,...drive,recuperadaPor:email,recuperadaAt:new Date().toISOString(),obraId:ctx.obra?.id||""};await db.collection("arcaRecuperados").doc(`pv9-t${tipo}-n${n}`).set(rec,{merge:true});if(ctx.obra?.id){const ref=db.collection("obras").doc(ctx.obra.id),snap=await ref.get(),o=snap.data()||{},arr=list(o),idx=arr.findIndex(c=>sameComp(c,tipo,n));if(idx>=0)arr[idx]={...arr[idx],...factura,driveFileId:drive.fileId,driveFileName:drive.fileName,driveWebViewLink:drive.webViewLink,drivePendiente:false};else arr.push({...factura,driveFileId:drive.fileId,driveFileName:drive.fileName,driveWebViewLink:drive.webViewLink,drivePendiente:false});const isCurrent=sameComp(o.facturaArca,tipo,n)||Number(o.facturaArca?.cbteNro)===n;const patch={comprobantesArca:arr,facturasArca:arr,ultimoPdfFacturaId:drive.fileId,ultimoPdfFacturaUrl:drive.webViewLink};if(isCurrent)patch.facturaArca={...(o.facturaArca||{}),...factura,driveFileId:drive.fileId,driveFileName:drive.fileName,driveWebViewLink:drive.webViewLink,drivePendiente:false},patch.facturaDrivePendiente=false;await ref.set(patch,{merge:true})}out.push({ok:true,numero:factura.numeroCompleto,cliente:factura.cliente,cuit:factura.cuit,total:factura.total,cae:factura.cae,obraId:ctx.obra?.id||"",ot:ctx.obra?.ot||"",...drive})}catch(e){out.push({ok:false,cbteNro:n,error:e.message||String(e)})}}
return res.json({ok:out.every(x=>x.ok),resultados:out})}catch(e){return res.status(e.status||502).json({ok:false,error:e.message||"No se pudieron recuperar los comprobantes"})}});
module.exports={facturacionRecuperarHistoricosV86};
