"use strict";
const admin=require("firebase-admin");
const {onRequest}=require("firebase-functions/v2/https");
const {defineSecret}=require("firebase-functions/params");
const {archivarFacturaPdfEnDrive}=require("./facturaDrive2026");
if(!admin.apps.length)admin.initializeApp();
const issuer=defineSecret("ARCA_ISSUER_CUIT"),allowed=defineSecret("ARCA_ALLOWED_EMAILS");
const ORIGINS=new Set(["https://tiz-publicidad.github.io","http://localhost:5000","http://127.0.0.1:5000"]);
function cors(req,res){const o=req.get("origin");if(o&&ORIGINS.has(o)){res.set("Access-Control-Allow-Origin",o);res.set("Vary","Origin")}res.set("Access-Control-Allow-Headers","Authorization, Content-Type");res.set("Access-Control-Allow-Methods","POST, OPTIONS")}
async function operator(req){const h=req.get("authorization")||"";if(!h.startsWith("Bearer "))throw Object.assign(new Error("Falta iniciar sesión"),{status:401});const d=await admin.auth().verifyIdToken(h.slice(7)),email=String(d.email||"").toLowerCase(),set=new Set(allowed.value().split(",").map(x=>x.trim().toLowerCase()).filter(Boolean));if(!set.has(email))throw Object.assign(new Error("Usuario sin permiso"),{status:403});return email}
const facturacionReintentarDriveV83=onRequest({region:"us-central1",invoker:"public",secrets:[issuer,allowed],timeoutSeconds:60},async(req,res)=>{cors(req,res);if(req.method==="OPTIONS")return res.status(204).send("");if(req.method!=="POST")return res.status(405).json({ok:false,error:"Método no permitido"});try{const email=await operator(req),obraId=String(req.body?.obraId||"").trim();if(!obraId)throw Object.assign(new Error("Falta identificar la OT"),{status:400});const ref=admin.firestore().collection("obras").doc(obraId),snap=await ref.get();if(!snap.exists)throw Object.assign(new Error("No se encontró la OT"),{status:404});const obra=snap.data()||{},factura=obra.facturaArca||{};if(!factura.cae)throw Object.assign(new Error("La OT no tiene un comprobante ARCA autorizado"),{status:400});if(factura.driveFileId)return res.json({ok:true,repetida:true,fileId:factura.driveFileId,webViewLink:factura.driveWebViewLink||""});const drive=await archivarFacturaPdfEnDrive({factura,obra,issuerCuit:issuer.value()});await ref.update({"facturaArca.driveFileId":drive.fileId,"facturaArca.driveFileName":drive.fileName,"facturaArca.driveWebViewLink":drive.webViewLink,"facturaArca.drivePendiente":false,facturaDrivePendiente:false,ultimoPdfFacturaId:drive.fileId,ultimoPdfFacturaUrl:drive.webViewLink,facturaDriveReintentadaAt:new Date().toISOString(),facturaDriveReintentadaPor:email});return res.json({ok:true,...drive})}catch(e){return res.status(e.status||502).json({ok:false,error:e.message||"No se pudo archivar el PDF"})}});
module.exports={facturacionReintentarDriveV83};
