// TIZ V98 - una sola vista Por cobrar, sin Gestiones separada ni mutadores posteriores.
(function(){
'use strict';
const MONEY=new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0});
const estados=['Pendiente de facturar','Facturada - falta enviar','Factura enviada','Esperando fecha de pago','Cobro programado','Vencida - reclamar','Pago parcial','Cobrado','En revisión'];
const num=v=>Number(v)||0;
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const base=v=>String(v??'').match(/\d{4,7}/)?.[0].replace(/^0+/,'')||'';
const date=v=>{if(!v)return '—';const s=String(v);const m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[3]}/${m[2]}/${m[1]}`:s};
function total(o){return num(o?.finanzas?.total||o?.infoPresupuesto?.importe||o?.sectores?.cobranzas?.montoTotal||o?.sectores?.facturacion?.importePresupuestado||o?.neto||o?.importe)}
function comps(o){const a=Array.isArray(o?.comprobantesArca)?[...o.comprobantesArca]:Array.isArray(o?.facturasArca)?[...o.facturasArca]:[];if(o?.facturaArca?.cae&&!a.some(x=>String(x?.cae)===String(o.facturaArca.cae)))a.push(o.facturaArca);return a.filter(x=>x?.cae)}
function latest(o){return [...comps(o)].sort((a,b)=>num(b?.cbteNro)-num(a?.cbteNro))[0]||o?.facturaArca||null}
function hasInvoice(o){const f=o?.finanzas||{};return !!(o?.facturaArca?.cae||o?.nrfc||f?.anticipo?.facturado||f?.saldo?.facturado||f?.anticipo?.nroFactura||f?.saldo?.nroFactura||comps(o).length)}
function emitted(o){const t=total(o),cs=comps(o);if(cs.length){const v=cs.reduce((s,c)=>s+num(c?.neto),0);if(v>0)return Math.min(t||v,v)}const f=o?.finanzas||{};let v=0;if(f?.anticipo?.facturado||f?.anticipo?.nroFactura)v+=num(f.anticipo.monto);if(f?.saldo?.facturado||f?.saldo?.nroFactura)v+=num(f.saldo.monto);if(v>0)return Math.min(t||v,v);if(o?.nrfc)return t;return 0}
function retenciones(o){return Object.values(o?.finanzas?.retenciones||{}).reduce((a,v)=>a+num(v),0)}
function cobrado(o){const f=o?.finanzas||{};return num(f?.anticipo?.montoCobrado)+num(f?.saldo?.montoCobrado)}
function saldoCobro(o){return Math.max(0,total(o)-cobrado(o)-retenciones(o))}
function saldoFacturar(o){return Math.max(0,total(o)-emitted(o))}
function sent(o){const c=latest(o);return !!(c?.emailUltimoEnvioAt||o?.facturaArca?.emailUltimoEnvioAt)}
function drive(o){const c=latest(o);if(!c?.cae)return {ok:false,href:''};const known=Number(c.cbteNro||0)===1?{fileId:'1OW0DBW9pH-QslFHdVJ--LHE2_q81s2jn',webViewLink:'https://drive.google.com/file/d/1OW0DBW9pH-QslFHdVJ--LHE2_q81s2jn/view'}:null;const fileId=c.driveFileId||c.fileId||known?.fileId||'';const href=c.driveWebViewLink||c.webViewLink||known?.webViewLink||(fileId?`https://drive.google.com/file/d/${fileId}/view`:'');return {ok:!!(fileId||href),href}}
function eligible(o){return !!(o?.id&&total(o)>0&&(hasInvoice(o)||norm(o?.estado).startsWith('aprob')||norm(o?.infoPresupuesto?.estado).startsWith('aprob')||o?.origen==='presupuesto'||o?.presupuestoId||o?.infoPresupuesto?.nro))}
function status(o){if(o?.estadoGestionFactura)return o.estadoGestionFactura;if(norm(o?.estado)==='cobrado'||saldoCobro(o)<=.01)return 'Cobrado';if(cobrado(o)>0)return 'Pago parcial';if(sent(o))return 'Factura enviada';if(hasInvoice(o))return 'Facturada - falta enviar';return 'Pendiente de facturar'}
function selectEstado(o){const cur=status(o);return `<select class="quick-estado tiz-v98-estado" data-id="${esc(o.id)}" style="width:190px;min-width:190px;max-width:190px;box-sizing:border-box">${estados.map(s=>`<option value="${s}" ${s===cur?'selected':''}>${s}</option>`).join('')}</select>`}
function facturacion(o){const t=total(o),e=emitted(o),sf=Math.max(0,t-e);if(!hasInvoice(o))return '<span style="color:var(--text3)">Sin facturar</span>';const c=latest(o),n=c?.numeroCompleto||o?.nrfc||o?.finanzas?.saldo?.nroFactura||o?.finanzas?.anticipo?.nroFactura||'';if(sf<=.01)return `<b style="color:var(--green)">Facturado 100%</b><br><span style="color:var(--text3)">${esc(n?`FC ${n}`:'Comprobante emitido')}</span>`;const pct=t?Math.max(0,Math.min(100,e/t*100)):0;return `<b style="color:var(--amber)">Anticipo facturado ${pct.toFixed(pct%1?1:0)}%</b><br><span style="color:var(--text3)">${MONEY.format(e)} facturados · ${MONEY.format(sf)} por facturar</span>${n?`<br><span style="color:var(--text3)">FC ${esc(n)}</span>`:''}`}
function pdf(o){if(!hasInvoice(o))return '<span style="color:var(--text3)">—</span>';const c=latest(o);if(!c?.cae)return '<span class="badge badge-gray">Factura histórica</span>';const d=drive(o);if(d.ok)return d.href?`<a href="${esc(d.href)}" target="_blank" rel="noopener" class="badge badge-green" style="text-decoration:none">En Drive</a>`:'<span class="badge badge-green">En Drive</span>';return `<div style="display:flex;gap:6px;align-items:center;flex-wrap:wrap"><span class="badge badge-amber">PDF pendiente</span><button type="button" class="btn btn-ghost btn-sm tiz-v98-archive" data-n="${num(c.cbteNro)}">Archivar PDF</button></div>`}
function indicator(o){if(!hasInvoice(o))return '';const d=drive(o),s=sent(o);const color=d.ok&&s?'#22a06b':'#e8b84b';const title=d.ok&&s?'PDF en Drive y factura enviada':d.ok?'PDF en Drive · falta enviar':'Factura emitida · PDF pendiente de archivar';return `<span title="${title}" style="width:11px;height:11px;border-radius:50%;display:inline-block;flex:0 0 11px;background:${color}"></span>`}
function actions(o){const inv=hasInvoice(o),sf=saldoFacturar(o),c=latest(o);const fact=!inv?`<button class="btn btn-primary btn-sm" onclick="abrirFacturacionGeneralV63('${o.id}')"><i class="ti ti-receipt"></i> Facturar</button>`:(sf>.01?`<button class="btn btn-primary btn-sm" onclick="abrirFacturacionGeneralV63('${o.id}')">Facturar saldo</button>`:'');const mail=c?.cae?`<button class="btn btn-ghost btn-sm" onclick="abrirEnvioFacturaEmailV61('${o.id}')">${sent(o)?'Reenviar FC':'Enviar FC'}</button>`:'';return `<div style="display:flex;gap:8px;align-items:center;justify-content:flex-end;white-space:nowrap">${indicator(o)}<button class="btn btn-ghost btn-sm" onclick="editarCobranzaObraV41('${o.id}')">Gestionar</button>${fact}${mail}</div>`}
async function saveEstado(o,sel){const prev=o.estadoGestionFactura||'';const v=sel.value;o.estadoGestionFactura=v;sel.disabled=true;try{const patch={estadoGestionFactura:v,estadoGestionFacturaActualizadoAt:new Date().toISOString()};if(v==='Cobrado')patch.estado='Cobrado';await window.updateDoc_('obras',o.id,patch);Object.assign(o,patch);window.showToast?.('Estado actualizado');render()}catch(e){console.error(e);o.estadoGestionFactura=prev;sel.value=prev||status(o);alert('No se pudo guardar el estado.')}finally{sel.disabled=false}}
function render(){
 if(window.cobTab!=='cobrar'&&window.cobTab!=='gestiones')return;
 window.cobTab='cobrar';hideGestiones();
 const mod=document.getElementById('cobr-modulo-v48');if(!mod)return;
 const rows=(window.DB?.obras||[]).filter(eligible).filter(o=>status(o)!=='Cobrado'&&saldoCobro(o)>.01).sort((a,b)=>num(base(b.ot))-num(base(a.ot))).map(o=>`<tr data-v98="${esc(o.id)}"><td class="strong">${esc(base(o.ot))}</td><td><b>${esc(o.cliente||'')}</b><br><span style="color:var(--text3)">${esc(o.desc||o.descripcion||'')}</span></td><td>${facturacion(o)}</td><td>${MONEY.format(saldoCobro(o))}</td><td>${esc(date(o?.finanzas?.saldo?.fechaPrevistaCobro||o?.finanzas?.anticipo?.fechaPrevistaCobro||''))}</td><td>${selectEstado(o)}</td><td>${pdf(o)}</td><td>${actions(o)}</td></tr>`).join('');
 mod.innerHTML=`<div class="card"><div class="card-header"><span class="card-title">Por cobrar · facturación y gestión</span><span style="font-size:10px;color:var(--text3)"><span style="color:#22a06b">●</span> En Drive + enviada &nbsp; <span style="color:#e8b84b">●</span> Falta enviar / revisar PDF</span></div><div class="table-wrap"><table><thead><tr><th>OT</th><th>Cliente / obra</th><th>Facturación</th><th>Saldo a cobrar</th><th>Cobro previsto</th><th>Estado</th><th>PDF</th><th>Acción</th></tr></thead><tbody>${rows||'<tr><td colspan="8" style="text-align:center;padding:30px;color:var(--text3)">No hay saldos pendientes.</td></tr>'}</tbody></table></div></div>`;
 mod.querySelectorAll('.tiz-v98-estado').forEach(sel=>{const o=(window.DB?.obras||[]).find(x=>x.id===sel.dataset.id);if(o)sel.onchange=()=>saveEstado(o,sel)});
 mod.querySelectorAll('.tiz-v98-archive').forEach(btn=>btn.onclick=async()=>{const ok=await window.recuperarPdfFacturaV86?.(Number(btn.dataset.n||0),btn);if(ok)render()});
}
function hideGestiones(){document.querySelectorAll('#page-cobranzas .page-tabs .page-tab').forEach(b=>{if(/gestiones/i.test(b.textContent||''))b.style.display='none';if(/por cobrar/i.test(b.textContent||'')){b.style.display='';if(window.cobTab==='cobrar')b.classList.add('active')}})}
const priorSet=window.setCobTab;
window.setCobTab=function(tab,button){if(tab==='gestiones')tab='cobrar';if(tab==='cobrar'){window.cobTab='cobrar';document.querySelectorAll('#page-cobranzas .page-tab').forEach(x=>x.classList.remove('active'));const p=[...document.querySelectorAll('#page-cobranzas .page-tab')].find(x=>/por cobrar/i.test(x.textContent||''));(p||button)?.classList.add('active');hideGestiones();render();return}const r=priorSet?.apply(this,[tab,button]);hideGestiones();return r};
window.renderCobranzas=render;
hideGestiones();
if(window.cobTab==='gestiones')window.cobTab='cobrar';
if(window.cobTab==='cobrar')render();
window.addEventListener('load',()=>{hideGestiones();if(window.cobTab==='cobrar'||window.cobTab==='gestiones'){window.cobTab='cobrar';render()}},{once:true});
})();
