// TIZ V106.2 - Fuente unica canonica. Compatibilidad workflow: TIZ V106.1
(function(){'use strict';
const n=v=>Number(v)||0,N=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim(),B=v=>{const m=String(v??'').match(/\d{4,7}/);return m?String(Number(m[0])):''},A=v=>N(v).startsWith('aprob'),M=new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}),E=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');let busy=false;
function badge(){document.getElementById('tiz-build-v20')?.style.setProperty('display','none');let x=document.getElementById('tiz-runtime-v106');if(!x){x=document.createElement('div');x.id='tiz-runtime-v106';x.style.cssText='position:fixed;right:10px;bottom:8px;z-index:99999;background:#1a1a1a;border:1px solid rgba(232,184,75,.45);color:#e8b84b;border-radius:6px;padding:4px 8px;font:10px DM Mono,monospace;pointer-events:none';document.body.appendChild(x)}x.textContent='TIZ V106.2 · FACTURACION/COBRANZAS · 16/09/2026'}
function totalP(p){return n(p?.importe||p?.neto||p?.total||p?.totalItems)||(Array.isArray(p?.items)?p.items.reduce((a,i)=>a+n(i?.subtotal||n(i?.precio)*n(i?.cant||i?.cantidad||1)),0):0)}
function aprobadas(){const m=new Map();for(const p of(window.DB?.presupuestos||[])){if(!A(p?.estado||p?.status||p?.estadoRevision))continue;const k=B(p?.nro||p?.cotizacionBase);if(!k)continue;const q=m.get(k);if(!q||String(p?.revision||'').localeCompare(String(q?.revision||''),undefined,{numeric:true})>=0)m.set(k,p)}return[...m.values()]}
function obra(p){const os=window.DB?.obras||[],k=B(p?.nro||p?.cotizacionBase);return(p?.obraId&&os.find(o=>o.id===p.obraId))||os.find(o=>o.presupuestoId===p?.id||o.cotizacionId===p?.id)||os.find(o=>B(o?.ot)===k&&k)||null}
function local(p,id){const t=totalP(p),k=B(p?.nro||p?.cotizacionBase),part={facturado:false,nroFactura:'',monto:0,montoCobrado:0};return{id,ot:k,cliente:p?.cliente||'',desc:p?.desc||p?.descripcion||'',estado:'Aprobado',neto:t,importe:t,origen:'presupuesto',presupuestoId:p?.id||'',cotizacionId:p?.id||'',infoPresupuesto:{nro:p?.nro||k,presupuestoId:p?.id||'',importe:t,estado:'Aprobado'},finanzas:{total:t,anticipo:{...part},saldo:{...part}}}}
async function syncAprobadas(){if(busy)return 0;busy=true;let c=0;try{if(!Array.isArray(window.DB?.obras)||!Array.isArray(window.DB?.presupuestos))return 0;for(const p of aprobadas()){let o=obra(p);if(!o){try{let id='';if(typeof window.ensureObraFromPresupuestoV358==='function')id=await window.ensureObraFromPresupuestoV358(p.id,p)||'';else if(typeof window.addDoc_==='function')id=(await window.addDoc_('obras',local(p,'')))?.id||'';if(id){o=local(p,id);p.obraId=id;if(!window.DB.obras.some(x=>x.id===id||B(x.ot)===B(p.nro)))window.DB.obras.push(o);c++}}catch(e){console.error('[V106.2] aprobada',B(p.nro),e)}}if(!o)continue;const t=totalP(p)||n(o.neto||o.importe||o.finanzas?.total),patch={presupuestoId:p.id||o.presupuestoId||'',cotizacionId:p.id||o.cotizacionId||'',neto:t,importe:t,finanzas:{...(o.finanzas||{}),total:t},infoPresupuesto:{...(o.infoPresupuesto||{}),nro:p.nro||B(o.ot),presupuestoId:p.id||'',importe:t,estado:'Aprobado'}};Object.assign(o,patch);if(o.id&&typeof window.updateDoc_==='function')try{await window.updateDoc_('obras',o.id,patch)}catch(e){console.error('[V106.2] OT',B(o.ot),e)}if(p.id&&p.obraId!==o.id&&typeof window.updateDoc_==='function')try{await window.updateDoc_('presupuestos',p.id,{obraId:o.id,promovidoAObra:true});p.obraId=o.id}catch(_){}}}finally{busy=false}return c}
function invs(o){const f=o?.finanzas||{},s=o?.sectores?.facturacion||o?.gestionSectores?.facturacion||{},a=[];if(o?.facturaArca)a.push(o.facturaArca);if(Array.isArray(o?.comprobantesArca))a.push(...o.comprobantesArca);if(Array.isArray(o?.facturasArca))a.push(...o.facturasArca);a.push({numeroCompleto:o?.nrfc,fecha:o?.ffc},{numeroCompleto:s?.nroFactura,fecha:s?.fechaFactura},{numeroCompleto:f?.anticipo?.nroFactura,neto:f?.anticipo?.monto},{numeroCompleto:f?.saldo?.nroFactura,neto:f?.saldo?.monto});return a.filter(Boolean)}
function invN(o){for(const x of invs(o)){const z=String(x?.numeroCompleto||x?.nroFactura||x?.numero||'').trim();if(z)return z}return''}function invA(o){for(const x of invs(o)){const z=n(x?.neto||x?.importeNeto||x?.monto||x?.importe||x?.total||x?.importeTotal||x?.totalComprobante);if(z>0)return z}return 0}
function normInv(){for(const o of(window.DB?.obras||[])){const z=invN(o);if(!z)continue;if(!o.nrfc)o.nrfc=z;const p=aprobadas().find(x=>B(x.nro)===B(o.ot)),raw=o.finanzas||{},t=n(raw.total||o.neto||o.importe||o.infoPresupuesto?.importe||totalP(p)||invA(o));if(t>0)o.finanzas={...raw,total:t}}}
const H={'4680':['00009-00000001','2026-09-04',329200,'Factura enviada'],'4701':['00009-00000002','2026-09-07',1477118,'Facturada - falta enviar']};async function hist(){for(const o of(window.DB?.obras||[])){const h=H[B(o.ot)];if(!h||invN(o)||!o.id)continue;const raw=o.finanzas||{},t=n(raw.total||o.neto||o.importe||h[2]),patch={nrfc:h[0],ffc:h[1],estadoGestionFactura:o.estadoGestionFactura||h[3],finanzas:{...raw,total:t,saldo:{...(raw.saldo||{}),facturado:true,nroFactura:h[0],fechaFactura:h[1],monto:n(raw?.saldo?.monto)||h[2]||t}}};try{await window.updateDoc_('obras',o.id,patch);Object.assign(o,patch)}catch(e){console.error('[V106.2] histórica',h[0],e)}}}
function emitted(o){const t=n(o?.finanzas?.total||o?.neto||o?.importe),f=o?.finanzas||{};let v=0;if(f?.anticipo?.facturado||f?.anticipo?.nroFactura)v+=n(f?.anticipo?.monto);if(f?.saldo?.facturado||f?.saldo?.nroFactura)v+=n(f?.saldo?.monto);if(v)return Math.min(t||v,v);const a=invA(o);if(a)return Math.min(t||a,a);return invN(o)?t:0}
function paraFacturar(){if(window.cobTab!=='facturar')return;const el=document.getElementById('cobr-modulo-v48');if(!el)return;const rs=aprobadas().map(p=>{const o=obra(p),t=totalP(p)||n(o?.finanzas?.total||o?.neto||o?.importe),e=o?emitted(o):0;return{p,o,t,e,s:Math.max(0,t-e)}}).filter(x=>x.t>0&&x.s>.01).sort((a,b)=>n(B(b.p.nro))-n(B(a.p.nro)));el.innerHTML=`<div class="card"><div class="card-header"><span class="card-title">Cola de facturación</span><span style="font-size:10px;color:var(--text3)">${rs.length} aprobadas pendientes</span></div><div class="table-wrap"><table><thead><tr><th>OT</th><th>Cliente / obra</th><th>Facturación actual</th><th>Saldo</th><th>Estado</th><th>Acción</th></tr></thead><tbody>${rs.map(x=>{const id=x.o?.id||'',nr=invN(x.o||{}),ac=id?`<div style="display:flex;gap:8px;justify-content:flex-end"><button class="btn btn-ghost btn-sm" onclick="editarCobranzaObraV41('${E(id)}')">Gestionar</button><button class="btn btn-primary btn-sm" onclick="abrirFacturacionGeneralV63('${E(id)}')">${x.e?'Facturar saldo':'Facturar'}</button></div>`:'<span style="color:var(--amber)">Sincronizando…</span>';return`<tr><td class="strong">${E(B(x.p.nro))}</td><td><b>${E(x.p.cliente||x.o?.cliente||'')}</b><br><span style="color:var(--text3)">${E(x.p.desc||x.p.descripcion||x.o?.desc||'')}</span></td><td>${x.e?`${nr?`FC ${E(nr)} · `:''}${M.format(x.e)}`:'<span style="color:var(--text3)">Sin facturar</span>'}</td><td>${M.format(x.s)}</td><td><span class="badge badge-${id?'amber':'gray'}">${id?'Lista para facturar':'Sincronizando obra'}</span></td><td>${ac}</td></tr>`}).join('')||'<tr><td colspan="6" style="text-align:center;padding:30px;color:var(--text3)">No hay aprobadas pendientes.</td></tr>'}</tbody></table></div></div>`}
async function run(){badge();normInv();const a=await syncAprobadas();await hist();normInv();window.tizReconciliarCobranzasV105?.();if(window.cobTab==='facturar')setTimeout(paraFacturar,0);if(a)setTimeout(()=>{window.renderCobranzas?.();paraFacturar()},180)}
function hooks(){const r=window.renderCobranzas;if(typeof r==='function'&&!r.__v1062){const w=function(){normInv();const out=r.apply(this,arguments);if(window.cobTab==='facturar')queueMicrotask(paraFacturar);run().catch(console.error);return out};w.__v1062=true;window.renderCobranzas=w}const s=window.setCobTab;if(typeof s==='function'&&!s.__v1062){const w=function(){const out=s.apply(this,arguments);normInv();if(window.cobTab==='facturar')queueMicrotask(paraFacturar);run().then(()=>setTimeout(paraFacturar,100));return out};w.__v1062=true;window.setCobTab=w}}
async function init(){badge();hooks();await run();[700,1800,4500,9000,18000].forEach(ms=>setTimeout(()=>{hooks();run().catch(console.error)},ms))}window.tizReconciliarFuenteUnicaV106=run;window.tizRenderParaFacturarCanonicoV106=paraFacturar;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();})();
