// TIZ V86 — Drive obligatorio, recuperacion fiscal historica y estado PDF visible
(function(){
'use strict';
const ENDPOINT='https://us-central1-tiz---app.cloudfunctions.net/facturacionReintentarDriveV83';
const RECOVER_ENDPOINT='https://us-central1-tiz---app.cloudfunctions.net/facturacionRecuperarHistoricosV86';
const AUTO_KEY='tiz-drive-retry-v86';
const RECOVER_KEY='tiz-arca-recover-v86-2-3';
const base=v=>String(v??'').match(/\d{4,7}/)?.[0].replace(/^0+/,'')||'';
async function token(){const [{getApp},{getAuth}]=await Promise.all([import('https://www.gstatic.com/firebasejs/10.12.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/10.12.0/firebase-auth.js')]);const u=getAuth(getApp()).currentUser;if(!u)throw new Error('Sesión no iniciada');return u.getIdToken()}
function comps(o){const a=Array.isArray(o?.comprobantesArca)?[...o.comprobantesArca]:Array.isArray(o?.facturasArca)?[...o.facturasArca]:[];if(o?.facturaArca?.cae&&!a.some(x=>String(x?.cae)===String(o.facturaArca.cae)))a.push(o.facturaArca);return a.filter(x=>x?.cae)}
function latest(o){return [...comps(o)].sort((a,b)=>Number(b?.cbteNro||0)-Number(a?.cbteNro||0))[0]||o?.facturaArca||null}
function hasDrive(c){return !!(c?.driveFileId||c?.fileId||c?.driveWebViewLink)}
async function callRetry(id){const r=await fetch(ENDPOINT,{method:'POST',headers:{Authorization:'Bearer '+await token(),'Content-Type':'application/json'},body:JSON.stringify({obraId:id})}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok){const err=new Error(d.error||'No se pudo archivar el PDF');err.meta=d;throw err}return d}
async function callRecover(nums){const r=await fetch(RECOVER_ENDPOINT,{method:'POST',headers:{Authorization:'Bearer '+await token(),'Content-Type':'application/json'},body:JSON.stringify({cbteTipo:1,numeros:nums.map(Number)})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'No se pudo consultar ARCA');return d}
function applySuccess(o,d){o.facturaArca=o.facturaArca||{};o.facturaArca.driveFileId=d.fileId;o.facturaArca.driveWebViewLink=d.webViewLink;o.facturaArca.drivePendiente=false;o.facturaDrivePendiente=false;window.showToast?.('PDF archivado en 2026 Facturacion ✓')}
function errorText(e){const m=e?.meta||{},actor=m.serviceAccountEmail?`\n\nCuenta que necesita acceso Editor a 2026 Facturacion:\n${m.serviceAccountEmail}`:'',folder=m.folderId?`\nCarpeta: ${m.folderId}`:'';return 'No se pudo archivar el PDF.\n\n'+(e.message||e)+actor+folder}
window.reintentarPdfFacturaV83=async function(id,btn,opts={}){const o=(window.DB?.obras||[]).find(x=>x.id===id);if(!o)return false;if(!o.facturaArca?.cae){if(!opts.silent)alert('La OT no tiene un comprobante ARCA autorizado.');return false}const old=btn?.textContent;if(btn){btn.disabled=true;btn.textContent='Archivando…'}try{const d=await callRetry(id);applySuccess(o,d);if(!opts.silent)setTimeout(()=>window.renderCobranzas?.(),80);return true}catch(e){console.error('[TIZ Drive retry]',e);if(!opts.silent)alert(errorText(e));else{o.__driveRetryError=errorText(e);window.showToast?.('PDF pendiente en Drive')}return false}finally{if(btn){btn.disabled=false;btn.textContent=old}}};
window.recuperarPdfFacturaV86=async function(n,btn,opts={}){n=Number(n);if(!n)return false;const old=btn?.textContent;if(btn){btn.disabled=true;btn.textContent='Archivando…'}try{const d=await callRecover([n]),row=d.resultados?.[0];if(!row?.ok)throw new Error(row?.error||'No se pudo recuperar el comprobante');window.showToast?.(`FC ${row.numero}: PDF archivado en 2026 Facturacion ✓`);setTimeout(()=>window.renderCobranzas?.(),300);return true}catch(e){console.error('[TIZ V86 recover]',e);if(!opts.silent)alert('La factura ya existe en ARCA, pero no se pudo archivar su PDF.\n\n'+(e.message||e));return false}finally{if(btn){btn.disabled=false;btn.textContent=old}}};
async function autoRetry(){for(const o of (window.DB?.obras||[])){const c=latest(o);if(!o?.id||!c?.cae||hasDrive(c)||(!o.facturaDrivePendiente&&!c.drivePendiente))continue;const key=`${AUTO_KEY}:${o.id}:${c.cae}`;if(sessionStorage.getItem(key))continue;sessionStorage.setItem(key,'1');if(Number(c.cbteTipo||1)===1&&Number(c.cbteNro)>0)await window.recuperarPdfFacturaV86(c.cbteNro,null,{silent:true});else await window.reintentarPdfFacturaV83(o.id,null,{silent:true})}}
async function recoverMissing(){const obras=window.DB?.obras||[],need=[2,3].filter(n=>{const o=obras.find(x=>comps(x).some(c=>Number(c.cbteTipo||1)===1&&Number(c.cbteNro)===n));const c=o&&comps(o).find(c=>Number(c.cbteTipo||1)===1&&Number(c.cbteNro)===n);return !c||!hasDrive(c)});if(!need.length){sessionStorage.setItem(RECOVER_KEY,'done');return}const key=RECOVER_KEY+':'+need.join('-');if(sessionStorage.getItem(key))return;sessionStorage.setItem(key,'1');try{const d=await callRecover(need),ok=(d.resultados||[]).filter(x=>x.ok),bad=(d.resultados||[]).filter(x=>!x.ok);if(ok.length)window.showToast?.(`PDF recuperado${ok.length>1?'s':''}: ${ok.map(x=>x.numero).join(', ')} ✓`);if(bad.length){console.error('[TIZ V86 recovery incomplete]',bad);window.showToast?.('Quedó algún PDF pendiente de Drive')}setTimeout(()=>window.renderCobranzas?.(),350)}catch(e){console.error('[TIZ V86 recovery]',e);sessionStorage.removeItem(key);window.showToast?.('No se pudo completar la recuperación de PDFs')}}
window.recuperarFacturasArcaV86=recoverMissing;
function pdfHtml(o){const c=latest(o);if(!c?.cae)return '<span style="color:var(--text3)">—</span>';if(hasDrive(c))return '<span class="badge badge-green" title="PDF archivado en 2026 Facturacion">En Drive</span>';return `<div style="display:flex;gap:6px;align-items:center;flex-wrap:wrap"><span class="badge badge-amber">Pendiente</span><button class="btn btn-ghost btn-sm fv86-pdf-recover" data-n="${Number(c.cbteNro||0)}" title="Recupera el comprobante existente de ARCA y archiva solamente el PDF. No emite nada nuevo.">Archivar PDF</button></div>`}
function obraForRow(tr){const ot=base(tr.cells?.[0]?.textContent||'');return (window.DB?.obras||[]).find(x=>base(x.ot)===ot)||null}
function decorateTable(){const mod=document.getElementById('cobr-modulo-v48');if(!mod)return;const table=mod.querySelector('table');if(!table)return;const hr=table.querySelector('thead tr');if(hr&&!hr.querySelector('.fv86-pdf-head')){const th=document.createElement('th');th.className='fv86-pdf-head';th.textContent='PDF';const action=[...hr.children].find(x=>/acci[oó]n/i.test(x.textContent||''));action?hr.insertBefore(th,action):hr.appendChild(th)}table.querySelectorAll('tbody tr').forEach(tr=>{const o=obraForRow(tr);if(!o)return;let td=tr.querySelector('.fv86-pdf-cell');if(!td){td=document.createElement('td');td.className='fv86-pdf-cell';const action=tr.lastElementChild;action?tr.insertBefore(td,action):tr.appendChild(td)}td.innerHTML=pdfHtml(o);td.querySelectorAll('.fv86-pdf-recover').forEach(b=>b.onclick=()=>window.recuperarPdfFacturaV86(b.dataset.n,b))})}
function hook(){if(typeof window.renderCobranzas==='function'&&!window.renderCobranzas.__driveRetryV86){const old=window.renderCobranzas,w=function(){const r=old.apply(this,arguments);setTimeout(decorateTable,80);setTimeout(autoRetry,250);setTimeout(recoverMissing,700);return r};w.__driveRetryV86=true;window.renderCobranzas=w}decorateTable();setTimeout(autoRetry,300);setTimeout(recoverMissing,900)}
hook();window.addEventListener('load',()=>{hook();setTimeout(hook,700);setTimeout(hook,1700)});let n=0;const t=setInterval(()=>{hook();if(++n>80)clearInterval(t)},300);const mo=new MutationObserver(()=>{if(document.getElementById('page-cobranzas')?.classList.contains('active'))setTimeout(decorateTable,60)});mo.observe(document.documentElement,{childList:true,subtree:true});
})();
