// TIZ Facturacion y Cobranzas V2.0 - acciones operativas con guardrails
(function(){
'use strict';
const obra=id=>(window.DB?.obras||[]).find(o=>o.id===id)||null;
const now=()=>new Date().toISOString();
const n=v=>Number(v)||0;
const norm=v=>String(v??'').replace(/\D/g,'');
function work(obraId){return window.TIZFacturacionCobranzasDataV2?.build?.().workItems?.find(w=>w.obraId===obraId)||null}
async function save(o,patch){if(!o)throw new Error('No se encontro la OT');if(typeof window.updateDoc_!=='function')throw new Error('Firestore no disponible');await window.updateDoc_('obras',o.id,patch);Object.assign(o,patch);window.TIZFactCobUIV2?.render?.();return patch}
async function registrarCobro(obraId,payload){const o=obra(obraId),w=work(obraId);if(!o)throw new Error('No se encontro la OT');const cobros=Array.isArray(o.cobros)?[...o.cobros]:[],row={id:'cob-'+Date.now(),invoiceKey:String(payload?.invoiceKey||''),facturaNumero:String(payload?.facturaNumero||''),fecha:String(payload?.fecha||new Date().toISOString().slice(0,10)),importe:n(payload?.importe),medio:String(payload?.medio||''),referencia:String(payload?.referencia||''),retenciones:n(payload?.retenciones),observaciones:String(payload?.observaciones||''),creadoAt:now()};if(!(row.importe>0||row.retenciones>0))throw new Error('El cobro o la retencion debe ser mayor a cero');const aplicado=row.importe+row.retenciones;if(w&&aplicado-w.porCobrar>1&&!payload?.permitirExceso)throw new Error(`El cobro + retenciones supera el saldo abierto (${w.porCobrar.toLocaleString('es-AR',{style:'currency',currency:'ARS'})}). Revisalo antes de guardar.`);cobros.push(row);await save(o,{cobros});return row}
async function registrarFacturaManual(obraId,payload){const o=obra(obraId),w=work(obraId);if(!o)throw new Error('No se encontro la OT');const facturas=Array.isArray(o.facturasManual)?[...o.facturasManual]:[],numero=String(payload?.numeroCompleto||payload?.nroFactura||'').trim();if(!numero)throw new Error('Falta el numero de factura');const digits=norm(numero);const existentes=[...(w?.invoices||[]),...facturas];if(digits&&existentes.some(x=>norm(x.numeroCompleto||x.nroFactura)===digits))throw new Error('Ese numero de factura ya esta registrado en la OT');const neto=n(payload?.neto),iva=n(payload?.iva),total=n(payload?.total)||(neto+iva);if(!(neto>0||total>0))throw new Error('El importe de la factura debe ser mayor a cero');if(w&&neto-w.porFacturar>1&&!payload?.permitirExcesoHistorico)throw new Error(`El neto supera el saldo por facturar (${w.porFacturar.toLocaleString('es-AR',{style:'currency',currency:'ARS'})}). Si es una factura historica que corrige datos viejos, revisa primero el presupuesto.`);const row={id:'manual-'+Date.now(),origen:'manual',numeroCompleto:numero,fecha:String(payload?.fecha||new Date().toISOString().slice(0,10)),neto,iva,total,porcentaje:n(payload?.porcentaje),tipoParte:String(payload?.tipoParte||'otro'),estadoEnvio:String(payload?.estadoEnvio||'pendiente'),driveFileId:String(payload?.driveFileId||''),driveWebViewLink:String(payload?.driveWebViewLink||payload?.driveUrl||''),creadoAt:now()};facturas.push(row);await save(o,{facturasManual:facturas});return row}
async function guardarSeguimiento(obraId,payload){const o=obra(obraId);const seguimientoCobranzas={accion:String(payload?.accion||''),fecha:String(payload?.fecha||''),nota:String(payload?.nota||''),actualizadoAt:now()};const historial=Array.isArray(o?.seguimientoCobranzasHistorial)?[...o.seguimientoCobranzasHistorial]:[];historial.push({...seguimientoCobranzas,id:'seg-'+Date.now()});await save(o,{seguimientoCobranzas,seguimientoCobranzasHistorial:historial.slice(-100)});return seguimientoCobranzas}
async function guardarGestionFactura(obraId,invoiceKey,payload){const o=obra(obraId);if(!o)throw new Error('No se encontro la OT');const facturacionGestion={...(o.facturacionGestion||{})},key=String(invoiceKey||'').trim();if(!key)throw new Error('No se pudo identificar la factura');facturacionGestion[key]={...(facturacionGestion[key]||{}),estadoEnvio:String(payload?.estadoEnvio||facturacionGestion[key]?.estadoEnvio||''),fechaVencimientoPago:String(payload?.fechaVencimientoPago||facturacionGestion[key]?.fechaVencimientoPago||''),nota:String(payload?.nota||''),driveUrl:String(payload?.driveUrl||facturacionGestion[key]?.driveUrl||''),driveFileId:String(payload?.driveFileId||facturacionGestion[key]?.driveFileId||''),actualizadoAt:now()};await save(o,{facturacionGestion});return facturacionGestion[key]}
async function guardarCondicionPago(obraId,dias){const o=obra(obraId);if(!o)throw new Error('No se encontro la OT');const value=Math.max(0,n(dias)),finanzas={...(o.finanzas||{}),diasPago:value};await save(o,{finanzas,diasPago:value});return finanzas}
async function guardarEstadoCobranza(obraId,estado){const o=obra(obraId);if(!o)throw new Error('No se encontro la OT');const v=String(estado||'').toLowerCase().trim();if(!['pendiente','cobrado pendiente','cobrado'].includes(v))throw new Error('Estado de cobranza invalido');const patch={cobranzaEstadoManual:v,historicoCerrado:v==='cobrado',cobranzaEstadoManualAt:now()};await save(o,patch);return patch}
function emitirArca(obraId){if(typeof window.abrirFacturacionGeneralV63!=='function')throw new Error('El facturador ARCA no esta disponible');return window.abrirFacturacionGeneralV63(obraId)}
window.TIZFactCobActionsV2={registrarCobro,registrarFacturaManual,guardarSeguimiento,guardarGestionFactura,guardarCondicionPago,guardarEstadoCobranza,emitirArca};
})();
