// TIZ V83 — Puesto operativo de Facturación y Cobranzas
(function(){
'use strict';
const VERSION='FACTURACION-COBRANZAS-INTEGRAL-V1-20260914';
const num=v=>Number(v)||0;
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const money=v=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(num(v));
const base=v=>String(v??'').match(/\d{4,7}/)?.[0].replace(/^0+/,'')||'';
const hoy=()=>new Date().toISOString().slice(0,10);
function comprobantes(o){const a=Array.isArray(o?.comprobantesArca)?[...o.comprobantesArca]:Array.isArray(o?.facturasArca)?[...o.facturasArca]:[];if(o?.facturaArca?.cae&&!a.some(x=>x?.cae===o.facturaArca.cae))a.push(o.facturaArca);return a.filter(x=>x?.cae);}
function total(o){return num(o?.finanzas?.total||o?.neto||o?.importe||o?.infoPresupuesto?.importe)}
function cobrado(o){const f=o?.finanzas||{};return num(f.anticipo?.montoCobrado)+num(f.saldo?.montoCobrado)}
function retenciones(o){return Object.values(o?.finanzas?.retenciones||{}).reduce((a,v)=>a+num(v),0)}
function pendiente(o){return Math.max(0,total(o)-cobrado(o)-retenciones(o))}
function fechaCobro(o){const f=o?.finanzas||{};return f.saldo?.fechaPrevistaCobro||f.anticipo?.fechaPrevistaCobro||''}
function factura(o){return o?.facturaArca||comprobantes(o).slice(-1)[0]||{}}
function porFacturar(o){return total(o)>0&&!comprobantes(o).length&&norm(o?.estado)!=='anulado'}
function drivePendiente(o){const f=factura(o);return !!f.cae&&(f.drivePendiente===true||o?.facturaDrivePendiente===true||!f.driveFileId)}
function envioPendiente(o){const f=factura(o);return !!f.cae&&!f.emailUltimoEnvioAt}
function vencida(o){const f=fechaCobro(o);return pendiente(o)>0&&f&&f<hoy()}
function aprobadas(){return (window.DB?.obras||[]).filter(o=>['aprobado','en produccion','en producción','cobrado pendiente','cobrado'].includes(norm(o?.estado))||total(o)>0)}
function ensureStyle(){if(document.getElementById('fc83-style'))return;const s=document.createElement('style');s.id='fc83-style';s.textContent='.fc83{margin:0 0 14px}.fc83-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:10px}.fc83-head h3{margin:0;font-size:18px}.fc83-kpis{display:grid;grid-template-columns:repeat(6,minmax(120px,1fr));gap:8px}.fc83-k{border:1px solid var(--border);border-radius:10px;padding:10px;background:var(--surface)}.fc83-k small{display:block;color:var(--text3);font-size:8px;text-transform:uppercase}.fc83-k b{display:block;font:700 20px DM Mono,monospace;margin-top:4px}.fc83-alerts{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.fc83-chip{border:1px solid var(--border);border-radius:99px;padding:5px 8px;font-size:9px;background:var(--surface2)}.fc83-chip.red{border-color:rgba(239,91,91,.45);color:#ff7777}.fc83-chip.amber{border-color:rgba(232,184,75,.45);color:#e8b84b}@media(max-width:1100px){.fc83-kpis{grid-template-columns:repeat(2,1fr)}}';document.head.appendChild(s)}
function inject(){const page=document.getElementById('page-cobranzas');if(!page)return;ensureStyle();let box=document.getElementById('fc83-workstation');if(!box){box=document.createElement('section');box.id='fc83-workstation';box.className='fc83';const target=page.querySelector('.page-tabs,.tabs,#cobr-modulo-v48')||page.firstElementChild;target?.parentNode?.insertBefore(box,target)}const all=aprobadas(),pf=all.filter(porFacturar),dp=all.filter(drivePendiente),ep=all.filter(envioPendiente),ven=all.filter(vencida),pc=all.filter(o=>pendiente(o)>0&&comprobantes(o).length),cob=all.filter(o=>pendiente(o)<=.01&&comprobantes(o).length);const monto=pc.reduce((a,o)=>a+pendiente(o),0);box.innerHTML=`<div class="fc83-head"><div><h3>Facturación y Cobranzas</h3><div style="font-size:9px;color:var(--text3)">Puesto operativo · PV 00009 · ${VERSION}</div></div><div style="font-size:9px;color:var(--text3)">PDF fiscales: carpeta general 2026 Facturacion · nunca carpeta OT</div></div><div class="fc83-kpis"><div class="fc83-k"><small>Por facturar</small><b>${pf.length}</b></div><div class="fc83-k"><small>PDF pendiente</small><b>${dp.length}</b></div><div class="fc83-k"><small>Falta enviar</small><b>${ep.length}</b></div><div class="fc83-k"><small>Por cobrar</small><b>${pc.length}</b><span style="font-size:9px;color:var(--text3)">${money(monto)}</span></div><div class="fc83-k"><small>Vencidas</small><b>${ven.length}</b></div><div class="fc83-k"><small>Cobradas</small><b>${cob.length}</b></div></div><div class="fc83-alerts">${dp.length?`<span class="fc83-chip red">${dp.length} comprobante(s) autorizado(s) sin PDF archivado</span>`:''}${ep.length?`<span class="fc83-chip amber">${ep.length} factura(s) pendientes de envío</span>`:''}${ven.length?`<span class="fc83-chip red">${ven.length} cobranza(s) vencida(s) para reclamar</span>`:''}${!dp.length&&!ep.length&&!ven.length?'<span class="fc83-chip">Sin alertas administrativas críticas</span>':''}</div>`;}
function hook(){if(typeof window.renderCobranzas==='function'&&!window.renderCobranzas.__fc83){const old=window.renderCobranzas;const w=function(){const r=old.apply(this,arguments);setTimeout(inject,0);return r};w.__fc83=true;window.renderCobranzas=w}inject()}
window.tizFacturacionPuestoV83={refresh:inject,version:VERSION};hook();window.addEventListener('load',()=>{hook();setTimeout(hook,500);setTimeout(hook,1500)});let n=0;const t=setInterval(()=>{hook();if(++n>80)clearInterval(t)},300);
})();
