// TIZ V85 — control simple de anticipos, saldo pendiente y PDF fiscal
(function(){
'use strict';
const money=v=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(v)||0);
const num=v=>Number(v)||0;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const base=v=>String(v??'').match(/\d{4,7}/)?.[0].replace(/^0+/,'')||'';
const creditTypes=new Set([3,8,203,208]);
function total(o){return num(o?.finanzas?.total||o?.neto||o?.importe||o?.infoPresupuesto?.importe||o?.sectores?.cobranzas?.montoTotal||o?.sectores?.facturacion?.importePresupuestado)}
function comps(o){const a=Array.isArray(o?.comprobantesArca)?[...o.comprobantesArca]:Array.isArray(o?.facturasArca)?[...o.facturasArca]:[];if(o?.facturaArca?.cae&&!a.some(x=>x?.cae===o.facturaArca.cae))a.push(o.facturaArca);return a.filter(x=>x?.cae)}
function fiscal(o){const p=total(o),emit=comps(o).reduce((s,c)=>{const credito=c.familia==='credito'||creditTypes.has(Number(c.cbteTipo));return s+(credito?-num(c.neto):num(c.neto))},0),saldo=Math.max(0,p-emit),pct=p?Math.max(0,Math.min(100,emit/p*100)):0;return {p,emit,saldo,pct,restPct:p?Math.max(0,Math.min(100,saldo/p*100)):0}}
function eligible(o){return !!(o?.id&&total(o)>0&&(norm(o?.estado).startsWith('aprob')||norm(o?.infoPresupuesto?.estado).startsWith('aprob')||o?.origen==='presupuesto'||o?.presupuestoId||o?.infoPresupuesto?.nro||o?.facturaArca?.cae))}
function stateText(o){const f=fiscal(o);if(!f.emit)return '<span style="color:var(--text3)">Sin facturar</span>';if(f.saldo<=.01)return `<b style="color:var(--green)">Facturado 100%</b><br><span style="color:var(--text3)">${money(f.emit)} facturados</span>`;return `<b style="color:var(--amber)">Anticipo facturado ${f.pct.toFixed(f.pct%1?1:0)}%</b><br><span style="color:var(--text2)">${money(f.emit)} facturados · <b>${money(f.saldo)} pendientes</b></span>`}
function invoiceRefs(o){const list=comps(o).slice(-3).map(c=>`${esc(c.tipo||'FC')} ${esc(c.numeroCompleto||'')}`).filter(Boolean);return list.length?`<div style="font-size:9px;color:var(--text3);margin-top:3px">${list.join(' · ')}</div>`:''}
function driveBadge(o){if(!o?.facturaArca?.cae)return '';if(o?.facturaDrivePendiente||o?.facturaArca?.drivePendiente)return '<span class="badge badge-amber" title="La factura ya fue emitida; falta archivar su PDF">PDF pendiente</span>';if(o?.facturaArca?.driveFileId)return '<span class="badge badge-green">PDF en Drive</span>';return ''}
function actionHtml(o){const f=fiscal(o),has=!!comps(o).length,sent=!!o?.facturaArca?.emailUltimoEnvioAt,partial=has&&f.saldo>.01;const fact=f.saldo>.01?`<button class="btn btn-primary btn-sm fv85-fact" data-id="${esc(o.id)}"><i class="ti ti-receipt"></i> ${partial?'Facturar saldo':'Facturar'}</button>`:'';const retry=(o?.facturaDrivePendiente||o?.facturaArca?.drivePendiente)&&o?.facturaArca?.cae?`<button class="btn btn-ghost btn-sm fv85-drive" data-id="${esc(o.id)}">Archivar PDF</button>`:'';const send=o?.facturaArca?.cae&&!o?.facturaDrivePendiente&&!o?.facturaArca?.drivePendiente?`<button class="btn btn-ghost btn-sm fv85-mail" data-id="${esc(o.id)}">${sent?'Reenviar FC':'Enviar FC'}</button>`:'';return `<div style="display:flex;gap:7px;align-items:center;justify-content:flex-end;flex-wrap:wrap"><button class="btn btn-ghost btn-sm fv85-manage" data-id="${esc(o.id)}">Gestionar</button>${fact}${retry}${send}</div>`}
function bindActions(root){root?.querySelectorAll?.('.fv85-fact').forEach(b=>b.onclick=()=>window.abrirFacturacionGeneralV63?.(b.dataset.id));root?.querySelectorAll?.('.fv85-drive').forEach(b=>b.onclick=()=>window.reintentarPdfFacturaV83?.(b.dataset.id,b));root?.querySelectorAll?.('.fv85-mail').forEach(b=>b.onclick=()=>window.abrirEnvioFacturaEmailV61?.(b.dataset.id));root?.querySelectorAll?.('.fv85-manage').forEach(b=>b.onclick=()=>window.editarCobranzaObraV41?.(b.dataset.id))}
function renderFacturar(){if(window.cobTab!=='facturar')return false;const mod=document.getElementById('cobr-modulo-v48');if(!mod)return false;const rows=(window.DB?.obras||[]).filter(eligible).map(o=>({o,f:fiscal(o)})).filter(x=>x.f.saldo>.01&&x.o?.estadoGestionFactura!=='Cobrado').sort((a,b)=>num(base(b.o.ot))-num(base(a.o.ot))).map(({o,f})=>`<tr data-fv85="${esc(o.id)}"><td class="strong">${esc(base(o.ot))}</td><td><b>${esc(o.cliente||'')}</b><br><span style="color:var(--text3)">${esc(o.desc||o.descripcion||'')}</span></td><td>${stateText(o)}${invoiceRefs(o)}</td><td><b>${money(f.saldo)}</b><br><span style="color:var(--text3)">${f.restPct.toFixed(f.restPct%1?1:0)}% del presupuesto</span></td><td>${driveBadge(o)}</td><td>${actionHtml(o)}</td></tr>`).join('');mod.innerHTML=`<div class="card"><div class="card-header"><span class="card-title">Cola de facturación</span><span style="font-size:10px;color:var(--text3)">Los anticipos permanecen acá hasta facturar el 100%</span></div><div class="table-wrap"><table><thead><tr><th>OT</th><th>Cliente / obra</th><th>Facturación actual</th><th>Saldo por facturar</th><th>PDF</th><th>Acción</th></tr></thead><tbody>${rows||'<tr><td colspan="6" style="text-align:center;padding:30px;color:var(--text3)">No hay saldos pendientes de facturar.</td></tr>'}</tbody></table></div></div>`;bindActions(mod);return true}
function annotateOtherTabs(){if(window.cobTab==='facturar')return;const mod=document.getElementById('cobr-modulo-v48');if(!mod)return;mod.querySelectorAll('tbody tr[data-v76]').forEach(tr=>{const o=(window.DB?.obras||[]).find(x=>x.id===tr.dataset.v76);if(!o)return;const f=fiscal(o);if(tr.cells?.[2])tr.cells[2].innerHTML=stateText(o)+invoiceRefs(o)+(driveBadge(o)?`<div style="margin-top:4px">${driveBadge(o)}</div>`:'');const last=tr.cells?.[tr.cells.length-1];if(last&&f.saldo>.01&&!last.querySelector('.fv85-fact')){const wrap=document.createElement('span');wrap.innerHTML=`<button class="btn btn-primary btn-sm fv85-fact" data-id="${esc(o.id)}">Facturar saldo</button>`;last.querySelector('div')?.appendChild(wrap.firstElementChild);bindActions(last)}if(last&&(o?.facturaDrivePendiente||o?.facturaArca?.drivePendiente)&&!last.querySelector('.fv85-drive')){const wrap=document.createElement('span');wrap.innerHTML=`<button class="btn btn-ghost btn-sm fv85-drive" data-id="${esc(o.id)}">Archivar PDF</button>`;last.querySelector('div')?.appendChild(wrap.firstElementChild);bindActions(last)}})}
function enhanceModal(){const root=document.getElementById('modal-fv83');if(!root||root.dataset.fv85)return;root.dataset.fv85='1';const ot=base(root.querySelector('.modal-title')?.textContent||''),o=(window.DB?.obras||[]).find(x=>base(x.ot)===ot);if(!o)return;const f=fiscal(o),pct=root.querySelector('#fv83-pct'),net=root.querySelector('#fv83-net'),note=root.querySelector('.fv83-note');if(pct){pct.max=String(Math.max(.01,Math.round(f.restPct*100)/100));const lab=pct.closest('.form-group')?.querySelector('label');if(lab)lab.textContent='Porcentaje del presupuesto a facturar ahora'}if(net){net.max=String(f.saldo)}const box=document.createElement('div');box.className='fv83-full';box.id='fv85-summary';box.style.cssText='border:1px solid var(--border2);background:var(--surface2);border-radius:8px;padding:10px;margin-top:10px;font-size:11px';const render=()=>{const n=Math.max(0,num(net?.value)),after=Math.max(0,f.saldo-n),afterPct=f.p?Math.min(100,(f.emit+n)/f.p*100):0;let kind='FACTURA TOTAL';if(f.emit>0&&after<=.01)kind='SALDO FINAL';else if(n<f.saldo-.01)kind=f.emit>0?'NUEVO PAGO PARCIAL':'ANTICIPO';box.innerHTML=`<b>${kind}</b><br>Presupuesto: ${money(f.p)} · Ya facturado: ${money(f.emit)} · Saldo actual: <b>${money(f.saldo)}</b><br>Después de esta factura: ${afterPct.toFixed(afterPct%1?1:0)}% facturado · saldo ${money(after)}`};render();pct?.addEventListener('input',render);net?.addEventListener('input',render);note?.insertAdjacentElement('afterend',box);if(f.emit>0&&f.saldo>.01){const b=document.createElement('button');b.type='button';b.className='btn btn-ghost btn-sm';b.textContent='Usar saldo completo';b.style.marginTop='8px';b.onclick=()=>{if(net)net.value=f.saldo.toFixed(2);if(pct)pct.value=(f.restPct).toFixed(2);net?.dispatchEvent(new Event('input',{bubbles:true}));render()};box.appendChild(b)}const emit=root.querySelector('#fv83-emit');if(emit&&!emit.dataset.fv85){emit.dataset.fv85='1';emit.addEventListener('click',e=>{const n=num(net?.value);if(n-f.saldo>.01){e.preventDefault();e.stopImmediatePropagation();alert(`El importe supera el saldo pendiente de ${money(f.saldo)}.`)}},true)}}
let renderTimer=null;
function postRender(){clearTimeout(renderTimer);renderTimer=setTimeout(()=>{if(!renderFacturar())annotateOtherTabs();enhanceModal()},30)}
function installRenderHook(){if(typeof window.renderCobranzas!=='function'||window.renderCobranzas.__fv85)return;const old=window.renderCobranzas;let pending=null;window.renderCobranzas=function(){const ctx=this,args=arguments;clearTimeout(pending);pending=setTimeout(()=>{old.apply(ctx,args);postRender()},60)};window.renderCobranzas.__fv85=true}
const mo=new MutationObserver(()=>{enhanceModal();if(document.getElementById('page-cobranzas')?.classList.contains('active'))postRender()});
mo.observe(document.documentElement,{childList:true,subtree:true});
function boot(){installRenderHook();postRender()}
boot();window.addEventListener('load',()=>{boot();setTimeout(boot,500);setTimeout(boot,1500)});let tries=0;const t=setInterval(()=>{installRenderHook();if(++tries>40)clearInterval(t)},250);
})();
