// TIZ V86 — reintento seguro de Drive + recuperacion fiscal historica
(function(){
'use strict';
const ENDPOINT='https://us-central1-tiz---app.cloudfunctions.net/facturacionReintentarDriveV83';
const RECOVER_ENDPOINT='https://us-central1-tiz---app.cloudfunctions.net/facturacionRecuperarHistoricosV86';
const AUTO_KEY='tiz-drive-retry-v83';
const RECOVER_KEY='tiz-arca-recover-v86-2-3';
async function token(){const [{getApp},{getAuth}]=await Promise.all([import('https://www.gstatic.com/firebasejs/10.12.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/10.12.0/firebase-auth.js')]);const u=getAuth(getApp()).currentUser;if(!u)throw new Error('Sesión no iniciada');return u.getIdToken()}
async function callRetry(id){const r=await fetch(ENDPOINT,{method:'POST',headers:{Authorization:'Bearer '+await token(),'Content-Type':'application/json'},body:JSON.stringify({obraId:id})}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok){const err=new Error(d.error||'No se pudo archivar el PDF');err.meta=d;throw err}return d}
function applySuccess(o,d){o.facturaArca=o.facturaArca||{};o.facturaArca.driveFileId=d.fileId;o.facturaArca.driveWebViewLink=d.webViewLink;o.facturaArca.drivePendiente=false;o.facturaDrivePendiente=false;window.showToast?.('PDF archivado en 2026 Facturacion ✓')}
function errorText(e){const m=e?.meta||{},actor=m.serviceAccountEmail?`\n\nCuenta que necesita acceso Editor a 2026 Facturacion:\n${m.serviceAccountEmail}`:'',folder=m.folderId?`\nCarpeta: ${m.folderId}`:'';return 'No se pudo archivar el PDF.\n\n'+(e.message||e)+actor+folder}
window.reintentarPdfFacturaV83=async function(id,btn,opts={}){const o=(window.DB?.obras||[]).find(x=>x.id===id);if(!o)return false;if(!o.facturaArca?.cae){if(!opts.silent)alert('La OT no tiene un comprobante ARCA autorizado.');return false}const old=btn?.textContent;if(btn){btn.disabled=true;btn.textContent='Archivando…'}try{const d=await callRetry(id);applySuccess(o,d);if(!opts.silent)setTimeout(()=>window.renderCobranzas?.(),60);return true}catch(e){console.error('[TIZ Drive retry]',e);if(!opts.silent)alert(errorText(e));else{window.showToast?.('PDF pendiente en Drive');o.__driveRetryError=errorText(e)}return false}finally{if(btn){btn.disabled=false;btn.textContent=old}}};
async function autoRetry(){for(const o of (window.DB?.obras||[])){if(!o?.id||!o.facturaArca?.cae||o.facturaArca?.driveFileId||!o.facturaDrivePendiente)continue;const key=`${AUTO_KEY}:${o.id}:${o.facturaArca.cae}`;if(sessionStorage.getItem(key))continue;sessionStorage.setItem(key,'1');await window.reintentarPdfFacturaV83(o.id,null,{silent:true});}}
async function recoverMissing(){if(sessionStorage.getItem(RECOVER_KEY))return;sessionStorage.setItem(RECOVER_KEY,'1');try{const r=await fetch(RECOVER_ENDPOINT,{method:'POST',headers:{Authorization:'Bearer '+await token(),'Content-Type':'application/json'},body:JSON.stringify({cbteTipo:1,numeros:[2,3]})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'No se pudieron recuperar las facturas');const ok=(d.resultados||[]).filter(x=>x.ok),bad=(d.resultados||[]).filter(x=>!x.ok);if(ok.length){console.info('[TIZ V86] Recuperadas',ok);window.showToast?.(`ARCA: ${ok.length} PDF recuperado${ok.length>1?'s':''} en 2026 Facturacion ✓`)}if(bad.length){console.error('[TIZ V86] Recuperacion incompleta',bad);alert('Recuperación ARCA incompleta.\n\n'+bad.map(x=>`FC 00009-${String(x.cbteNro||'').padStart(8,'0')}: ${x.error}`).join('\n'))}}catch(e){console.error('[TIZ V86 recovery]',e);alert('No se pudieron recuperar automáticamente las FC 00002/00003.\n\n'+(e.message||e))}}
window.recuperarFacturasArcaV86=recoverMissing;
function inject(){document.querySelectorAll('#cobr-modulo-v48 table tbody tr').forEach(tr=>{const ot=String(tr.cells?.[0]?.textContent||'').match(/\d{4,7}/)?.[0].replace(/^0+/,'')||'',o=(window.DB?.obras||[]).find(x=>String(x.ot||'').match(/\d{4,7}/)?.[0].replace(/^0+/,'')===ot);if(!o||!o.facturaArca?.cae||(!o.facturaDrivePendiente&&o.facturaArca.driveFileId))return;const cell=tr.cells?.[tr.cells.length-1];if(!cell||cell.querySelector('.fv83-drive-retry'))return;const b=document.createElement('button');b.className='btn btn-ghost btn-sm fv83-drive-retry';b.textContent='Archivar PDF';b.title=o.__driveRetryError||'Reintenta sólo el PDF en Drive; no vuelve a emitir en ARCA.';b.onclick=()=>window.reintentarPdfFacturaV83(o.id,b);cell.appendChild(b)})}
function hook(){if(typeof window.renderCobranzas==='function'&&!window.renderCobranzas.__driveRetryV83){const old=window.renderCobranzas,w=function(){const r=old.apply(this,arguments);setTimeout(inject,50);setTimeout(autoRetry,250);return r};w.__driveRetryV83=true;window.renderCobranzas=w}inject();setTimeout(autoRetry,300)}
hook();window.addEventListener('load',()=>{hook();setTimeout(hook,700);setTimeout(recoverMissing,1500)});let n=0;const t=setInterval(()=>{hook();if(++n>80)clearInterval(t)},300);
})();
