// TIZ V86 — estado visible de PDF + recuperación segura de comprobantes existentes
(function(){
'use strict';
const ENDPOINT='https://us-central1-tiz---app.cloudfunctions.net/facturacionRecuperarHistoricosV86';
const AUTO_KEY='tiz-v86-recover-2-3';
const base=v=>String(v??'').match(/\d{4,7}/)?.[0].replace(/^0+/,'')||'';
async function token(){const [{getApp},{getAuth}]=await Promise.all([import('https://www.gstatic.com/firebasejs/10.12.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/10.12.0/firebase-auth.js')]);const u=getAuth(getApp()).currentUser;if(!u)throw new Error('Sesión no iniciada');return u.getIdToken()}
function comps(o){const a=Array.isArray(o?.comprobantesArca)?[...o.comprobantesArca]:Array.isArray(o?.facturasArca)?[...o.facturasArca]:[];if(o?.facturaArca?.cae&&!a.some(x=>x?.cae===o.facturaArca.cae))a.push(o.facturaArca);return a.filter(x=>x?.cae)}
function current(o){return [...comps(o)].sort((a,b)=>Number(b?.cbteNro||0)-Number(a?.cbteNro||0))[0]||o?.facturaArca||null}
function hasDrive(c){return !!(c?.driveFileId||c?.fileId||c?.driveWebViewLink)}
async function recover(nums,opts={}){const r=await fetch(ENDPOINT,{method:'POST',headers:{Authorization:'Bearer '+await token(),'Content-Type':'application/json'},body:JSON.stringify({cbteTipo:1,numeros:nums})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'No se pudo consultar ARCA');const ok=(d.resultados||[]).filter(x=>x.ok),bad=(d.resultados||[]).filter(x=>!x.ok);if(ok.length&&!opts.silent)window.showToast?.(`PDF${ok.length>1?'s':''} archivado${ok.length>1?'s':''} en 2026 Facturacion ✓`);if(bad.length&&!opts.silent)alert('No se pudieron recuperar:\n'+bad.map(x=>`FC ${String(x.cbteNro).padStart(8,'0')}: ${x.error}`).join('\n'));return d}
window.recuperarPdfFacturaV86=async function(n,btn){const old=btn?.textContent;if(btn){btn.disabled=true;btn.textContent='Recuperando…'}try{const d=await recover([Number(n)]);const row=d.resultados?.[0];if(row?.ok){window.showToast?.(`FC ${row.numero}: PDF en Drive ✓`);setTimeout(()=>window.renderCobranzas?.(),250)}return !!row?.ok}catch(e){alert('No se pudo recuperar el PDF.\n\n'+(e.message||e));return false}finally{if(btn){btn.disabled=false;btn.textContent=old}}};
function pdfHtml(o){const c=current(o);if(!c?.cae)return '<span style="color:var(--text3)">—</span>';if(hasDrive(c))return `<span class="badge badge-green" title="PDF archivado en 2026 Facturacion">En Drive</span>`;return `<div style="display:flex;gap:6px;align-items:center;flex-wrap:wrap"><span class="badge badge-amber">Pendiente</span><button class="btn btn-ghost btn-sm fv86-recover" data-n="${Number(c.cbteNro||0)}" title="Consulta el comprobante existente en ARCA y archiva sólo el PDF. No emite nada nuevo.">Archivar PDF</button></div>`}
function findObra(tr){const ot=base(tr.cells?.[0]?.textContent||'');return (window.DB?.obras||[]).find(o=>base(o.ot)===ot)||null}
function decorate(){const mod=document.getElementById('cobr-modulo-v48');if(!mod)return;const table=mod.querySelector('table');if(!table)return;const hr=table.querySelector('thead tr');if(hr&&!hr.querySelector('.fv86-pdf-head')){const th=document.createElement('th');th.className='fv86-pdf-head';th.textContent='PDF';const action=[...hr.children].find(x=>/acci[oó]n/i.test(x.textContent||''));if(action)hr.insertBefore(th,action);else hr.appendChild(th)}
 table.querySelectorAll('tbody tr').forEach(tr=>{if(tr.querySelector('.fv86-pdf-cell'))return;const o=findObra(tr);if(!o)return;const td=document.createElement('td');td.className='fv86-pdf-cell';td.innerHTML=pdfHtml(o);const action=tr.lastElementChild;if(action)tr.insertBefore(td,action);else tr.appendChild(td);td.querySelectorAll('.fv86-recover').forEach(b=>b.onclick=()=>window.recuperarPdfFacturaV86(b.dataset.n,b))})}
async function autoRecover(){if(sessionStorage.getItem(AUTO_KEY))return;const obras=window.DB?.obras||[];const need=[2,3].filter(n=>{const o=obras.find(x=>comps(x).some(c=>Number(c.cbteTipo||1)===1&&Number(c.cbteNro)===n));const c=o&&comps(o).find(c=>Number(c.cbteTipo||1)===1&&Number(c.cbteNro)===n);return !c||!hasDrive(c)});if(!need.length){sessionStorage.setItem(AUTO_KEY,'done');return}sessionStorage.setItem(AUTO_KEY,'running');try{const d=await recover(need,{silent:true});const ok=(d.resultados||[]).filter(x=>x.ok);const bad=(d.resultados||[]).filter(x=>!x.ok);if(ok.length)window.showToast?.(`Recuperados ${ok.map(x=>x.numero).join(', ')} → Drive ✓`);if(bad.length)window.showToast?.(`PDF pendiente: ${bad.map(x=>String(x.cbteNro).padStart(8,'0')).join(', ')}`);sessionStorage.setItem(AUTO_KEY,'done');setTimeout(()=>window.renderCobranzas?.(),300)}catch(e){console.error('[TIZ V86 recovery]',e);sessionStorage.removeItem(AUTO_KEY);window.showToast?.('No se pudo completar la recuperación de PDFs')}}
function hook(){if(typeof window.renderCobranzas==='function'&&!window.renderCobranzas.__fv86pdf){const old=window.renderCobranzas;window.renderCobranzas=function(){const r=old.apply(this,arguments);setTimeout(decorate,80);setTimeout(autoRecover,500);return r};window.renderCobranzas.__fv86pdf=true}decorate();setTimeout(autoRecover,700)}
hook();window.addEventListener('load',()=>{hook();setTimeout(hook,700);setTimeout(hook,1800)});const mo=new MutationObserver(()=>{if(document.getElementById('page-cobranzas')?.classList.contains('active'))setTimeout(decorate,40)});mo.observe(document.documentElement,{childList:true,subtree:true});
})();
