// TIZ V83 — botón seguro de prueba ARCA homologación
(function(){
'use strict';
const ENDPOINT='https://us-central1-tiz---app.cloudfunctions.net/arcaHomologacionEmitirPrueba';
const num=v=>Number(v)||0;
const money=v=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:2}).format(num(v));
async function token(){const [{getApp},{getAuth}]=await Promise.all([import('https://www.gstatic.com/firebasejs/10.12.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/10.12.0/firebase-auth.js')]);const u=getAuth(getApp()).currentUser;if(!u)throw new Error('Sesión no iniciada');return u.getIdToken()}
function items(o,net){const src=(Array.isArray(o?.itemsCotizados)?o.itemsCotizados:[]).map(x=>({descripcion:String(x.descripcion||x.desc||'').trim(),cantidad:num(x.cantidad||x.cant||x.unidades||1)||1,unitario:num(x.unitario??x.precio??x.precioUnitario)})).filter(x=>x.descripcion);const base=src.reduce((a,x)=>a+x.cantidad*x.unitario,0)||num(o?.finanzas?.total||o?.neto||o?.importe)||net,ratio=base?net/base:1;return src.length?src.map(x=>({...x,unitario:Math.round(x.unitario*ratio*100)/100})):[{descripcion:o?.desc||o?.descripcion||`OT ${o?.ot||''}`,cantidad:1,unitario:net}]}
function obra(root){const id=root?.dataset?.obraId;return (window.DB?.obras||[]).find(x=>x.id===id)||null}
function hookOpen(){const old=window.abrirFacturacionIntegralV83;if(typeof old!=='function'||old.__homoV83)return;const wrapped=function(id){const r=old.apply(this,arguments);setTimeout(()=>{const root=document.getElementById('modal-fv83');if(root){root.dataset.obraId=id;inject(root)}},0);return r};wrapped.__homoV83=true;window.abrirFacturacionIntegralV83=wrapped;window.abrirFacturacionProduccionV67=wrapped;window.abrirFacturacionGeneralV63=wrapped}
function inject(root){if(!root||root.querySelector('#fv83-homo'))return;const actions=root.querySelector('.modal-actions'),real=root.querySelector('#fv83-emit');if(!actions||!real)return;const b=document.createElement('button');b.id='fv83-homo';b.className='btn btn-ghost';b.textContent='PROBAR EN HOMOLOGACIÓN';b.style.borderColor='var(--blue)';b.style.color='var(--blue)';actions.insertBefore(b,real);const note=root.querySelector('.fv83-note');if(note)note.insertAdjacentHTML('beforeend','<br><span style="color:var(--blue)"><b>Modo prueba:</b> “PROBAR EN HOMOLOGACIÓN” no genera comprobante fiscal real ni consume numeración de PV 00009.</span>');b.onclick=async()=>{const o=obra(root);if(!o)return alert('No se pudo identificar la OT.');const cuit=String(root.querySelector('#fv83-cuit')?.value||'').replace(/\D/g,''),net=num(root.querySelector('#fv83-net')?.value),tipo=num(root.querySelector('#fv83-type')?.value),cond=num(root.querySelector('#fv83-cond')?.value||1),ivaRaw=root.querySelector('#fv83-iva')?.value||'21';if(!/^\d{11}$/.test(cuit))return alert('Revisá el CUIT.');if(!(net>0))return alert('Revisá el importe neto.');if(!confirm(`PRUEBA ARCA · HOMOLOGACIÓN\n\nOT ${o.ot}\nNeto ${money(net)}\n\nNo genera una factura fiscal real. ¿Continuar?`))return;const old=b.textContent;b.disabled=true;b.textContent='Probando ARCA…';try{const payload={docNro:cuit,neto:net,items:items(o,net),cbteTipo:tipo,condicionIVAReceptorId:cond,tratamientoIva:ivaRaw==='exento'?'exento':'gravado',alicuota:ivaRaw==='exento'?0:num(ivaRaw)};const r=await fetch(ENDPOINT,{method:'POST',headers:{Authorization:'Bearer '+await token(),'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||'ARCA homologación rechazó la prueba');alert(`PRUEBA APROBADA EN HOMOLOGACIÓN\n\nPV prueba: ${String(d.ptoVta||'—').padStart(5,'0')}\nComprobante: ${d.cbteNro||'—'}\nCAE prueba: ${d.cae||'—'}\nNeto: ${money(d.neto)}\nIVA: ${money(d.iva)}\nTotal: ${money(d.total)}\n\nEsto NO es una factura fiscal real.`);window.showToast?.('Prueba ARCA homologación aprobada ✓')}catch(e){console.error('[TIZ V83 homologación]',e);alert('La prueba de homologación falló.\n\n'+(e.message||e))}finally{b.disabled=false;b.textContent=old}}}
function install(){hookOpen();const root=document.getElementById('modal-fv83');if(root)inject(root)}
install();window.addEventListener('load',()=>{install();setTimeout(install,500)});let n=0;const t=setInterval(()=>{install();if(++n>120)clearInterval(t)},250);
})();
