// TIZ Produccion V5 - Tablero de control operativo estable
(()=>{
'use strict';
window.__TIZ_PRODUCCION_DASHBOARD_V5__=true;
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>{if(!v)return null;const d=new Date(String(v).length===10?String(v)+'T12:00:00':v);return isNaN(d)?null:d};
const daysTo=v=>{const d=date(v);if(!d)return null;const t=new Date();t.setHours(0,0,0,0);return Math.ceil((d-t)/86400000)};
const sectors=o=>window.getSectoresV35?window.getSectoresV35(o):(o.sectores||{});
const prod=o=>({...((o.gestionSectores||{}).produccion||{}),...((sectors(o).produccion)||{})});
const active=o=>['aprobado','en produccion','en producción'].includes(norm(o.estado))&&o.archivado!==true&&o.revisionVigente!==false;
const status=o=>{const p=prod(o),e=norm(p.estadoInterno||p.estado);if(e.includes('bloq'))return'BLOQUEADO';if(e.includes('final')||e.includes('termin')||p.terminada)return'FINALIZADA';if(e.includes('control'))return'EN CONTROL';if(e.includes('proceso')||e.includes('produccion'))return'EN PRODUCCIÓN';if(e.includes('prepar'))return'EN PREPARACIÓN';return'PENDIENTE'};
const due=o=>{const p=prod(o),s=sectors(o);return p.fechaFinPlan||p.compromiso||s?.colocaciones?.compromiso||o.fprod_c||o.fcol_c||''};
const resp=o=>{const p=prod(o);return p.operadorAsignado||p.responsable||p.asignadoA||'Sin asignar'};
const machine=o=>{const p=prod(o);const route=(p.procesos||[]).map(x=>x.recurso).filter(Boolean);return route.length?route.join(' → '):(p.maquinaId||p.recurso||p.maquina||'Sin máquina')};
const works=()=>[...(window.DB?.obras||[])].filter(active).filter(o=>status(o)!=='FINALIZADA');
function countBy(list,fn){const m=new Map();list.forEach(o=>{const k=fn(o)||'Sin asignar';m.set(k,(m.get(k)||0)+1)});return[...m.entries()].sort((a,b)=>b[1]-a[1])}
function ensureStyle(){if(document.getElementById('tiz-prod-v5-css'))return;const s=document.createElement('style');s.id='tiz-prod-v5-css';s.textContent=`.tpd{display:grid;grid-template-columns:repeat(12,1fr);gap:10px;margin:0 0 12px}.tpd-card{background:var(--surface);border:1px solid var(--border);border-radius:12px;padding:12px}.tpd-card h3{font-size:11px;margin:0 0 8px;color:var(--text)}.tpd-big{font:700 26px 'DM Mono',monospace}.tpd-sub{font-size:9px;color:var(--text3);margin-top:3px}.tpd-today{grid-column:span 3;border-left:3px solid var(--blue)}.tpd-week{grid-column:span 3;border-left:3px solid var(--amber)}.tpd-block{grid-column:span 3;border-left:3px solid var(--red)}.tpd-ready{grid-column:span 3;border-left:3px solid var(--green)}.tpd-load{grid-column:span 6}.tpd-row{display:grid;grid-template-columns:minmax(90px,1fr) 3fr 28px;gap:7px;align-items:center;margin:7px 0;font-size:9px}.tpd-bar{height:6px;background:#0b0b0b;border-radius:99px;overflow:hidden}.tpd-bar span{display:block;height:100%;background:var(--blue);border-radius:99px}.tpd-machine .tpd-bar span{background:var(--purple)}.tpd-attn{grid-column:span 12}.tpd-attn-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.tpd-alert{border:1px solid var(--border);background:var(--surface2);border-radius:8px;padding:9px;font-size:9px}.tpd-alert.red{border-left:3px solid var(--red)}.tpd-alert.amber{border-left:3px solid var(--amber)}.tpd-alert b{display:block;margin-bottom:3px}.tpd-empty{font-size:9px;color:var(--text3)}@media(max-width:1100px){.tpd-today,.tpd-week,.tpd-block,.tpd-ready{grid-column:span 6}.tpd-load{grid-column:span 12}.tpd-attn-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function render(){const host=document.querySelector('#page-produccion .tpc')||document.querySelector('#produccion-v34-root .tpc');if(!host)return;ensureStyle();let box=document.getElementById('tpd-v5');if(!box){box=document.createElement('div');box.id='tpd-v5';host.insertBefore(box,host.querySelector('.tpc-kpis')||host.firstChild?.nextSibling||null)}const list=works(),today=list.filter(o=>daysTo(due(o))===0),week=list.filter(o=>{const d=daysTo(due(o));return d!==null&&d>=0&&d<=7}),blocked=list.filter(o=>status(o)==='BLOQUEADO'),ready=list.filter(o=>status(o)==='EN CONTROL'||status(o)==='EN PRODUCCIÓN'),byResp=countBy(list,resp),byMachine=countBy(list,machine),maxR=Math.max(1,...byResp.map(x=>x[1])),maxM=Math.max(1,...byMachine.map(x=>x[1]));const overdue=list.filter(o=>{const d=daysTo(due(o));return d!==null&&d<0}).sort((a,b)=>daysTo(due(a))-daysTo(due(b))).slice(0,3),unassigned=list.filter(o=>resp(o)==='Sin asignar').slice(0,3),nextBlocked=blocked.slice(0,3);const loadRows=(arr,max,cls='')=>arr.slice(0,6).map(([k,v])=>`<div class="tpd-row ${cls}"><span>${esc(k)}</span><div class="tpd-bar"><span style="width:${Math.round(v/max*100)}%"></span></div><b>${v}</b></div>`).join('')||'<div class="tpd-empty">Sin datos todavía.</div>';box.innerHTML=`<div class="tpd"><div class="tpd-card tpd-today"><h3>HOY</h3><div class="tpd-big">${today.length}</div><div class="tpd-sub">trabajos con fecha necesaria hoy</div></div><div class="tpd-card tpd-week"><h3>PRÓXIMOS 7 DÍAS</h3><div class="tpd-big">${week.length}</div><div class="tpd-sub">requieren planificación cercana</div></div><div class="tpd-card tpd-block"><h3>BLOQUEADOS</h3><div class="tpd-big">${blocked.length}</div><div class="tpd-sub">necesitan acción para destrabar</div></div><div class="tpd-card tpd-ready"><h3>EN CURSO / CONTROL</h3><div class="tpd-big">${ready.length}</div><div class="tpd-sub">trabajos actualmente activos</div></div><div class="tpd-card tpd-load"><h3>CARGA POR RESPONSABLE</h3>${loadRows(byResp,maxR)}</div><div class="tpd-card tpd-load tpd-machine"><h3>CARGA POR MÁQUINA / RECURSO</h3>${loadRows(byMachine,maxM,'tpd-machine')}</div><div class="tpd-card tpd-attn"><h3>ATENCIÓN INMEDIATA</h3><div class="tpd-attn-grid">${overdue.map(o=>`<div class="tpd-alert red"><b>OT ${esc(o.ot)} · vencida</b>${esc(o.desc||o.cliente||'')} · ${Math.abs(daysTo(due(o)))} días</div>`).join('')}${nextBlocked.map(o=>`<div class="tpd-alert red"><b>OT ${esc(o.ot)} · bloqueada</b>${esc(prod(o).motivoBloqueo||'Sin motivo cargado')}</div>`).join('')}${unassigned.map(o=>`<div class="tpd-alert amber"><b>OT ${esc(o.ot)} · sin responsable</b>${esc(o.desc||o.cliente||'')}</div>`).join('')||'<div class="tpd-empty">Sin alertas críticas.</div>'}</div></div></div>`}
window.renderProduccionDashboardV5=render;
setTimeout(render,0);
})();