// TIZ Produccion V6 - ficha operativa por OT + procesos dinamicos
(()=>{
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v||'').toLowerCase().trim();
const getO=id=>(window.DB?.obras||[]).find(x=>x.id===id);
const P=o=>(o?.gestionSectores||{}).produccion||{};
const catalog=()=>{try{return JSON.parse(localStorage.getItem('tiz_prod_recursos_v6')||'[]')}catch{return[]}};
const saveCatalog=a=>localStorage.setItem('tiz_prod_recursos_v6',JSON.stringify([...new Set(a.filter(Boolean))]));
function css(){if(document.getElementById('tpf-v6-css'))return;const s=document.createElement('style');s.id='tpf-v6-css';s.textContent=`.tpf-plus{width:30px;height:30px;border:1px solid var(--border);background:var(--surface2);color:var(--accent);border-radius:7px;font-size:18px;cursor:pointer}.tpf-process{border:1px solid var(--border);border-radius:9px;padding:10px;margin:8px 0;background:var(--surface2)}.tpf-process-grid{display:grid;grid-template-columns:1.4fr 1fr 1fr 1fr auto;gap:7px;align-items:end}.tpf-section{grid-column:1/-1;border-top:1px solid var(--border);padding-top:10px;margin-top:3px}.tpf-section-title{display:flex;justify-content:space-between;align-items:center;margin-bottom:6px}.tpf-section-title b{font-size:11px}.tpf-help{font-size:8px;color:var(--text3)}.tpf-drive{display:flex;gap:7px;align-items:center;padding:9px;border:1px solid var(--border);border-radius:8px;background:rgba(91,156,246,.05)}@media(max-width:800px){.tpf-process-grid{grid-template-columns:1fr 1fr}.tpf-process-grid .tpf-remove{grid-column:2}}`;document.head.appendChild(s)}
function resourceOptions(cur){const historical=(window.DB?.obras||[]).flatMap(o=>{const p=P(o);return [p.maquina,...(p.procesos||[]).map(x=>x.recurso)]});const all=[...new Set([...catalog(),...historical,cur].filter(Boolean))].sort();return `<option value="">Seleccionar máquina/proceso…</option>${all.map(x=>`<option ${x===cur?'selected':''}>${esc(x)}</option>`).join('')}`}
function procRow(x={}){return `<div class="tpf-process"><div class="tpf-process-grid"><div class="tpc-field"><label>Máquina / proceso</label><select class="tpf-resource">${resourceOptions(x.recurso||'')}</select></div><div class="tpc-field"><label>Responsable</label><input class="tpf-owner" value="${esc(x.responsable||'')}"></div><div class="tpc-field"><label>Estado</label><select class="tpf-state"><option ${x.estado==='Pendiente'?'selected':''}>Pendiente</option><option ${x.estado==='Listo para iniciar'?'selected':''}>Listo para iniciar</option><option ${x.estado==='En proceso'?'selected':''}>En proceso</option><option ${x.estado==='En control'?'selected':''}>En control</option><option ${x.estado==='Terminado'?'selected':''}>Terminado</option><option ${x.estado==='Bloqueado'?'selected':''}>Bloqueado</option></select></div><div class="tpc-field"><label>Fecha objetivo</label><input class="tpf-date" type="date" value="${esc(x.fecha||'')}"></div><button type="button" class="tpc-edit tpf-remove" onclick="this.closest('.tpf-process').remove()">Quitar</button></div><div class="tpc-field" style="margin-top:7px"><label>Indicaciones / trabajo a realizar</label><input class="tpf-notes" value="${esc(x.indicaciones||'')}" placeholder="Ej.: imprimir frente, cortar contorno, laminar…"></div></div>`}
function install(){if(typeof window.tpcQuickEdit!=='function')return setTimeout(install,250);css();const prev=window.tpcQuickEdit;window.tpcQuickEdit=function(id){prev(id);const o=getO(id),p=P(o),form=document.querySelector('#tpc-modal-body .tpc-form');if(!o||!form)return;document.getElementById('tpc-modal-title').textContent=`OT ${o.ot||'—'} · Gestión de Producción`;form.insertAdjacentHTML('beforeend',`<div class="tpf-section"><div class="tpf-section-title"><div><b>Ruta de producción</b><div class="tpf-help">Agregá todas las máquinas o procesos que necesite esta OT, en el orden de trabajo.</div></div><button type="button" class="tpf-plus" onclick="tpfAddProcess()" title="Agregar máquina o proceso">+</button></div><div id="tpf-processes">${(p.procesos||[]).map(procRow).join('')||procRow({})}</div></div><div class="tpf-section"><div class="tpf-section-title"><b>Datos para producir</b><span class="tpf-help">Información específica de taller</span></div><div class="tpc-form"><div class="tpc-field"><label>Cantidad</label><input id="tpf-qty" value="${esc(p.cantidad||'')}"></div><div class="tpc-field"><label>Medidas</label><input id="tpf-size" value="${esc(p.medidas||'')}"></div><div class="tpc-field"><label>Material / sustrato</label><input id="tpf-material" value="${esc(p.material||'')}"></div><div class="tpc-field"><label>Terminación</label><input id="tpf-finish" value="${esc(p.terminacion||'')}"></div><div class="tpc-field"><label>Material disponible</label><select id="tpf-stock"><option value="">Sin verificar</option><option ${p.materialDisponible==='Sí'?'selected':''}>Sí</option><option ${p.materialDisponible==='No'?'selected':''}>No</option><option ${p.materialDisponible==='Parcial'?'selected':''}>Parcial</option></select></div><div class="tpc-field"><label>Archivo listo para producir</label><select id="tpf-file"><option value="">Sin verificar</option><option ${p.archivoListo==='Sí'?'selected':''}>Sí</option><option ${p.archivoListo==='No'?'selected':''}>No</option></select></div><div class="tpc-field tpc-full"><label>Instrucciones de producción</label><textarea id="tpf-instructions" rows="3">${esc(p.instruccionesProduccion||'')}</textarea></div></div></div><div class="tpf-section"><div class="tpf-section-title"><b>Archivos de la OT</b><span class="tpf-help">Misma carpeta creada desde Venta</span></div><div class="tpf-drive">📁 <span style="flex:1">${o.driveFolderUrl?'Carpeta de Drive vinculada a esta OT':'Esta OT todavía no tiene carpeta de Drive vinculada'}</span>${o.driveFolderUrl?`<button type="button" class="btn btn-ghost" onclick="window.open('${esc(o.driveFolderUrl)}','_blank')">Abrir / cargar archivos</button>`:''}</div></div>`);};
window.tpfAddProcess=()=>document.getElementById('tpf-processes')?.insertAdjacentHTML('beforeend',procRow({}));
const prevSave=window.tpcSaveQuick;window.tpcSaveQuick=async function(){const m=document.getElementById('tpc-quick-modal'),o=getO(m?.dataset.id);if(!o)return prevSave();const procesos=[...document.querySelectorAll('#tpf-processes .tpf-process')].map((r,i)=>({orden:i+1,recurso:r.querySelector('.tpf-resource')?.value||'',responsable:r.querySelector('.tpf-owner')?.value||'',estado:r.querySelector('.tpf-state')?.value||'Pendiente',fecha:r.querySelector('.tpf-date')?.value||'',indicaciones:r.querySelector('.tpf-notes')?.value||''})).filter(x=>x.recurso||x.indicaciones);const resources=procesos.map(x=>x.recurso).filter(Boolean);saveCatalog([...catalog(),...resources]);const p=P(o),extra={...p,procesos,cantidad:document.getElementById('tpf-qty')?.value||'',medidas:document.getElementById('tpf-size')?.value||'',material:document.getElementById('tpf-material')?.value||'',terminacion:document.getElementById('tpf-finish')?.value||'',materialDisponible:document.getElementById('tpf-stock')?.value||'',archivoListo:document.getElementById('tpf-file')?.value||'',instruccionesProduccion:document.getElementById('tpf-instructions')?.value||''};o.gestionSectores={...(o.gestionSectores||{}),produccion:extra};await prevSave();};
window.tpfNewResource=()=>{const n=prompt('Nombre de la máquina o proceso');if(!n?.trim())return;saveCatalog([...catalog(),n.trim()]);document.querySelectorAll('.tpf-resource').forEach(sel=>{const cur=sel.value;sel.innerHTML=resourceOptions(cur)});};
// + junto a cada selector permite crear recursos sin salir de la OT
const obs=new MutationObserver(()=>document.querySelectorAll('.tpf-resource:not([data-plus])').forEach(sel=>{sel.dataset.plus='1';const b=document.createElement('button');b.type='button';b.className='tpf-plus';b.textContent='+';b.title='Crear máquina o proceso';b.onclick=window.tpfNewResource;sel.parentElement.style.position='relative';sel.parentElement.appendChild(b)}));obs.observe(document.body,{childList:true,subtree:true});
}
install();
})();