// TIZ Produccion - Centro de Control Operativo + Copiloto V1
// Capa compatible: lee datos existentes y no escribe un modelo nuevo todavia.
(()=>{
'use strict';
window.__TIZ_PRODUCCION_COPILOTO_V1__=true;
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>{if(!v)return null;const d=new Date(String(v).length===10?String(v)+'T12:00:00':v);return isNaN(d)?null:d};
const daysTo=v=>{const d=date(v);if(!d)return null;const t=new Date();t.setHours(0,0,0,0);return Math.ceil((d-t)/86400000)};
const sectors=o=>window.getSectoresV35?window.getSectoresV35(o):(o.sectores||{});
const prod=o=>sectors(o).produccion||{};
const design=o=>sectors(o).diseno||{};
const purchases=o=>sectors(o).compras||{};
const placement=o=>sectors(o).colocaciones||{};
const active=o=>['aprobado','en produccion','en producción'].includes(norm(o.estado))&&o.archivado!==true&&o.revisionVigente!==false;
const works=()=>[...(window.DB?.obras||[])].filter(active).sort((a,b)=>(Number(String(b.ot||'').replace(/\D/g,''))||0)-(Number(String(a.ot||'').replace(/\D/g,''))||0));
function priority(o){const p=norm(prod(o).prioridad||o.prioridadProduccion);if(p.includes('urgent'))return 'URGENTE';if(p.includes('alta'))return 'ALTA';return 'NORMAL'}
function status(o){const p=prod(o),e=norm(p.estadoInterno||p.estado);if(e.includes('bloq'))return 'BLOQUEADO';if(p.terminada||e.includes('termin'))return 'TERMINADO';if(e.includes('control'))return 'EN CONTROL';if(e.includes('proceso')||e.includes('produccion'))return 'EN PRODUCCIÓN';if(e.includes('prepar'))return 'PREPARANDO';return 'PENDIENTE'}
function due(o){return placement(o).compromiso||o.fcol_c||prod(o).fechaFinPlan||prod(o).compromiso||o.fprod_c||''}
function blockReason(o){const p=prod(o);return p.motivoBloqueo||p.bloqueoMotivo||p.bloqueo||''}
function assignee(o){const p=prod(o);return p.operadorAsignado||p.responsable||p.asignadoA||'Sin asignar'}
function machine(o){const p=prod(o);return p.maquinaId||p.recurso||p.maquina||''}
function risk(o){const alerts=[],d=daysTo(due(o)),p=prod(o);if(status(o)==='BLOQUEADO')alerts.push(blockReason(o)||'Trabajo bloqueado');if(d!==null&&d<=4&&status(o)!=='TERMINADO')alerts.push(`Fecha necesaria en ${d<0?Math.abs(d)+' días vencida':d+' días'}`);if(!assignee(o)||assignee(o)==='Sin asignar')alerts.push('Sin operador asignado');if(design(o).aprobado===false||norm(design(o).estado)==='pendiente')alerts.push('Diseño/archivo todavía pendiente');if(p.materialesPendientes===true||p.faltaMaterial===true||norm(purchases(o).estado)==='pendiente')alerts.push('Revisar materiales/compras');return alerts}
function suggestions(list){const out=[];list.forEach(o=>{const r=risk(o),d=daysTo(due(o));if(r.length)out.push({level:(d!==null&&d<=2)||status(o)==='BLOQUEADO'?'red':'amber',title:`OT ${o.ot||''} · ${o.cliente||''}`,text:r[0]});if(machine(o)&&!assignee(o))out.push({level:'amber',title:`OT ${o.ot||''} · trabajo para máquina`,text:`${machine(o)} está definido pero falta operador.`});});return out.slice(0,8)}
function thirdParties(){const direct=window.DB?.tercerizaciones||[];if(direct.length)return direct;return works().flatMap(o=>{const p=prod(o),arr=p.tercerizaciones||[];return arr.map(x=>({...x,obraId:o.id,ot:o.ot,cliente:o.cliente}))})}
function ensureStyle(){if(document.getElementById('tiz-prod-control-v1-css'))return;const s=document.createElement('style');s.id='tiz-prod-control-v1-css';s.textContent=`
.tpc{padding-bottom:30px}.tpc-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:14px}.tpc-head h2{font-size:22px;margin:0}.tpc-sub{font-size:11px;color:var(--text3);margin-top:4px}.tpc-kpis{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr));gap:10px;margin-bottom:12px}.tpc-kpi,.tpc-panel{background:var(--surface);border:1px solid var(--border);border-radius:12px}.tpc-kpi{padding:13px}.tpc-kpi small{display:block;color:var(--text3);font-size:9px;text-transform:uppercase}.tpc-kpi b{display:block;font:600 24px 'DM Mono',monospace;margin-top:5px}.tpc-grid{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(300px,.55fr);gap:12px}.tpc-panel{padding:12px}.tpc-title{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-bottom:10px}.tpc-title b{font-size:13px}.tpc-title span{font-size:9px;color:var(--text3)}.tpc-table{width:100%;border-collapse:collapse;font-size:10px}.tpc-table th{font-size:8px;color:var(--text3);text-transform:uppercase;text-align:left;padding:7px;border-bottom:1px solid var(--border)}.tpc-table td{padding:9px 7px;border-bottom:1px solid var(--border);vertical-align:middle}.tpc-pill{display:inline-block;padding:4px 7px;border-radius:99px;font-size:8px;background:rgba(91,156,246,.12);color:#79adff}.tpc-pill.red{background:rgba(224,92,92,.14);color:#ff7878}.tpc-pill.amber{background:rgba(232,160,32,.14);color:#ffc05b}.tpc-pill.green{background:rgba(76,175,125,.14);color:#61d79a}.tpc-suggestion{padding:9px;border:1px solid var(--border);border-left:3px solid var(--amber);border-radius:8px;background:var(--surface2);margin:7px 0;font-size:10px}.tpc-suggestion.red{border-left-color:var(--red)}.tpc-suggestion b{display:block;margin-bottom:3px}.tpc-section{margin-top:12px}.tpc-empty{padding:18px;text-align:center;color:var(--text3);font-size:10px}.tpc-legacy{margin-top:12px;padding-top:12px;border-top:1px solid var(--border)}@media(max-width:1050px){.tpc-grid{grid-template-columns:1fr}.tpc-kpis{grid-template-columns:repeat(2,1fr)}}`;
document.head.appendChild(s)}
function badge(v){const cls=v==='URGENTE'||v==='BLOQUEADO'?'red':v==='ALTA'?'amber':v==='TERMINADO'?'green':'';return `<span class="tpc-pill ${cls}">${esc(v)}</span>`}
function rows(list){return list.slice(0,30).map(o=>{const r=risk(o);return `<tr onclick="window.openSectorFichaV31&&openSectorFichaV31('${esc(o.id)}','Producción')" style="cursor:pointer"><td><b>OT ${esc(o.ot)}</b><br><span style="color:var(--text3)">${esc(o.cliente||'')}</span></td><td>${badge(priority(o))}</td><td>${badge(status(o))}${r[0]?`<br><span style="font-size:8px;color:var(--text3)">${esc(r[0])}</span>`:''}</td><td>${esc(assignee(o))}</td><td>${esc(machine(o)||'—')}</td><td>${esc(due(o)||'Sin fecha')}</td></tr>`}).join('')}
function render(){const root=document.getElementById('produccion-v34-root');if(!root)return false;ensureStyle();const list=works(),sug=suggestions(list),third=thirdParties();const blocked=list.filter(o=>status(o)==='BLOQUEADO').length,attention=list.filter(o=>risk(o).length).length,machines=list.filter(o=>!!machine(o)&&status(o)!=='TERMINADO').length,materials=list.filter(o=>risk(o).some(x=>/material|compra/i.test(x))).length;root.innerHTML=`<div class="tpc"><div class="tpc-head"><div><h2>Producción hoy</h2><div class="tpc-sub">Centro de control operativo · pendientes, bloqueos, responsables y riesgos.</div></div><span class="tpc-pill">Copiloto V1 · sugerencias</span></div><div class="tpc-kpis"><div class="tpc-kpi"><small>Requieren atención</small><b>${attention}</b></div><div class="tpc-kpi"><small>Bloqueadas</small><b>${blocked}</b></div><div class="tpc-kpi"><small>Materiales pendientes</small><b>${materials}</b></div><div class="tpc-kpi"><small>Trabajos para máquina</small><b>${machines}</b></div></div><div class="tpc-grid"><div><section class="tpc-panel"><div class="tpc-title"><b>Trabajos pendientes</b><span>${list.length} OT activas</span></div><div style="overflow:auto"><table class="tpc-table"><thead><tr><th>OT</th><th>Prioridad</th><th>Estado / bloqueo</th><th>Operador</th><th>Máquina / recurso</th><th>Fecha necesaria</th></tr></thead><tbody>${rows(list)||'<tr><td colspan="6" class="tpc-empty">No hay trabajos activos.</td></tr>'}</tbody></table></div></section><section class="tpc-panel tpc-section"><div class="tpc-title"><b>Seguimiento de tercerizaciones</b><span>Base preparada para follow-up</span></div>${third.length?`<div style="overflow:auto"><table class="tpc-table"><thead><tr><th>OT</th><th>Proveedor</th><th>Trabajo</th><th>Prometido</th><th>Follow-up</th><th>Estado</th></tr></thead><tbody>${third.slice(0,12).map(x=>`<tr><td>${esc(x.ot||x.obraId||'')}</td><td>${esc(x.proveedor||x.proveedorNombre||x.proveedorId||'')}</td><td>${esc(x.descripcion||x.trabajo||'')}</td><td>${esc(x.fechaPrometida||'')}</td><td>${esc(x.proximoFollowUp||'')}</td><td>${esc(x.estado||'')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="tpc-empty">Todavía no hay tercerizaciones estructuradas disponibles en la base cargada.</div>'}</section></div><aside><section class="tpc-panel"><div class="tpc-title"><b>Copiloto TIZ</b><span>Sugerencias para anticiparse</span></div>${sug.map(x=>`<div class="tpc-suggestion ${x.level==='red'?'red':''}"><b>${esc(x.title)}</b>${esc(x.text)}</div>`).join('')||'<div class="tpc-suggestion"><b>Sin alertas críticas</b>No detectamos riesgos con las reglas disponibles.</div>'}<div style="font-size:9px;color:var(--text3);margin-top:10px">V1 usa reglas determinísticas sobre datos existentes. No ejecuta acciones automáticamente.</div></section></aside></div></div>`;return true}
window.renderProduccionCopilotoV1=render;
function hook(){const old=window.renderProduccionV34;if(typeof old==='function'&&!old.__tpcWrapped){const wrapped=function(){const r=old.apply(this,arguments);setTimeout(render,0);return r};wrapped.__tpcWrapped=true;window.renderProduccionV34=wrapped}render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(hook,0));else setTimeout(hook,0);
setInterval(()=>{if(document.getElementById('produccion-v34-root')?.offsetParent)render()},5000);
})();
