const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const root=path.join(__dirname,'..');
function setup(o,rows){const writes=[];const window={DB:{obras:[o],presupuestos:[],clientes:[]},leerFacturacionBaseMadreTIZV123:async()=>({rows,firstRow:3}),updateDoc_:async(_,id,patch)=>writes.push({id,patch})};vm.runInNewContext(fs.readFileSync(path.join(root,'facturacionCobranzasDataV2.js'),'utf8'),{window,console,Date,Intl});vm.runInNewContext(fs.readFileSync(path.join(root,'facturacionBaseMadreReconcileV2.js'),'utf8'),{window,console,Date});return{window,writes}}
function sheet(number='1472.0',status='Cobrado',net=100){const r=Array(26).fill('');Object.assign(r,{2:'4708',3:'Cartel',5:'Cliente',6:String(net),7:String(net*1.21),17:'07/09/26',18:number,24:status});return r}
function obra(){return{id:'o',ot:'4708',cliente:'Cliente',nrfc:'1472.0',neto:100}}
test('normaliza un entero histórico con .0 y completa sus importes sin duplicar FC',async()=>{const o=obra(),{window}=setup(o,[sheet()]);const r=await window.TIZFactBaseMadreV2.audit();assert.equal(r.items[0].tipo,'datos');await window.TIZFactBaseMadreV2.importOne(r.items[0]);const w=window.TIZFacturacionCobranzasDataV2.build().workItems[0];assert.equal(w.invoices.length,1);assert.equal(w.invoices[0].numeroCompleto,'1472');assert.equal(w.facturadoTotal,121);assert.equal(w.cobradoPct,100);assert.equal(w.porCobrar,0)});
test('cobro real e histórico de la misma FC no descuentan dos veces del saldo',()=>{const o=obra();o.facturasBaseMadre=[{numeroCompleto:'1472',neto:100,total:121},{numeroCompleto:'1473',neto:100,total:121}];o.historicoExcel={facturasCobradas:['1472']};o.cobros=[{id:'cob-1',importe:121,fecha:'2026-09-29'}];const {window}=setup(o,[]);const w=window.TIZFacturacionCobranzasDataV2.build().workItems[0];assert.equal(w.facturadoTotal,242);assert.equal(w.porCobrar,121);assert.equal(w.cobradoPct,50)});
test('un número fiscal débil no marca cobradas FC de dos puntos de venta',()=>{const o=obra();o.nrfc='';o.facturasArca=[{numeroCompleto:'00003-00001472',cbteTipo:1,ptoVta:3,cbteNro:1472,cae:'a',neto:100,total:121},{numeroCompleto:'00009-00001472',cbteTipo:1,ptoVta:9,cbteNro:1472,cae:'b',neto:100,total:121}];o.historicoExcel={facturasCobradas:['1472']};const {window}=setup(o,[]);const w=window.TIZFacturacionCobranzasDataV2.build().workItems[0];assert.equal(w.cobradoHistoricoFacturas,0);assert.equal(w.porCobrar,242)});
test('Cobrado pendiente se conserva sin inventar el importe de un cobro',async()=>{const o=obra(),{window,writes}=setup(o,[sheet('1472','Cobrado pendiente')]);const r=await window.TIZFactBaseMadreV2.audit();await window.TIZFactBaseMadreV2.importOne(r.items[0]);const w=window.TIZFacturacionCobranzasDataV2.build().workItems[0];assert.equal(w.estadoOperativo,'cobrado_pendiente');assert.equal(w.cobrado,0);assert.equal(w.porCobrar,121);assert.equal(writes[0].patch.cobros,undefined)});
test('diferencia de importe e invoice compuesto quedan pendientes de revisión',async()=>{const o=obra();const {window,writes}=setup(o,[sheet('1472 / 1473','Cobrado',200)]);const r=await window.TIZFactBaseMadreV2.audit();assert.equal(r.items[0].safeImport,false);assert.equal(writes.length,0)});
test('aplicar el lote vuelve a leer y descarta un cliente cambiado',async()=>{const o=obra(),r1=sheet(),{window,writes}=setup(o,[r1]);const r=await window.TIZFactBaseMadreV2.audit();r1[5]='Otro cliente';const result=await window.TIZFactBaseMadreV2.applySafe(r);assert.equal(result.aplicadas,0);assert.equal(writes.length,0)});
