'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.join(__dirname,'..'),C=require('../functions/colocacionesCoreV129');
const action=(id='a')=>({id,titulo:'Relevar anclajes',tipo:'Relevamiento',fecha:'2026-10-08',responsable:'Ariel',estado:'Pendiente',todoDia:true,direccion:'Av. Córdoba 1200, CABA',actualizadoEn:'v1'});
const work=()=>({id:'o',ot:'4573',cliente:'Cliente prueba',desc:'Cartel',driveFolderId:'parent',neto:987654,infoPresupuesto:{importe:987654},colocacionesGestion:{tipoTrabajo:'Letras',acciones:{a:action()},preparacion:{final:{estado:'Pendiente',detalle:'Revisar'}},notas:{x:{tipo:'Ayudamemoria',texto:'Llevar escalera'}}}});
function database(initial={}){const docs=new Map(Object.entries(initial).map(([k,v])=>[k,structuredClone(v)]));let writes=0;const apply=(obj,p)=>{for(const [key,v]of Object.entries(p)){const a=key.split('.');let x=obj;for(const k of a.slice(0,-1))x=x[k]||=( {} );x[a.at(-1)]=structuredClone(v)}};const collection=n=>({doc:id=>{const k=n+'/'+id;return {id,get:async()=>({exists:docs.has(k),data:()=>structuredClone(docs.get(k))}),update:async p=>{if(!docs.has(k))throw Error('missing');apply(docs.get(k),p);writes++},_key:k}},limit:()=>({get:async()=>({size:docs.size,docs:[...docs].filter(([k])=>k.startsWith(n+'/')).map(([k,v])=>({id:k.split('/')[1],data:()=>structuredClone(v)}))})})});return {docs,collection,writeCount:()=>writes,runTransaction:async fn=>{const pending=[];const result=await fn({get:ref=>ref.get(),set:(ref,data)=>pending.push(()=>{docs.set(ref._key,structuredClone(data));writes++}),update:(ref,p)=>pending.push(()=>{apply(docs.get(ref._key),p);writes++})});pending.forEach(f=>f());return result}}}
function backend(db,drive={}){const exports={},admin={apps:[{}],auth:()=>({verifyIdToken:async token=>({email:token})}),firestore:()=>db};const filename=path.join(root,'functions/colocacionesGeneralV129.js'),source=fs.readFileSync(filename,'utf8');vm.runInNewContext(source+'\nexports.Test={operator,saveDraft,linkDraft,planVisits,makePdf,archive,folder};',{exports,console,Buffer,Date,Set,Map,require:n=>n==='firebase-admin'?admin:n==='googleapis'?{google:{drive:()=>drive,auth:{GoogleAuth:class {},OAuth2:class{setCredentials(){}}}}}:n==='firebase-functions/v2/https'?{onRequest:(_o,h)=>h}:n==='./colocacionesCoreV129'?C:n==='pdfkit'?require('../functions/node_modules/pdfkit'):require(n)});return exports}
test('semanas ISO conservan año al cruzar diciembre y enero',()=>{assert.equal(C.week('2026-12-31').label,'2026-W53');assert.equal(C.week('2027-01-03').label,'2026-W53');assert.equal(C.week('2027-01-04').label,'2027-W01');assert.equal(C.week('2026-10-08').start,'2026-10-05');assert.equal(C.week('').label,'Sin fecha')});
test('zona CABA se reconoce por domicilio; Buenos Aires sin localidad no se adivina',()=>{assert.equal(C.zone('Av Córdoba 1000, Capital Federal'),'CABA');assert.equal(C.zone('Mosconi 1234, Buenos Aires'),'');assert.equal(C.zone('Calle 1','San Miguel'),'San Miguel')});
test('sugerencias sólo incluyen visitas abiertas compatibles; no llamadas, bloqueos ni fechas lejanas',()=>{const row=(key,a,type='Letras')=>({key,accion:a,tipoTrabajo:type}),anchor=row('o/a',action()),rows=[anchor,row('b/a',{...action(),fecha:'2026-10-07'}),row('c/a',{...action(),direccion:'Calle 2',zona:'Zona Norte'}),row('d/a',{...action(),estado:'Cerrada'}),row('e/a',{...action(),estado:'Bloqueada'}),row('f/a',{...action(),tipo:'Planos'}),row('g/a',{...action(),fecha:'2026-10-19'}),row('h/a',{...action(),tipo:'Entrega'},'Placas')];const out=C.nearby(rows,anchor,'2026-10-08');assert.deepEqual(out.map(r=>r.key),['b/a','h/a']);assert.match(out[0].motivo,/vencido/);assert.equal(C.nearby(rows,{...anchor,accion:{...action(),tipo:'Seguimiento'}},'2026-10-08').length,0)});
test('plan conserva fecha anterior y rechaza versiones cambiadas sin cerrar ni tocar producción',()=>{const o=work(),p=C.planPatch(o,[{actionId:'a',version:'v1',fecha:'2026-10-08'}],'2026-10-09','salida','Ariel','at');assert.equal(p['colocacionesGestion.acciones.a'].fechaAnterior,'2026-10-08');assert.equal(p['colocacionesGestion.acciones.a'].estado,'Pendiente');assert.equal(Object.keys(p).every(k=>k.startsWith('colocacionesGestion.')),true);assert.throws(()=>C.planPatch(o,[{actionId:'a',version:'v0',fecha:'2026-10-08'}],'2026-10-09','id','u','at'),/modificada/)});
test('base sin OT permite fecha pendiente y rechaza días inexistentes',()=>{assert.equal(C.cleanAction({id:'a',titulo:'Reparar cartel',cliente:'Referencia'}).fecha,'');assert.throws(()=>C.cleanAction({titulo:'Tarea',fecha:'2026-02-30'}),/Fecha/)});
test('Ariel puede operar y cuentas no habilitadas se rechazan en servidor',async()=>{const b=backend(database()).Test;assert.equal(await b.operator({get:()=> 'Bearer arielbenitezpublicidad@gmail.com'}),'arielbenitezpublicidad@gmail.com');await assert.rejects(b.operator({get:()=> 'Bearer otro@tizpublicidad.com'}),/Sin permiso/);await assert.rejects(b.operator({get:()=>''}),/sesión/)});
test('guardar y asociar es transaccional, conserva detalle y no duplica al reintentar',async()=>{const db=database({'obras/o':work()}),b=backend(db).Test;await b.saveDraft(db,{action:{...action('nuevo'),cliente:'Ref'}},'Ariel');const a=db.docs.get('colocacionesPendientes/nuevo');await b.linkDraft(db,{id:'nuevo',obraId:'o',version:a.actualizadoEn},'Ariel');const writes=db.writeCount();await b.linkDraft(db,{id:'nuevo',obraId:'o',version:a.actualizadoEn},'Ariel');assert.equal(db.writeCount(),writes);assert.equal(db.docs.get('obras/o').colocacionesGestion.acciones.nuevo.titulo,'Relevar anclajes');assert.equal(db.docs.get('colocacionesPendientes/nuevo').obraId,'o');await assert.rejects(b.saveDraft(db,{action:{...action('nuevo'),titulo:'Borrar detalle'},version:a.actualizadoEn},'Ariel'),/vinculado/)});
test('conflicto de borrador y de salida múltiple no producen escrituras parciales',async()=>{const db=database({'obras/o':work(),'obras/p':{...work(),colocacionesGestion:{acciones:{a:{...action(),actualizadoEn:'v2'}}}},'colocacionesPendientes/n':{...action('n'),actualizadoEn:'v2'}}),b=backend(db).Test;await assert.rejects(b.saveDraft(db,{action:action('n'),version:'v1'},'Ariel'),/modificó/);await assert.rejects(b.planVisits(db,{day:'2026-10-09',selections:[{obraId:'o',actionId:'a',fecha:'2026-10-08',version:'v1'},{obraId:'p',actionId:'a',fecha:'2026-10-08',version:'v1'}]},'Ariel'),/modificada/);assert.equal(db.writeCount(),0);assert.equal(db.docs.get('obras/o').colocacionesGestion.acciones.a.fecha,'2026-10-08')});
test('reporte operativo y PDF excluyen importes y comprobantes fiscales',async()=>{const o=work();o.facturaArca={numeroCompleto:'FC-PRIVADA',total:987654};const report=C.report(o,[{nombre:'Ana',cargo:'Arquitecto',telefono:'111'}]);assert.equal(JSON.stringify(report).includes('987654'),false);assert.equal(JSON.stringify(report).includes('FC-PRIVADA'),false);const pdf=await backend(database()).Test.makePdf(report);assert.equal(pdf.subarray(0,4).toString(),'%PDF');assert.ok(pdf.length>1500)});
test('archivo Drive reutiliza ficha y carpeta, repite sin duplicar y conserva error visible',async()=>{const db=database({'obras/o':work()}),files=[{id:'sector',name:'Colocaciones',mimeType:'application/vnd.google-apps.folder'},{id:'pdf',name:'OT 4573 - Colocaciones.pdf',mimeType:'application/pdf'}];let creates=0,updates=0;const drive={files:{get:async()=>({data:{id:'parent',mimeType:'application/vnd.google-apps.folder'}}),list:async x=>({data:{files:x.q.includes("mimeType = 'application/vnd.google-apps.folder'")?[files[0]]:[files[1]]}}),create:async()=>{creates++;throw Error('unexpected create')},update:async()=>{updates++;return {data:{id:'pdf',webViewLink:'https://drive.google.com/file/d/pdf/view'}}}}};const b=backend(db,drive).Test,r=await b.archive(db,{obraId:'o'},'Ariel');assert.equal(r.fileId,'pdf');await b.archive(db,{obraId:'o'},'Ariel');assert.equal(updates,1);assert.equal(creates,0);db.docs.get('obras/o').colocacionesGestion.acciones.a.titulo='Nueva tarea';drive.files.update=async()=>{throw Error('Sin acceso a Drive')};await assert.rejects(b.archive(db,{obraId:'o'},'Ariel'),/Sin acceso/);assert.equal(db.docs.get('obras/o').colocacionesGestion.documento.lockUntil,0);assert.match(db.docs.get('obras/o').colocacionesGestion.documento.error,/Sin acceso/);assert.equal(db.docs.get('obras/o').colocacionesGestion.documento.fileId,'pdf')});
test('cargar acción con OT guarda ambos registros atómicamente y conserva identidad del mirror',async()=>{const db=database({'obras/o':work()}),b=backend(db).Test,result=await b.saveDraft(db,{action:action('directo'),obraId:'o'},'Ariel');assert.equal(result.obraId,'o');assert.equal(db.docs.get('obras/o').colocacionesGestion.acciones.directo.registroId,'sinOT/directo');assert.equal(db.docs.get('colocacionesPendientes/directo').obraId,'o');const before=db.writeCount();await assert.rejects(b.saveDraft(db,{action:action('nuevo'),obraId:'missing'},'Ariel'),/disponible/);assert.equal(db.writeCount(),before);assert.equal(db.docs.has('colocacionesPendientes/nuevo'),false)});
