'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.join(__dirname,'..');
function setup(){const counters={secrets:0,network:0,collections:[]},db={collection:name=>{counters.collections.push(name);return {limit:()=>({get:async()=>({size:0,docs:[]})}),doc:()=>({get:async()=>({exists:false,data:()=>undefined})})}}},admin={apps:[{}],firestore:()=>db,auth:()=>({verifyIdToken:async token=>({email:token})})};
const general={exports:{}},base={console,Buffer,Date,Set,Map};
vm.runInNewContext(fs.readFileSync(path.join(root,'functions/colocacionesGeneralV129.js'),'utf8'),{...base,exports:general.exports,require:n=>n==='firebase-admin'?admin:n==='googleapis'?{google:{}}:n==='./colocacionesCoreV129'?require('../functions/colocacionesCoreV129'):n==='pdfkit'?require('../functions/node_modules/pdfkit'):require(n)});
const module={exports:{}};
vm.runInNewContext(fs.readFileSync(path.join(root,'functions/facturacionIntegralApiV83.js'),'utf8'),{...base,module,fetch:async()=>{counters.network++;throw Error('No se debe emitir');},require:n=>n==='firebase-admin'?admin:n==='googleapis'?{google:{}}:n==='node-forge'?{}:n==='firebase-functions/v2/https'?{onRequest:(_o,h)=>h}:n==='firebase-functions/params'?{defineSecret:name=>({value:()=>{counters.secrets++;return name==='ARCA_ALLOWED_EMAILS'?'info@tizpublicidad.com':''}})}:n==='./colocacionesGeneralV129'?general.exports:n==='./condicionesPagoV127'?require('../functions/condicionesPagoV127'):n==='./arcaFiscalCoreV83'?require('../functions/arcaFiscalCoreV83'):n==='./facturaDrive2026'?{}:require(n)});
async function call({body={},email='',method='POST'}={}){let status=200,result;const req={method,body,get:n=>n==='authorization'?(email?'Bearer '+email:''):n==='origin'?'https://tiz-publicidad.github.io':''},res={set(){},status:n=>{status=n;return res},json:r=>{result=r;return res},send:r=>{result=r;return res}};await module.exports.facturacionIntegralEmitirV83(req,res);return {status,result};}return {counters,call};}
test('Colocaciones valida Ariel con su propia autorización sin leer secretos ni tocar ARCA',async()=>{const x=setup(),r=await x.call({email:'arielbenitezpublicidad@gmail.com',body:{sector:'colocaciones',mode:'list'}});assert.equal(r.status,200);assert.equal(r.result.ok,true);assert.deepEqual(x.counters.collections,['colocacionesPendientes','configuracion']);assert.equal(x.counters.secrets,0);assert.equal(x.counters.network,0)});
test('Colocaciones rechaza tokens ausentes y cuentas no habilitadas antes de consultar datos',async()=>{for(const email of ['', 'otro@example.test']){const x=setup(),r=await x.call({email,body:{sector:'colocaciones',mode:'list'}});assert.equal(r.status,email?403:401);assert.equal(x.counters.collections.length,0);assert.equal(x.counters.network,0);assert.equal(x.counters.secrets,0)}});
test('marcar sector Colocaciones no permite emitir una factura ni acceder a una operación desconocida',async()=>{const x=setup(),r=await x.call({email:'arielbenitezpublicidad@gmail.com',body:{sector:'colocaciones',mode:'emitir',confirmacion:'EMITIR COMPROBANTE REAL PV 00009'}});assert.equal(r.status,400);assert.match(r.result.error,/Operación inválida/);assert.equal(x.counters.network,0);assert.equal(x.counters.secrets,0);assert.equal(x.counters.collections.length,0)});
test('Ariel sigue sin permiso para emitir por el recorrido fiscal',async()=>{const x=setup(),r=await x.call({email:'arielbenitezpublicidad@gmail.com',body:{confirmacion:'EMITIR COMPROBANTE REAL PV 00009'}});assert.equal(r.status,403);assert.equal(x.counters.network,0);assert.equal(x.counters.collections.length,0)});
test('el recorrido fiscal conserva la validación del plazo de pago antes de leer la obra o emitir',async()=>{const x=setup(),r=await x.call({email:'info@tizpublicidad.com',body:{confirmacion:'EMITIR COMPROBANTE REAL PV 00009',obraId:'o',idempotencyKey:'id',cbteTipo:1}});assert.equal(r.status,400);assert.match(r.result.error,/plazo de pago/);assert.equal(x.counters.network,0);assert.equal(x.counters.collections.length,0)});
test('OPTIONS y GET se resuelven antes de las operaciones de ambos sectores',async()=>{for(const [method,status] of [['OPTIONS',204],['GET',405]]){const x=setup(),r=await x.call({method,body:{sector:'colocaciones',mode:'list'}});assert.equal(r.status,status);assert.equal(x.counters.collections.length,0);assert.equal(x.counters.secrets,0)}});
