'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.join(__dirname,'..'),G=require('../functions/colocacionesCoreV129');
const action=(fecha,estado='Pendiente')=>({id:'a',titulo:'Revisar anclajes',responsable:'Ariel',fecha,estado,todoDia:true});
test('por fecha enlaza la Sheet de OT al contacto y Maps usa el domicilio propio de la acción',()=>{
 const w=ui(),g=w.TIZColocacionesGeneralV129;w.canViewPage=()=>true;w.canAnnotateSector=()=>true;
 w.DB.obras=[{id:'o',estado:'Pendiente',ot:'4700',cliente:'Cliente',otSheetUrl:'https://docs.google.com/spreadsheets/d/test_OT/edit#gid=42',colocacionesGestion:{direccion:'Domicilio general 100',acciones:{a:{...action('2026-10-09'),direccion:'Av. Córdoba 1234',zona:'CABA'},b:{...action('2026-10-09'),id:'b',direccion:'San Martín 200',zona:'San Isidro'}}}}];
 const html=g.datesBody('2026-10-05');assert.ok(html.includes('OT · contacto'));assert.ok(html.includes('gid=42'));assert.ok(html.includes('range=FICHA%21D9%3AH10'));assert.ok(html.includes(encodeURIComponent('Av. Córdoba 1234, CABA')));assert.ok(html.includes(encodeURIComponent('San Martín 200, San Isidro')));assert.ok(!html.includes(encodeURIComponent('Domicilio general 100')));
 assert.equal(g.sheetContactLink({otSheetUrl:'javascript:alert(1)'}),'');assert.equal(g.sheetContactLink({}),'');assert.equal(g.mapsLink(''),'');
});
test('histórico contiene las acciones resueltas por fecha real y conserva los indicadores como detalle',()=>{
 const w=ui(),g=w.TIZColocacionesGeneralV129;w.DB.obras=[{id:'o',ot:'4700',cliente:'Cliente',colocacionesGestion:{acciones:{a:{...action('2026-10-09'),titulo:'Pendiente actual'},b:{...action('2026-10-07','Cerrada'),id:'b',titulo:'Terminada reciente',fechaReal:'2026-10-09',resultado:'Trabajo realizado'},c:{...action('2026-10-05','Reprogramada'),id:'c',titulo:'Reprogramación anterior',fechaReal:'2026-10-06'}}}}];
 const html=g.body('historico','2026-10-05'),list=html.split('<details style="margin-top:18px">')[0];assert.ok(list.includes('Terminada reciente'));assert.ok(list.includes('Reprogramación anterior'));assert.ok(list.indexOf('Terminada reciente')<list.indexOf('Reprogramación anterior'));assert.ok(!list.includes('Pendiente actual'));assert.ok(html.includes('Ver indicadores de cumplimiento semanal'));
});
test('apertura queda separada de planificación y el vínculo usa la carpeta OT existente',()=>{
 const w=ui(),g=w.TIZColocacionesGeneralV129;w.canViewPage=()=>true;w.canAnnotateSector=()=>true;
 const row={key:'o/a',obra:{id:'o',ot:'4700',driveFolderId:'Folder_4700'},cliente:'Cliente',accion:{...action('2026-10-15'),fechaApertura:'2026-10-09'}};
 const html=g.inlineRow(row);assert.ok(html.indexOf('name="fechaApertura"')<html.indexOf('name="titulo"'));assert.ok(html.indexOf('name="titulo"')<html.indexOf('name="fecha"'));assert.ok(html.includes('value="2026-10-09"'));assert.ok(html.includes('value="2026-10-15"'));assert.ok(html.includes('href="https://drive.google.com/drive/folders/Folder_4700"'));assert.ok(html.includes('ti-brand-google-drive'));assert.ok(!g.driveLink({driveFolderUrl:'javascript:alert(1)'}).includes('href='));assert.ok(!g.driveLink({}).includes('href='));
 assert.equal(g.openingDate({creadoEn:'2026-10-09T01:00:00Z'}),'2026-10-08');assert.equal(g.openingDate({datosPlanilla:[['Fecha','07/10/2026']]}),'2026-10-07');assert.equal(g.openingDate({}),'');
 const saved=G.cleanAction({...action('2026-10-15'),fechaApertura:'2026-10-09'});assert.equal(saved.fechaApertura,'2026-10-09');assert.equal(saved.fecha,'2026-10-15');assert.throws(()=>G.cleanAction({...action('2026-10-15'),fechaApertura:'2026-02-30'}),/apertura/);
});
test('bloquea anteayer y fechas anteriores, incluidos bloqueados; ayer, sin fecha y cerrados no bloquean',()=>{
 for(const day of ['2026-10-06','2026-09-30'])for(const status of ['Pendiente','Bloqueada'])assert.equal(G.overdue(action(day,status),'2026-10-08'),true);
 for(const a of [action('2026-10-07'),action('2026-10-08'),action(''),action('2026-10-05','Cerrada'),action('2026-10-05','Reprogramada')])assert.equal(G.overdue(a,'2026-10-08'),false);
 assert.equal(G.overdue(action('2026-12-30'),'2027-01-01'),true);
});
test('resolver conserva fecha original y exige motivo, fecha real y nueva fecha vigente',()=>{
 const old=action('2026-10-05'),result={detalle:'Faltó permiso de acceso',fechaReal:'2026-10-08'},next={...old,id:'next',fecha:'2026-10-09'};
 const r=G.resolveDraftAction(old,result,next,'2026-10-08','at','Ariel');assert.equal(r.closed.fecha,'2026-10-05');assert.equal(r.closed.estado,'Reprogramada');assert.equal(r.next.anteriorId,'a');assert.equal(G.overdue(r.next,'2026-10-08'),false);
 assert.throws(()=>G.resolveDraftAction(old,{...result,detalle:''},next,'2026-10-08','at','u'),/resultado/);
 for(const fecha of ['','2026-10-07'])assert.throws(()=>G.resolveDraftAction(old,result,{...next,fecha},'2026-10-08','at','u'));
 assert.throws(()=>G.resolveDraftAction({...old,estado:'Cerrada'},result,null,'2026-10-08','at','u'),/gestionada/);
 assert.equal(G.resolveDraftAction(old,result,null,'2026-10-08','at','u').closed.estado,'Cerrada');
});
function ui(doc,extras={}){const window={DB:{obras:[],clientes:[],presupuestos:[]},TIZColocacionesGeneralCore:G};const c={window,console,Date,Intl,URL,URLSearchParams,TextEncoder,setInterval:()=>{},setTimeout:()=>{},...extras};vm.runInNewContext(fs.readFileSync(path.join(root,'colocacionesV128.js'),'utf8'),c);if(doc)c.document=doc;vm.runInNewContext(fs.readFileSync(path.join(root,'colocacionesGeneralUIV129.js'),'utf8'),c);return window;}
test('base contiene obras pendientes sin acción ni fecha y mantiene acciones con y sin fecha',()=>{
 const w=ui();w.DB.obras=[{id:'1',ot:'4700',cliente:'A',estado:'Pendiente'},{id:'2',ot:'4701',cliente:'B',estado:'Pendiente',colocacionesGestion:{acciones:{a:action(''),b:{...action('2026-10-09'),id:'b'}}}},{id:'3',estado:'Rechazado'}];
 const rows=w.TIZColocacionesGeneralV129.baseRows();assert.equal(rows.length,3);assert.equal(rows.filter(r=>r.obra.id==='1'&&r.empty).length,1);assert.equal(rows.some(r=>r.obra.id==='3'),false);assert.equal(w.TIZColocacionesGeneralV129.entries().length,2);
 const html=w.TIZColocacionesGeneralV129.body('base');for(const text of ['OT / cliente','Responsable','Pendientes','4701','Acción'])assert.ok(html.includes(text));
});
test('calendario renderiza una semana de lunes a domingo y el bloqueo reemplaza la navegación',()=>{
 const source=fs.readFileSync(path.join(root,'colocacionesV128.js'),'utf8');const w=ui();
 const c={window:w,Date,Intl,console,TextEncoder};
 // Execute the actual render helpers with lightweight DOM bindings.
 const start=source.indexOf('  function agendaHTML()'),end=source.indexOf('  function overlay()',start);
 const node={innerHTML:''};w.currentUser={};w.canViewPage=()=>true;w.TIZColocacionesGeneralV129.attach=()=>{};w.TIZColocacionesGeneralV129.load=()=>{};
 vm.runInNewContext(source.slice(start,end)+'\nwindow.testRender=render;window.testAgenda=agendaHTML;',{...c,today:()=> '2026-10-08',shift:G.shift,fmtDate:x=>x,open:G.open,esc:x=>String(x||''),bucket:a=>a.fecha<'2026-10-08'?'vencidas':'proximas',chip:x=>x,canWrite:()=>true,canRead:()=>true,allWorks:()=>[],pending:()=>[],db:()=>w.DB,style:()=>{},pageRoot:()=>node,btn:(text,attr)=>`<button ${attr}>${text}</button>`,state:{view:'agenda'},renderList:()=>{}});
 w.testRender();assert.equal((node.innerHTML.match(/<section class="c128-day /g)||[]).length,8);assert.ok(node.innerHTML.includes('05/10/2026 al 11/10/2026'));assert.ok(node.innerHTML.includes('data-view="historico"'));
 for(const fecha of ['1900-01-06','2026-03-01']){w.DB.obras=[{id:'old',ot:'4350',estado:'Pendiente',fcol_c:fecha}];w.testRender();assert.ok(node.innerHTML.includes('data-view=\"base\"'));assert.ok(!node.innerHTML.includes('data-overdue='));}
 w.DB.obras=[{id:'o',estado:'Pendiente',ot:'4700',colocacionesGestion:{acciones:{a:action('2026-10-06')}}}];w.testRender();assert.ok(node.innerHTML.includes('data-overdue="o/a"'));assert.ok(!node.innerHTML.includes('data-view='));
 w.DB.obras[0].colocacionesGestion.acciones.a.estado='Cerrada';w.testRender();assert.ok(node.innerHTML.includes('data-view="agenda"'));
});
test('resolver sin OT es transaccional y rechaza versiones viejas o identidad repetida',async()=>{
 const docs=new Map([['a',{...action('2026-10-05'),actualizadoEn:'v1'}]]),writes=[];
 const db={collection:()=>({doc:id=>({id})}),runTransaction:async fn=>{const pending=[];await fn({get:async ref=>({exists:docs.has(ref.id),data:()=>docs.get(ref.id)}),set:(ref,data)=>pending.push([ref.id,data])});for(const [id,data]of pending){docs.set(id,data);writes.push(id)}}};
 const source=fs.readFileSync(path.join(root,'functions/colocacionesGeneralV129.js'),'utf8'),exports={};
 vm.runInNewContext(source+'\nexports.resolveDraft=resolveDraft;',{exports,Date,Intl,Buffer,Set,Map,require:n=>n==='firebase-admin'?{apps:[{}]}:n==='googleapis'?{google:{}}:n==='pdfkit'?class{}:n==='./colocacionesCoreV129'?G:require(n)});
 const body={id:'a',version:'v1',result:{detalle:'Resuelto',fechaReal:'2026-10-08'}};
 await assert.rejects(exports.resolveDraft(db,{...body,version:'old'},'u'),/cambió/);assert.equal(writes.length,0);
 await assert.rejects(exports.resolveDraft(db,{...body,next:{...action('2099-01-01'),id:'a'}},'u'),/identidad/);assert.equal(writes.length,0);
 await exports.resolveDraft(db,body,'u');assert.equal(docs.get('a').estado,'Cerrada');assert.equal(docs.get('a').fecha,'2026-10-05');
 await assert.rejects(exports.resolveDraft(db,{...body,version:docs.get('a').actualizadoEn},'u'),/gestionada/);
});

test('preparación exige datos y controles previos según modalidad, sin exigir fotos finales antes de salir',()=>{
 const w=ui(),g=w.TIZColocacionesGeneralV129,r={key:'o/a',obra:{id:'o',colocacionesGestion:{modalidad:'Propia',zona:'CABA',contactos:{c:{id:'c',nombre:'Ana',telefono:'123'}}}},accion:{...action('2026-10-09'),tipo:'Colocación',direccion:'Córdoba 1000, CABA'}};
 assert.ok(g.preparation(r).includes('Producción liberada'));assert.ok(g.preparation(r).includes('Cuadrilla / recursos'));assert.ok(!g.preparation(r).includes('Fotos finales'));
 r.obra.colocacionesGestion.preparacion=Object.fromEntries(['relevamiento','planos','acceso','produccion','kit','cuadrilla'].map(k=>[k,{estado:'Listo'}]));assert.equal(g.preparation(r).length,0);
 r.obra.colocacionesGestion.modalidad='Externa';assert.ok(g.preparation(r).includes('Recepción de planos'));assert.ok(!g.preparation(r).includes('Cuadrilla / recursos'));
 r.obra.colocacionesGestion.preparacion.recibido={estado:'No corresponde',detalle:''};assert.ok(g.preparation(r).includes('Recepción de planos'));r.obra.colocacionesGestion.preparacion.recibido.detalle='No requiere planos';assert.ok(!g.preparation(r).includes('Recepción de planos'));
 r.accion.estado='Cerrada';assert.equal(g.preparation(r).length,0);
});
test('cruces comparan el responsable en toda la base, incluyen medianoche y omiten días completos y tareas cerradas',()=>{
 const w=ui(),g=w.TIZColocacionesGeneralV129,row=(id,fecha,hora,duracion,responsable='Ariel',extra={})=>({key:id,obra:{},accion:{...action(fecha),todoDia:false,hora,duracion,responsable,...extra}}),rows=[row('a','2026-10-09','09:00',60),row('b','2026-10-09','09:30',60,' ariel '),row('c','2026-10-09','10:30',30),row('d','2026-10-09','09:30',60,'Otro'),row('e','2026-10-09','09:30',60,'Ariel',{estado:'Cerrada'}),row('f','2026-10-09','09:30',60,'Ariel',{todoDia:true})];
 const clashes=g.conflicts(rows);assert.deepEqual([...clashes.keys()],['a','b']);assert.deepEqual(Array.from(clashes.get('a')),['b']);
 assert.equal(g.conflicts([row('x','2026-10-09','23:30',90),row('y','2026-10-10','00:15',30)]).size,2);
 assert.equal(g.conflicts([row('x','2026-10-09','09:00',60),row('y','2026-10-10','09:00',30)]).size,0);
});
test('base y calendario comparten acciones, separan sin fecha y ordenan los horarios; render escapa datos',()=>{
 const w=ui();w.DB.obras=[{id:'o',estado:'Pendiente',ot:'123',cliente:'<img src=x>',estado:'Pendiente',colocacionesGestion:{acciones:{a:{...action('2026-10-09'),id:'a',todoDia:false,hora:'15:00',duracion:60},b:{...action('2026-10-09'),id:'b',todoDia:false,hora:'09:00',duracion:30},c:{...action(''),id:'c'},d:{...action('2026-10-09','Cerrada'),id:'d'}}}},{id:'empty',estado:'Pendiente'}];
 w.canViewPage=()=>true;w.canAnnotateSector=()=>true;const g=w.TIZColocacionesGeneralV129,before=JSON.stringify(w.DB);assert.equal(g.baseRows().length,5);assert.deepEqual(Array.from(g.calendarRows(),r=>r.accion.id),['b','a']);const html=g.body();assert.ok(html.includes('name="fecha" aria-label="Fecha planificada" value=""'));assert.equal((html.match(/data-key="o\//g)||[]).length,3);assert.ok(!html.includes('data-key="empty/'));assert.ok(html.includes('data-key="o/a"'));assert.ok(html.includes('&lt;img src=x&gt;'));assert.ok(!html.includes('<img src=x>'));g.conflicts();g.preparation(g.baseRows()[0]);assert.equal(JSON.stringify(w.DB),before);
});
test('buscar una acción filtra el listado sin ocultar los compromisos de otras obras por fecha',()=>{
 const nodes={'g129-style':{},'g134-actions':{innerHTML:''}},events={},w=ui({getElementById:id=>nodes[id]});w.DB.obras=[{id:'one',estado:'Pendiente',ot:'123',cliente:'Uno',estado:'Pendiente',colocacionesGestion:{acciones:{a:action('2026-10-09')}}},{id:'two',estado:'Pendiente',ot:'124',cliente:'Dos',estado:'Pendiente',colocacionesGestion:{acciones:{b:{...action('2026-10-09'),id:'b'}}}}];const g=w.TIZColocacionesGeneralV129;g.attach({addEventListener:(type,fn)=>{events[type]=fn}});events.input({target:{id:'g134-query',value:'Uno'}});assert.ok(nodes['g134-actions'].innerHTML.includes('data-g-action="one/a"'));assert.ok(!nodes['g134-actions'].innerHTML.includes('data-g-action="two/b"'));assert.equal(g.calendarRows().length,2);
});
test('la importación conserva todas las columnas operativas y no asocia por nombre del cliente',()=>{
 const w=ui(),headers=['Semana','Fecha','Día','Obra / OT','Cliente','Tarea / Operación','Responsable','Sector / Máquina','Prioridad','Estado','Fecha compromiso','Fecha Real','Cant. real','Cumplimiento','Control de colocación','Retrabajo','Próxima acción / observaciones'],row=['41','08/10/2026','Jue','123','Cliente','Relevar','','Colocaciones','Alta','Bloqueada','12/10/2026','','','No','Aprobado','Sí','Llevar fotos'];const matrices={Colocaciones:[headers,row]},works=[{id:'one',ot:'123'},{id:'two',ot:'123'}],a=w.TIZColocacionesCore.parseImportRows(matrices,works)[0];assert.equal(a.obraId,'');assert.equal(a.estado,'Bloqueada');assert.equal(a.observaciones,'Llevar fotos');assert.equal(a.control,'Aprobado');assert.equal(a.datosPlanilla.length,headers.length);assert.equal(G.cleanAction(a).datosPlanilla.length,headers.length);assert.equal(a.responsable,'');assert.equal(a.fecha,'2026-10-12');
});
test('el formulario sencillo tiene una sola tarea, fecha y responsable y conserva los campos avanzados',()=>{
 const source=fs.readFileSync(path.join(root,'colocacionesV128.js'),'utf8'),start=source.indexOf('  function actionFields('),end=source.indexOf('  function taskHTML(',start),w={};vm.runInNewContext(source.slice(start,end)+'\nwindow.form=newActionForm({id:"o"});',{window:w,state:{editor:null},esc:x=>String(x||''),options:()=>'',contactOptions:()=>'',logistics:()=>({direccion:'Dirección heredada'}),db:()=>({}),data:()=>({}),btn:()=>'',allWorks:()=>[]});for(const name of ['titulo','fecha','responsable'])assert.equal((w.form.match(new RegExp('name="'+name+'"','g'))||[]).length,1);assert.ok(w.form.includes('Más detalles'));assert.ok(w.form.includes('name="todoDia"'));assert.ok(w.form.includes('name="fecha" value=""'));
});
test('importar una fila terminada sin OT conserva su estado y no inventa una fecha real',async()=>{
 const docs=new Map(),db={collection:()=>({doc:id=>({id})}),runTransaction:async fn=>{const writes=[];await fn({get:async ref=>({exists:docs.has(ref.id),data:()=>docs.get(ref.id)}),set:(ref,data)=>writes.push([ref.id,data])});for(const [id,data]of writes)docs.set(id,data)}},source=fs.readFileSync(path.join(root,'functions/colocacionesGeneralV129.js'),'utf8'),exports={};vm.runInNewContext(source+'\nexports.saveDraftTest=saveDraft;',{exports,Date,Intl,Buffer,Set,Map,require:n=>n==='firebase-admin'?{apps:[{}]}:n==='googleapis'?{google:{}}:n==='pdfkit'?class{}:n==='./colocacionesCoreV129'?G:require(n)});await exports.saveDraftTest(db,{action:{...action('2026-10-06','Cerrada'),origen:'Planilla',datosPlanilla:[['Estado','Terminada'],['Fecha Real','06/10']]}},'Operador');assert.equal(docs.get('a').estado,'Cerrada');assert.equal(docs.get('a').fechaReal,'');assert.equal(docs.get('a').datosPlanilla[1][1],'06/10');await assert.rejects(exports.saveDraftTest(db,{action:action('2026-10-09'),version:docs.get('a').actualizadoEn},'Operador'),/gestionada/);
});
test('cumplimiento distingue plan, terminación, puntualidad, control y retrabajos sin inventar fechas',()=>{
 const w=ui(),g=w.TIZColocacionesGeneralV129;w.TIZColocacionesCore.today=()=> '2026-10-08';const row=(fecha,estado,extra={})=>({accion:{...action(fecha,estado),...extra}}),rows=[row('2026-10-08','Pendiente'),row('2026-10-05','Cerrada',{fechaReal:'2026-10-06'}),row('2026-10-08','Cerrada',{fechaReal:'2026-10-08'}),row('2026-10-07','Reprogramada'),row('2026-10-08','Cerrada'),row('2026-10-07','Cancelada'),row('2026-10-08','Cerrada',{tipo:'Colocación',control:'Sin revisar',fechaReal:'2026-10-08'}),row('2026-10-08','Cerrada',{tipo:'Colocación',control:'Conforme',fechaReal:'2026-10-08'}),row('2026-09-30','Cerrada',{fechaReal:'2026-10-08',retrabajo:'Sí'})],m=g.metrics(rows,'2026-10-05');assert.equal(m.plan,7);assert.equal(m.done,4);assert.equal(m.onTime,2);assert.equal(m.percent,57);assert.equal(m.onTimePercent,29);assert.equal(m.missingReal,1);assert.equal(m.unverified,1);assert.equal(m.reprogrammed,1);assert.equal(m.rework,1);assert.equal(g.metrics(rows,'2027-01-04').percent,null);
});
test('por fecha agrupa las acciones por obra, expone contactos heredados y permite completar ubicación sin alterar origen',()=>{
 const w=ui();w.TIZColocacionesCore.today=()=> '2026-10-08';w.DB.obras=[{id:'o',estado:'Pendiente',ot:'123',cliente:'Cliente',entregaLogistica:{domicilio:'Dirección original',contacto:'Contacto OT',contactoTelefono:'111'},colocacionesGestion:{direccion:'Domicilio de colocación',indicacionesColocacion:'Ingreso por portón',acciones:{a:{...action('2026-10-09'),id:'a'},b:{...action('2026-10-09'),id:'b',titulo:'Confirmar acceso'},c:{...action(''),id:'c'}}}}];const before=JSON.stringify(w.DB),html=w.TIZColocacionesGeneralV129.datesBody('2026-10-05');assert.equal((html.match(/123 · Cliente/g)||[]).length,2);assert.ok(html.includes('Domicilio de colocación'));assert.ok(html.includes('Contacto OT'));assert.ok(html.includes('111'));assert.ok(html.includes('Ingreso por portón'));assert.ok(html.includes('data-open-tab="contactos"'));assert.ok(html.includes('data-open-tab="ubicacion"'));assert.ok(html.includes('Sin fecha'));assert.equal(JSON.stringify(w.DB),before);
});
test('una colocación requiere control conforme para cerrar; reprogramar no exige declarar trabajo terminado',()=>{
 const a={...action('2026-10-08'),tipo:'Colocación'},result={detalle:'Montada',fechaReal:'2026-10-08'};assert.throws(()=>G.resolveDraftAction(a,result,null,'2026-10-08','at','Operador'),/control conforme/);const closed=G.resolveDraftAction(a,{...result,control:'Conforme',retrabajo:'Sí',cantidadReal:'2'},null,'2026-10-08','at','Operador').closed;assert.equal(closed.control,'Conforme');assert.equal(closed.retrabajo,'Sí');assert.equal(closed.cantidadReal,'2');const next={...a,id:'next',fecha:'2026-10-09'};assert.equal(G.resolveDraftAction(a,result,next,'2026-10-08','at','Operador').closed.estado,'Reprogramada');
});
test('los renglones son editables en el listado y la terminación se completa allí mismo',()=>{
 const w=ui();w.canViewPage=()=>true;w.canAnnotateSector=()=>true;w.DB.obras=[{id:'o',estado:'Pendiente',ot:'123',cliente:'Cliente',colocacionesGestion:{acciones:{a:{...action('2026-10-09'),tipo:'Colocación'}}}}];const r=w.TIZColocacionesGeneralV129.entries()[0],html=w.TIZColocacionesGeneralV129.inlineRow(r);for(const name of ['titulo','fecha','responsable','observaciones','detalle','fechaReal','control'])assert.ok(html.includes('name="'+name+'"'));assert.ok(html.includes('data-g-form="inline"'));assert.ok(html.includes('data-g-finish="o/a"'));assert.ok(html.includes('hidden disabled'));assert.ok(!html.includes('data-g-action='));const closed=w.TIZColocacionesGeneralV129.inlineRow({...r,accion:{...r.accion,estado:'Cerrada',control:'Conforme'}});assert.ok(!closed.includes('type="submit"'));assert.ok(closed.includes('readonly'));assert.ok(w.TIZColocacionesGeneralV129.body().includes('data-g-list="historico"'));
});
test('guardado del renglón verifica versión y conserva contactos, hora, prioridad e información previa',async()=>{
 const w=ui(),o={id:'o',colocacionesGestion:{acciones:{a:{...action('2026-10-09'),actualizadoEn:'v1',prioridad:'Media',todoDia:false,hora:'10:00',duracion:60,direccion:'Domicilio',datosPlanilla:[['Dato','Original']]}}}},source=fs.readFileSync(path.join(root,'colocacionesV128.js'),'utf8'),start=source.indexOf('  async function saveInline('),end=source.indexOf('  function actionFromForm(',start);let writes=0;vm.runInNewContext(source.slice(start,end)+'\nwindow.saveRowTest=saveInline;',{window:w,actions:w.TIZColocacionesCore.actions,db:()=>({}),open:G.open,blockers:()=>[],mutate:async(id,fn)=>{const patch=fn(o);writes++;w.TIZColocacionesCore.applyPatch(o,patch);return patch},isoDate:w.TIZColocacionesCore.isoDate,validateAction:w.TIZColocacionesCore.validateAction,resultPatch:w.TIZColocacionesCore.resultPatch,stamp:()=> 'v2',actor:()=> 'Operador'});const fields={titulo:'Confirmar anclajes',fechaApertura:'2026-10-08',fecha:'2026-10-10',responsable:'Ariel',observaciones:'Llevar fotos'};await assert.rejects(w.saveRowTest('o','a',fields,'old'),/modificó/);assert.equal(writes,0);await w.saveRowTest('o','a',fields,'v1');const a=o.colocacionesGestion.acciones.a;assert.equal(a.fechaApertura,'2026-10-08');assert.equal(a.fecha,'2026-10-10');assert.equal(a.titulo,'Confirmar anclajes');assert.equal(a.prioridad,'Media');assert.equal(a.hora,'10:00');assert.equal(a.direccion,'Domicilio');assert.equal(a.datosPlanilla[0][1],'Original');await w.saveRowTest('o','a',fields,'v2',{detalle:'Resuelto',fechaReal:'2026-10-10'});assert.equal(o.colocacionesGestion.acciones.a.estado,'Cerrada');await assert.rejects(w.saveRowTest('o','a',fields,'v2'),/gestionada/);
});
test('crear desde un renglón vincula a la OT elegida y conserva la fecha opcional',async()=>{
 const nodes={'g129-style':{}},events={},requests=[],w=ui({getElementById:id=>nodes[id]}, {FormData:class{constructor(f){this.fields=f.fields}[Symbol.iterator](){return Object.entries(this.fields)[Symbol.iterator]()}}});w.canViewPage=()=>true;w.canAnnotateSector=()=>true;w.DB.obras=[{id:'o',ot:'123',cliente:'Cliente'}];w.TIZColocacionesUIV128={blockers:()=>[],render:()=>{}};w.colocacionesApiV129=async p=>{requests.push(p);return p.mode==='list'?{rows:[]}:{id:p.action.id,obraId:p.obraId}};w.TIZColocacionesGeneralV129.attach({addEventListener:(type,fn)=>events[type]=fn});const error={textContent:''},button={disabled:false},f={dataset:{gForm:'inline',key:'__new__',version:''},fields:{obraId:'o',titulo:'Confirmar ingreso',fechaApertura:'2026-10-08',fecha:'',responsable:'Ariel',observaciones:'Hablar con encargado'},querySelector:s=>s==='.g135-error'?error:button};await events.submit({target:f,preventDefault:()=>{}});const saved=requests.find(p=>p.mode==='save');assert.equal(saved.obraId,'o');assert.equal(saved.action.fechaApertura,'2026-10-08');assert.equal(saved.action.fecha,'');assert.equal(saved.action.cliente,'Cliente');assert.equal(saved.action.observaciones,'Hablar con encargado');assert.equal(error.textContent,'');
});
test('una fecha heredada cambiada desde la OT invalida la edición y se captura una sola vez al guardar',async()=>{
 const w=ui(),o={id:'o',sectores:{colocaciones:{compromiso:'2026-10-09',responsable:'Ariel'}}},source=fs.readFileSync(path.join(root,'colocacionesV128.js'),'utf8'),start=source.indexOf('  async function saveInline('),end=source.indexOf('  function actionFromForm(',start);vm.runInNewContext(source.slice(start,end)+'\nwindow.saveRowTest=saveInline;',{window:w,actions:w.TIZColocacionesCore.actions,db:()=>({}),open:G.open,blockers:()=>[],mutate:async(id,fn)=>{const patch=fn(o);w.TIZColocacionesCore.applyPatch(o,patch);return patch},isoDate:w.TIZColocacionesCore.isoDate,validateAction:w.TIZColocacionesCore.validateAction,resultPatch:w.TIZColocacionesCore.resultPatch,stamp:()=> 'v2',actor:()=> 'Operador'});o.sectores.colocaciones.compromiso='2026-10-10';const fields={titulo:'Coordinar colocación',fecha:'2026-10-10',responsable:'Ariel',observaciones:''};await assert.rejects(w.saveRowTest('o','legacy',fields,'virtual:2026-10-09|Ariel'),/modificó/);assert.equal(o.colocacionesGestion,undefined);await w.saveRowTest('o','legacy',fields,'virtual:2026-10-10|Ariel');assert.equal(o.colocacionesGestion.legacyCapturada,true);assert.equal(w.TIZColocacionesCore.actions(o,{}).length,1);
});
test('teléfono abre llamadas y WhatsApp sólo con país explícito; rechaza texto o extensiones ambiguas',()=>{
 const c=ui().TIZColocacionesCore;assert.equal(c.phoneLinks('+54 9 (11) 1234-5678').whatsapp,'https://wa.me/5491112345678');assert.equal(c.phoneLinks('11 1234-5678').tel,'tel:1112345678');assert.equal(c.phoneLinks('11 1234-5678').whatsapp,'');for(const bad of ['javascript:123456789','123','1234567 ext 22'])assert.equal(c.phoneLinks(bad).tel,'');
});
test('visita conserva origen y acciones; exige confirmación válida y evita pisar una actualización ajena',()=>{
 const c=ui().TIZColocacionesCore,o={id:'o',entregaLogistica:{contacto:'Ana',contactoTelefono:'+54 9 11 12345678'},colocacionesGestion:{acciones:{a:action('2026-10-09')},preparacion:{fotos:{estado:'Pendiente'}},visita:{actualizadoEn:'v1'}}},before=JSON.stringify(o),fields={fechaVisita:'2026-10-09',horaVisita:'09:30',contactoId:'cotizacion',accesoConfirmado:true,materiales:true,vehiculo:true,planosURL:'https://drive.google.com/file/d/plan/view',fotosURL:'https://example.com/fotos'};
 assert.throws(()=>c.visitPatch(o,fields,'old','v2','Ariel'),/Otra persona/);assert.throws(()=>c.visitPatch(o,{...fields,horaVisita:''},'v1','v2','Ariel'),/horario/);assert.throws(()=>c.visitPatch(o,{...fields,fechaVisita:''},'v1','v2','Ariel'),/fecha/);assert.throws(()=>c.visitPatch(o,{...fields,fotosURL:'javascript:alert(1)'},'v1','v2','Ariel'),/http/);assert.equal(JSON.stringify(o),before);
 const p=c.visitPatch(o,fields,'v1','v2','Ariel');assert.deepEqual(Object.keys(p),['colocacionesGestion.visita']);c.applyPatch(o,p);assert.equal(o.colocacionesGestion.visita.checklist.herramientas,false);assert.equal(o.colocacionesGestion.preparacion.fotos.estado,'Pendiente');assert.equal(o.colocacionesGestion.acciones.a.estado,'Pendiente');
});
test('por fecha muestra preparación sólo para su visita y deja links y edición accesibles',()=>{
 const w=ui(),g=w.TIZColocacionesGeneralV129,o={id:'o',colocacionesGestion:{visita:{fecha:'2026-10-09',hora:'09:30',accesoConfirmado:true,indicaciones:'<script>',fotosURL:'https://example.com/fotos',planosURL:'javascript:alert(1)',checklist:{materiales:true,vehiculo:true}}}};
 const html=g.visitSummary(o,'2026-10-09');for(const t of ['Acceso confirmado','09:30','Salida 2/4','Fotos','data-open-tab="salida"','&lt;script&gt;'])assert.ok(html.includes(t));assert.ok(!html.includes('javascript:'));const other=g.visitSummary(o,'2026-10-12');assert.ok(other.includes('Acceso pendiente'));assert.ok(other.includes('Salida 0/4'));assert.ok(!other.includes('Acceso confirmado'));assert.ok(g.contactQuickLinks({nombre:'Ana',telefono:'+5491112345678'}).includes('WhatsApp'));
});
test('el formulario de salida permite completar contactos y recursos y guardar casillas desmarcadas',async()=>{
 const w=ui(),source=fs.readFileSync(path.join(root,'colocacionesV128.js'),'utf8'),o={id:'o',colocacionesGestion:{visita:{actualizadoEn:'v1',checklist:{materiales:true}}}},state={id:'o',busy:false,editor:null,drafts:{},editors:{}},messages=[];let saved;
 const start=source.indexOf('  async function submit('),end=source.indexOf('  function downloadCalendar(',start);
 vm.runInNewContext(source.slice(start,end)+'\nwindow.submitVisit=submit;',{window:w,state,FormData:class{constructor(f){this.fields=f.fields}get(k){return this.fields[k]}[Symbol.iterator](){return Object.entries(this.fields)[Symbol.iterator]()}},blockers:()=>[],obra:()=>o,stamp:()=> 'v2',actor:()=> 'Ariel',db:()=>w.DB,visitPatch:w.TIZColocacionesCore.visitPatch,mutate:async(id,fn)=>{saved=fn(o);w.TIZColocacionesCore.applyPatch(o,saved)},drawModal:()=>{},toast:m=>messages.push(m),error:e=>{throw e}});
 const f={dataset:{form:'visit'},fields:{version:'v1',fechaVisita:'2026-10-09',horaVisita:'',fotosURL:'',planosURL:''},querySelectorAll:()=>[{name:'materiales',checked:false},{name:'herramientas',checked:true}]};await w.submitVisit({target:f,preventDefault:()=>{}});assert.equal(saved['colocacionesGestion.visita'].checklist.materiales,false);assert.equal(saved['colocacionesGestion.visita'].checklist.herramientas,true);assert.equal(messages.length,1);
 const formStart=source.indexOf('  function visitForm('),formEnd=source.indexOf('  window.TIZColocacionesCore',formStart);vm.runInNewContext(source.slice(formStart,formEnd)+'\nwindow.form=visitForm(obra);',{window:w,obra:o,data:x=>x.colocacionesGestion,esc:x=>String(x||''),contactOptions:()=>'<option>Contacto OT</option>',VISIT_CHECKS:{materiales:'Materiales',herramientas:'Herramientas',vehiculo:'Vehículo',responsable:'Responsable'},canWrite:()=>true});for(const name of ['fechaVisita','horaVisita','contactoId','fotosURL','planosURL','accesoConfirmado','materiales','herramientas','vehiculo','responsable'])assert.ok(w.form.includes('name="'+name+'"'));
});
test('cambiar fecha de visita limpia confirmaciones y los borradores conservan casillas desmarcadas',async()=>{
 const source=fs.readFileSync(path.join(root,'colocacionesV128.js'),'utf8'),w={},boxes=[{name:'accesoConfirmado',checked:true},{name:'materiales',checked:true}],f={querySelectorAll:()=>boxes},state={tab:'salida',drafts:{}};
 const start=source.indexOf('  async function change('),end=source.indexOf('  async function sheetJS(',start);vm.runInNewContext(source.slice(start,end)+'\nwindow.changeVisit=change;',{window:w});await w.changeVisit({target:{name:'fechaVisita',closest:()=>f}});assert.ok(boxes.every(x=>!x.checked));
 const draftStart=source.indexOf('  function captureDraft('),draftEnd=source.indexOf('  function restoreDraft(',draftStart);vm.runInNewContext(source.slice(draftStart,draftEnd)+'\nwindow.capture=captureDraft;',{window:w,state,document:{querySelector:()=>f},FormData:class{[Symbol.iterator](){return [][Symbol.iterator]()}}});w.capture();assert.equal(state.drafts.salida.materiales,false);assert.equal(state.drafts.salida.accesoConfirmado,false);
});
test('pendientes de colocación usa exclusivamente Pendiente y Cobrado pendiente de Base Madre',()=>{
 const c=ui().TIZColocacionesCore;
 for(const estado of ['Pendiente',' Cobrado pendiente ','PENDIENTE'])assert.equal(c.pendingInstallation({estado}),true);
 for(const estado of ['Entregado','Entregada','Entregadas','Cobrado','Aprobado','Facturado','Enviado','Pendiente de aprobación',''])assert.equal(c.pendingInstallation({estado,presupuestoId:'p'}),false);
 assert.equal(c.pendingInstallation({estado:'Aprobado',estadoHistoricoExcel:'Cobrado pendiente'}),true);
 assert.equal(c.pendingInstallation({estado:'Aprobado',historicoExcel:{estado:'Pendiente'}}),true);
 assert.equal(c.pendingInstallation({estado:'Entregado',estadoHistoricoExcel:'Pendiente'}),false);
 assert.equal(c.pendingInstallation({estado:'Pendiente',estadoHistoricoExcel:'Entregadas'}),false);
 for(const extra of [{archivado:true},{revisionVigente:false},{revisionOperativa:false},{colocacionesGestion:{cierre:{cerrada:true}}}])assert.equal(c.pendingInstallation({estado:'Pendiente',...extra}),false);
});
test('entregadas salen de acciones abiertas, calendario, selección y bloqueos; sus resultados se conservan',()=>{
 const w=ui(),g=w.TIZColocacionesGeneralV129;w.canViewPage=()=>true;w.canAnnotateSector=()=>true;
 const work=(id,estado)=>({id,ot:id,cliente:'Cliente '+id,estado,colocacionesGestion:{acciones:{a:{...action('2026-10-01'),titulo:'Abierta '+id},b:{...action('2026-10-01','Cerrada'),id:'b',titulo:'Resultado '+id,resultado:'Terminada',fechaReal:'2026-10-02'}}}});
 w.DB.obras=[work('4700','Pendiente'),work('4701','Cobrado pendiente'),work('4100','Entregado'),work('4101','Cobrado'),work('4102','Aprobado')];const before=JSON.stringify(w.DB);
 assert.deepEqual(Array.from(g.entries().filter(r=>G.open(r.accion)),r=>r.obra.id),['4700','4701']);assert.equal(g.calendarRows().length,2);
 const source=fs.readFileSync(path.join(root,'colocacionesV128.js'),'utf8'),start=source.indexOf('  function blockers('),end=source.indexOf('  function render(',start);vm.runInNewContext(source.slice(start,end)+'\nwindow.testBlockers=blockers;',{window:w,today:()=> '2026-10-09'});assert.deepEqual(Array.from(w.testBlockers(),r=>r.obra.id),['4700','4701']);
 const selected=g.inlineRow(null);assert.ok(selected.includes('value="4700"'));assert.ok(!selected.includes('value="4100"'));
 assert.ok(g.historyBody('2026-10-05').includes('Resultado 4100'));assert.equal(JSON.stringify(w.DB),before);
 w.DB.obras[0].estado='Entregado';assert.equal(g.calendarRows().length,1);assert.equal(w.testBlockers().length,1);
});
test('gestión compara cierre real contra plan, usando días corridos sin convertir reprogramaciones en éxito',()=>{
 const w=ui(),g=w.TIZColocacionesGeneralV129;w.TIZColocacionesCore.today=()=> '2026-10-09';
 const a={...action('2026-10-06','Cerrada'),fechaReal:'2026-10-08'};assert.equal(g.performance(a).delay,2);assert.equal(g.performance({...a,fechaReal:'2026-10-06'}).onTime,true);assert.equal(g.performance({...a,fechaReal:'2026-10-05'}).onTime,true);
 assert.equal(g.performance({...a,estado:'Reprogramada'}).done,false);assert.equal(g.performance({...a,fechaReal:''}).missingReal,true);assert.equal(g.performance({...a,fechaReal:'2026-10-10'}).invalidReal,true);assert.equal(g.performance({...a,tipo:'Colocación',control:'Sin revisar'}).unverified,true);assert.equal(g.performance({...a,tipo:'Colocación',control:'Conforme'}).done,true);
 assert.equal(g.performance({...a,fecha:'2024-02-28',fechaReal:'2024-03-01'}).delay,2);assert.equal(g.performance({...a,fecha:''}).onTime,undefined);
});
test('indicadores separan futuras, fechas faltantes, control pendiente, canceladas y cierres fuera de semana',()=>{
 const w=ui(),g=w.TIZColocacionesGeneralV129;w.TIZColocacionesCore.today=()=> '2026-10-09';const row=(fecha,estado,extra={})=>({obra:{},accion:{...action(fecha,estado),...extra}}),rows=[row('2026-10-05','Cerrada',{fechaReal:'2026-10-05'}),row('2026-10-06','Cerrada',{fechaReal:'2026-10-08'}),row('2026-10-07','Pendiente'),row('2026-10-10','Pendiente'),row('2026-10-08','Reprogramada',{fechaReal:'2026-10-08'}),row('2026-10-08','Cerrada'),row('2026-10-07','Cancelada'),row('2026-10-06','Cerrada',{tipo:'Colocación',control:'Sin revisar',fechaReal:'2026-10-06'}),row('2026-10-06','Cerrada',{fechaReal:'2026-10-10'}),row('2026-09-30','Cerrada',{fechaReal:'2026-10-08'}),row('2026-10-05','Pendiente',{virtual:true})];
 const m=g.managementMetrics(rows,'2026-10-05');assert.equal(m.plan,8);assert.equal(m.evaluated,7);assert.equal(m.done,2);assert.equal(m.percent,29);assert.equal(m.onTimePercent,50);assert.equal(m.closedLate,1);assert.equal(m.averageDelay,2);assert.equal(m.overdue,1);assert.equal(m.future,1);assert.equal(m.reprogrammed,1);assert.equal(m.canceled,1);assert.equal(m.missingReal,1);assert.equal(m.unverified,1);assert.equal(m.invalidReal,1);
 const empty=g.managementMetrics(rows,'2026-11-02');assert.equal(empty.percent,null);assert.equal(empty.onTimePercent,null);assert.equal(empty.averageDelay,null);const future=g.managementMetrics([row('2026-10-10','Pendiente')],'2026-10-05');assert.equal(future.percent,null);
});
test('cerrar desde resultados conserva el evento por fecha con el cierre real e indicadores; entregadas sólo conservan eventos resueltos',()=>{
 const w=ui(),c=w.TIZColocacionesCore,g=w.TIZColocacionesGeneralV129;c.today=()=> '2026-10-09';const o={id:'o',ot:'4700',cliente:'Farmacity',estado:'Pendiente',colocacionesGestion:{acciones:{a:{...action('2026-10-06'),titulo:'Confirmar acceso'}}}};w.DB.obras=[o];
 c.applyPatch(o,c.resultPatch(o,'a',{detalle:'Confirmado <portón>',fechaReal:'2026-10-08'},null,'2026-10-09T10:00:00Z','Ariel',w.DB));const before=JSON.stringify(w.DB),html=g.datesBody('2026-10-05');for(const text of ['Confirmar acceso','Planificada: 06/10/2026','Cierre real: 08/10/2026','Cerrada con retraso · 2 día(s)','Confirmado &lt;portón&gt;','Cumplimiento actual','Gestión por responsable','data-open-tab="historico"'])assert.ok(html.includes(text),text);assert.ok(!html.includes('data-g-result="o/a"'));assert.equal(g.managementMetrics(g.entries(),'2026-10-05').closedLate,1);assert.equal(JSON.stringify(w.DB),before);
 o.estado='Entregado';assert.ok(g.datesBody('2026-10-05').includes('Cierre real: 08/10/2026'));assert.equal(g.calendarRows().length,0);
});
test('un cierre en otra semana aparece por fecha real sin duplicar el indicador del plan',()=>{
 const w=ui(),g=w.TIZColocacionesGeneralV129;w.TIZColocacionesCore.today=()=> '2026-10-09';w.DB.obras=[{id:'o',ot:'4700',estado:'Entregado',colocacionesGestion:{acciones:{a:{...action('2026-09-30','Cerrada'),titulo:'Terminada esta semana',fechaReal:'2026-10-08'}}}}];const html=g.datesBody('2026-10-05');assert.ok(html.includes('Gestiones de esta semana con planificación fuera de la semana (1)'));assert.equal((html.match(/Terminada esta semana/g)||[]).length,1);assert.ok(html.includes('Cierre real: 08/10/2026'));assert.equal(g.managementMetrics(g.entries(),'2026-10-05').done,0);assert.equal(g.managementMetrics(g.entries(),'2026-09-28').done,1);
});
