'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const core=require('../functions/colocacionesCoreV129');
function moduleFor(client={}){const module={exports:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../functions/colocacionesSheetV130.js'),'utf8'),{module,Date,Set,Map,require:n=>n==='googleapis'?{google:{sheets:()=>client,auth:{GoogleAuth:class{},OAuth2:class{setCredentials(){}}}}}:n==='./colocacionesCoreV129'?core:require(n)});return module.exports}
const M=moduleFor(),a={id:'a',titulo:'Relevar',fecha:'2026-10-08',estado:'Pendiente',responsable:'Ariel'},o={id:'o',ot:'4573',cliente:'Cliente',neto:999999,facturaArca:{numero:'FC-privada'},entregaLogistica:{domicilio:'Córdoba 100, CABA',contacto:'Ana',contactoTelefono:'123'}};
test('mirror includes only installation data and stable identity across OT association',()=>{const draft=M.rowFor({}, {...a,registroId:'sinOT/a'}),linked=M.rowFor(o,{...a,registroId:'sinOT/a'});assert.equal(draft[0],linked[0]);assert.equal(linked.length,20);assert.equal(linked[3],'4573');assert.equal(linked[9],'CABA');assert.equal(linked[11],'Ana');assert.equal(JSON.stringify(linked).includes('999999'),false);assert.equal(JSON.stringify(linked).includes('FC-privada'),false)});
test('upsert reuses draft row after association, appends new actions and retains unrelated rows',()=>{const existing=[M.HEADERS,M.rowFor({}, {...a,registroId:'sinOT/a'})],row=M.rowFor(o,{...a,registroId:'sinOT/a'}),out=M.upserts(existing,[row,M.rowFor(o,{...a,id:'b'})]);assert.equal(out[0].row,2);assert.equal(out[1].row,3);assert.equal(out[0].values[0][3],'4573');assert.equal(existing[1][3],'');assert.equal(M.upserts([M.HEADERS,row],[row])[0].row,2)});
test('changed headers and duplicate identities block all writes',()=>{assert.throws(()=>M.upserts([['Header manual']],[M.rowFor(o,a)]),/Encabezados/);const row=M.rowFor(o,a);assert.throws(()=>M.upserts([M.HEADERS,row,row],[row]),/duplicados/);assert.throws(()=>M.upserts([M.HEADERS],[row,row]),/duplicada/)});
function dbFor(initial){const docs=new Map(Object.entries(initial).map(([k,v])=>[k,structuredClone(v)]));const collection=n=>({doc:id=>{const key=n+'/'+id;return {get:async()=>({exists:docs.has(key),data:()=>structuredClone(docs.get(key))}),update:async p=>Object.assign(docs.get(key),p),set:async p=>docs.set(key,structuredClone(p)),key}}});return {docs,collection,runTransaction:async f=>{const pending=[];await f({get:r=>r.get(),update:(r,p)=>pending.push(()=>Object.assign(docs.get(r.key),p))});pending.forEach(f=>f())}}}
test('configuration is restricted to administration',async()=>{await assert.rejects(M.configureSheet(dbFor({}),{sheetUrl:'test'},'Ariel'),/administración/)});
test('sync reads fresh source, skips linked drafts, writes RAW and releases lease',async()=>{const db=dbFor({['configuracion/'+M.SETTINGS]:{spreadsheetId:'test',url:'https://example.test'},'obras/o':{...o,colocacionesGestion:{acciones:{a}}},'colocacionesPendientes/a':{...a,obraId:'o'}}),writes=[];const client={spreadsheets:{get:async()=>({data:{sheets:[]}}),values:{get:async()=>({data:{values:[M.HEADERS]}}),batchUpdate:async p=>writes.push(p)}}};const x=moduleFor(client),result=await x.syncSheet(db,{obras:['o'],drafts:['a']},'Ariel');assert.equal(result.count,1);assert.equal(writes[0].requestBody.valueInputOption,'RAW');assert.equal(writes[0].requestBody.data[0].values[0][5],'Relevar');assert.equal(db.docs.get('configuracion/'+M.SETTINGS).lockUntil,0)});
test('formula destinations are not overwritten; failure remains visible and retry lease clears',async()=>{const db=dbFor({['configuracion/'+M.SETTINGS]:{spreadsheetId:'test'},'obras/o':{...o,colocacionesGestion:{acciones:{a}}}});let writes=0;const client={spreadsheets:{get:async()=>({data:{sheets:[{data:[{rowData:[{values:[{userEnteredValue:{formulaValue:'=SUM(A1)'}}]}]}]}]}}),values:{get:async()=>({data:{values:[M.HEADERS]}}),batchUpdate:async()=>writes++}}};await assert.rejects(moduleFor(client).syncSheet(db,{obras:['o']},'Ariel'),/fórmulas/);assert.equal(writes,0);assert.match(db.docs.get('configuracion/'+M.SETTINGS).error,/fórmulas/);assert.equal(db.docs.get('configuracion/'+M.SETTINGS).lockUntil,0)});

test('lee únicamente las pestañas originales, respeta sus dimensiones y no escribe ni configura el Sheet',async()=>{
 const reads=[],client={spreadsheets:{get:async()=>({data:{sheets:[{properties:{title:'Colocaciones',gridProperties:{rowCount:40,columnCount:19}}},{properties:{title:'Histórico',gridProperties:{rowCount:15,columnCount:22}}},{properties:{title:'TIZZ - Acciones',gridProperties:{rowCount:2001,columnCount:20}}}]}}),values:{get:async p=>{reads.push(p);return {data:{values:[['Tarea / Operación']]}}}}}};const r=await moduleFor(client).readSource({}, {sheetUrl:'https://docs.google.com/spreadsheets/d/test_sheet_id/edit'});assert.deepEqual(Object.keys(r.matrices),['Colocaciones','Histórico']);assert.deepEqual(reads.map(p=>p.range),["'Colocaciones'!A1:S40","'Histórico'!A1:V15"]);assert.ok(reads.every(p=>p.valueRenderOption==='FORMATTED_VALUE'));
 await assert.rejects(moduleFor(client).readSource({}, {sheetUrl:'no es una planilla'}),/enlace/);
});
test('planilla equivocada o más filas de las que se pueden leer no producen una importación parcial',async()=>{
 const client={spreadsheets:{get:async()=>({data:{sheets:[{properties:{title:'Otro'}}]}}),values:{}}};await assert.rejects(moduleFor(client).readSource({}, {sheetUrl:'https://docs.google.com/spreadsheets/d/test/edit'}),/Colocaciones/);
 client.spreadsheets.get=async()=>({data:{sheets:[{properties:{title:'Colocaciones',gridProperties:{rowCount:4000,columnCount:22}}}]}});client.spreadsheets.values.get=async()=>({data:{values:Array.from({length:2001},(_,i)=>i===2000?['hay otra tarea']:[])}});await assert.rejects(moduleFor(client).readSource({}, {sheetUrl:'https://docs.google.com/spreadsheets/d/test/edit'}),/límite/);
});
